#!/usr/bin/env bash

alias v='nvim'

# https://man.openbsd.org/cp#i
# https://man.openbsd.org/cp#v
# https://man.openbsd.org/mv#i
# https://man.openbsd.org/mv#v
# https://man.openbsd.org/rm#i
# https://man.openbsd.org/rm#v
# https://man.openbsd.org/mkdir#p
# https://man.openbsd.org/mkdir#v
#
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'
alias mkdir='mkdir -pv'

# https://man.archlinux.org/man/extra/tree/tree.1.en#filesfirst
#
alias tree='tree --filesfirst'
