-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "purple"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.documentation", { link = "@comment" })
hi(0, "@comment.error", { link = "@text.danger" })
hi(0, "@comment.note", { link = "@text.note" })
hi(0, "@comment.todo", { link = "@text.todo" })
hi(0, "@comment.warning", { link = "@text.warning" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@debug", { link = "Debug" })
hi(0, "@define", { link = "Define" })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@exception", { link = "Exception" })
hi(0, "@field", { link = "Identifier" })
hi(0, "@float", { link = "Float" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@function.method", { link = "@method" })
hi(0, "@function.method.call", { link = "@method.call" })
hi(0, "@include", { link = "Include" })
hi(0, "@keyword.conditional", { link = "@keyword" })
hi(0, "@keyword.conditional.ternary", { link = "Keyword" })
hi(0, "@keyword.coroutine", { link = "@keyword" })
hi(0, "@keyword.debug", { bold = true, fg = "#007c65" })
hi(0, "@keyword.directive", { bold = true, fg = "#001f7d" })
hi(0, "@keyword.directive.define", { link = "@keyword.directive" })
hi(0, "@keyword.exception", { link = "@keyword" })
hi(0, "@keyword.function", { link = "@keyword" })
hi(0, "@keyword.import", { bold = true, fg = "#001f7d" })
hi(0, "@keyword.operator", { link = "@keyword" })
hi(0, "@keyword.repeat", { link = "@keyword" })
hi(0, "@keyword.return", { bold = true, fg = "#772200" })
hi(0, "@keyword.storage", { bold = true, fg = "#2e2e33" })
hi(0, "@lsp.mod.defaultLibrary", { link = "Special" })
hi(0, "@lsp.mod.deprecated", { fg = "#6a003e" })
hi(0, "@lsp.type.class", { link = "@structure" })
hi(0, "@lsp.type.decorator", { link = "@function" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.macro", { link = "@macro" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.struct", { link = "@structure" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@macro", { link = "Macro" })
hi(0, "@markup.environment", { link = "@module" })
hi(0, "@markup.heading", { link = "@text.title" })
hi(0, "@markup.italic", { link = "@text.emphasis" })
hi(0, "@markup.link", { link = "@text.reference" })
hi(0, "@markup.link.label", { link = "@markup.link" })
hi(0, "@markup.link.url", { fg = "#2e2e33", underline = true })
hi(0, "@markup.list", { link = "@punctuation.special" })
hi(0, "@markup.list.checked", { link = "DiagnosticOk" })
hi(0, "@markup.list.unchecked", { link = "DiagnosticWarn" })
hi(0, "@markup.math", { link = "@string.special" })
hi(0, "@markup.quote", { link = "@string.special" })
hi(0, "@markup.raw", { link = "@text.literal" })
hi(0, "@markup.raw.block", { link = "@markup.raw" })
hi(0, "@markup.strikethrough", { link = "@text.strikethrough" })
hi(0, "@markup.strong", { link = "@text.strong" })
hi(0, "@markup.underline", { link = "@text.underline" })
hi(0, "@method", { link = "Function" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@module", { link = "@namespace" })
hi(0, "@module.builtin", { link = "@variable.builtin" })
hi(0, "@namespace", { link = "Identifier" })
hi(0, "@none", { link = "Normal" })
hi(0, "@number.float", { link = "@float" })
hi(0, "@parameter", { fg = "#001f7d" })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@punctuation.bracket", { link = "@punctuation" })
hi(0, "@punctuation.delimiter", { link = "@punctuation" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "StorageClass" })
hi(0, "@string.documentation", { link = "@string" })
hi(0, "@string.escape", { link = "SpecialChar" })
hi(0, "@string.regexp", { link = "SpecialChar" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.path", { link = "Directory" })
hi(0, "@string.special.symbol", { link = "@constant" })
hi(0, "@string.special.url", { link = "@markup.link.url" })
hi(0, "@structure", { link = "Structure" })
hi(0, "@symbol", { link = "Keyword" })
hi(0, "@tag.attribute", { link = "@tag" })
hi(0, "@tag.delimiter", { link = "@punctuation" })
hi(0, "@text.danger", { link = "ErrorMsg" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.literal", { link = "Special" })
hi(0, "@text.note", { link = "MoreMsg" })
hi(0, "@text.reference", { link = "Identifier" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@text.warning", { link = "WarningMsg" })
hi(0, "@type.builtin", { link = "Special" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@type.qualifier", { link = "StorageClass" })
hi(0, "@variable", { fg = "#2e2e33" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "@variable.member", { link = "@field" })
hi(0, "@variable.parameter", { link = "@parameter" })
hi(0, "Added", { fg = "#426200" })
hi(0, "Beacon", { bg = "#0d0d11" })
hi(0, "Bold", { bold = true })
hi(0, "BufferCurrent", { bg = "#e2e2e9", bold = true, fg = "#2f0d79" })
hi(0, "BufferCurrentIcon", { bg = "#e2e2e9" })
hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
hi(0, "BufferCurrentMod", { bg = "#c2c2c9", bold = true, fg = "#2f0d79" })
hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
hi(0, "BufferCurrentTarget", { bg = "#a2a2a8", bold = true, fg = "#2f0d79" })
hi(0, "BufferInactive", { bg = "#ebebf2", fg = "#2e2e33" })
hi(0, "BufferInactiveIcon", { bg = "#ebebf2" })
hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
hi(0, "BufferInactiveMod", { bg = "#c2c2c9", fg = "#2e2e33" })
hi(0, "BufferInactiveSign", { link = "BufferInactive" })
hi(0, "BufferInactiveTarget", { bg = "#a2a2a8", fg = "#2e2e33" })
hi(0, "BufferLineBuffer", { fg = "#66666c" })
hi(0, "BufferLineBufferSelected", { bold = true, fg = "#2e2e33" })
hi(0, "BufferLineBufferVisible", { fg = "#2e2e33" })
hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
hi(0, "BufferLineFill", { link = "Normal" })
hi(0, "BufferLineTab", { bg = "#426200", fg = "#e2e2e9" })
hi(0, "BufferLineTabSelected", { bg = "#426200", bold = true, fg = "#e2e2e9" })
hi(0, "BufferOffset", { link = "Normal" })
hi(0, "BufferTabpageFill", { link = "Normal" })
hi(0, "BufferTabpages", { bg = "#426200", bold = true, fg = "#e2e2e9" })
hi(0, "BufferVisible", { bg = "#e2e2e9", bold = true, fg = "#2e2e33" })
hi(0, "BufferVisibleIcon", { bg = "#e2e2e9" })
hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
hi(0, "BufferVisibleMod", { bg = "#c2c2c9", bold = true, fg = "#2e2e33" })
hi(0, "BufferVisibleSign", { link = "BufferVisible" })
hi(0, "BufferVisibleTarget", { bg = "#a2a2a8", bold = true, fg = "#2e2e33" })
hi(0, "Changed", { fg = "#007c65" })
hi(0, "CmpItemAbbr", { fg = "#2e2e33" })
hi(0, "CmpItemAbbrDeprecated", { link = "Comment" })
hi(0, "CmpItemAbbrMatch", { bold = true })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true })
hi(0, "CmpItemKind", { fg = "#2e2e33" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindColor", { link = "Special" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstructor", { link = "Type" })
hi(0, "CmpItemKindEnum", { link = "Structure" })
hi(0, "CmpItemKindEnumMember", { link = "Structure" })
hi(0, "CmpItemKindEvent", { link = "Exception" })
hi(0, "CmpItemKindField", { link = "Structure" })
hi(0, "CmpItemKindFile", { link = "Tag" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindInterface", { link = "Structure" })
hi(0, "CmpItemKindKeyword", { link = "Keyword" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindModule", { link = "Structure" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindProperty", { link = "Structure" })
hi(0, "CmpItemKindReference", { link = "Tag" })
hi(0, "CmpItemKindSnippet", { link = "Special" })
hi(0, "CmpItemKindStruct", { link = "Structure" })
hi(0, "CmpItemKindText", { link = "Normal" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindUnit", { link = "Special" })
hi(0, "CmpItemKindValue", { link = "Identifier" })
hi(0, "CmpItemKindVariable", { link = "Delimiter" })
hi(0, "CmpItemMenu", { fg = "#2e2e33" })
hi(0, "CocBold", { bold = true })
hi(0, "CocCodeLens", { link = "LspCodeLens" })
hi(0, "CocCursorTransparent", { blend = 100, strikethrough = true })
hi(0, "CocDisabled", { link = "Comment" })
hi(0, "CocInlayHint", { ctermfg = 29, fg = "#007c65" })
hi(0, "CocItalic", { italic = true })
hi(0, "CocLink", { sp = "#15aabf", underline = true })
hi(0, "CocListBgBlack", { bg = "#e2e2e9", ctermbg = 0 })
hi(0, "CocListBgBlue", { bg = "#00738b", ctermbg = 12 })
hi(0, "CocListBgCyan", { bg = "#007c65", ctermbg = 14 })
hi(0, "CocListBgGreen", { bg = "#426200", ctermbg = 10 })
hi(0, "CocListBgGrey", { bg = "#e2e2e9", ctermbg = 248 })
hi(0, "CocListBgMagenta", { bg = "#46006a", ctermbg = 13 })
hi(0, "CocListBgRed", { bg = "#6a003e", ctermbg = 9 })
hi(0, "CocListBgWhite", { bg = "#2e2e33", ctermbg = 15 })
hi(0, "CocListBgYellow", { bg = "#7e5c00", ctermbg = 11 })
hi(0, "CocListBlackBlack", { bg = "#e2e2e9", fg = "#e2e2e9" })
hi(0, "CocListBlackBlue", { bg = "#00738b", fg = "#e2e2e9" })
hi(0, "CocListBlackCyan", { bg = "#007c65", fg = "#e2e2e9" })
hi(0, "CocListBlackGreen", { bg = "#426200", fg = "#e2e2e9" })
hi(0, "CocListBlackGrey", { bg = "#e2e2e9", fg = "#e2e2e9" })
hi(0, "CocListBlackMagenta", { bg = "#46006a", fg = "#e2e2e9" })
hi(0, "CocListBlackRed", { bg = "#6a003e", fg = "#e2e2e9" })
hi(0, "CocListBlackWhite", { bg = "#2e2e33", fg = "#e2e2e9" })
hi(0, "CocListBlackYellow", { bg = "#7e5c00", fg = "#e2e2e9" })
hi(0, "CocListBlueBlack", { bg = "#e2e2e9", fg = "#00738b" })
hi(0, "CocListBlueBlue", { bg = "#00738b", fg = "#00738b" })
hi(0, "CocListBlueCyan", { bg = "#007c65", fg = "#00738b" })
hi(0, "CocListBlueGreen", { bg = "#426200", fg = "#00738b" })
hi(0, "CocListBlueGrey", { bg = "#e2e2e9", fg = "#00738b" })
hi(0, "CocListBlueMagenta", { bg = "#46006a", fg = "#00738b" })
hi(0, "CocListBlueRed", { bg = "#6a003e", fg = "#00738b" })
hi(0, "CocListBlueWhite", { bg = "#2e2e33", fg = "#00738b" })
hi(0, "CocListBlueYellow", { bg = "#7e5c00", fg = "#00738b" })
hi(0, "CocListCyanBlack", { bg = "#e2e2e9", fg = "#007c65" })
hi(0, "CocListCyanBlue", { bg = "#00738b", fg = "#007c65" })
hi(0, "CocListCyanCyan", { bg = "#007c65", fg = "#007c65" })
hi(0, "CocListCyanGreen", { bg = "#426200", fg = "#007c65" })
hi(0, "CocListCyanGrey", { bg = "#e2e2e9", fg = "#007c65" })
hi(0, "CocListCyanMagenta", { bg = "#46006a", fg = "#007c65" })
hi(0, "CocListCyanRed", { bg = "#6a003e", fg = "#007c65" })
hi(0, "CocListCyanWhite", { bg = "#2e2e33", fg = "#007c65" })
hi(0, "CocListCyanYellow", { bg = "#7e5c00", fg = "#007c65" })
hi(0, "CocListFgBlack", { ctermfg = 0, fg = "#e2e2e9" })
hi(0, "CocListFgBlue", { ctermfg = 12, fg = "#00738b" })
hi(0, "CocListFgCyan", { ctermfg = 14, fg = "#007c65" })
hi(0, "CocListFgGreen", { ctermfg = 10, fg = "#426200" })
hi(0, "CocListFgGrey", { ctermfg = 248, fg = "#e2e2e9" })
hi(0, "CocListFgMagenta", { ctermfg = 13, fg = "#46006a" })
hi(0, "CocListFgRed", { ctermfg = 9, fg = "#6a003e" })
hi(0, "CocListFgWhite", { ctermfg = 15, fg = "#2e2e33" })
hi(0, "CocListFgYellow", { ctermfg = 11, fg = "#7e5c00" })
hi(0, "CocListGreenBlack", { bg = "#e2e2e9", fg = "#426200" })
hi(0, "CocListGreenBlue", { bg = "#00738b", fg = "#426200" })
hi(0, "CocListGreenCyan", { bg = "#007c65", fg = "#426200" })
hi(0, "CocListGreenGreen", { bg = "#426200", fg = "#426200" })
hi(0, "CocListGreenGrey", { bg = "#e2e2e9", fg = "#426200" })
hi(0, "CocListGreenMagenta", { bg = "#46006a", fg = "#426200" })
hi(0, "CocListGreenRed", { bg = "#6a003e", fg = "#426200" })
hi(0, "CocListGreenWhite", { bg = "#2e2e33", fg = "#426200" })
hi(0, "CocListGreenYellow", { bg = "#7e5c00", fg = "#426200" })
hi(0, "CocListGreyBlack", { bg = "#e2e2e9", fg = "#e2e2e9" })
hi(0, "CocListGreyBlue", { bg = "#00738b", fg = "#e2e2e9" })
hi(0, "CocListGreyCyan", { bg = "#007c65", fg = "#e2e2e9" })
hi(0, "CocListGreyGreen", { bg = "#426200", fg = "#e2e2e9" })
hi(0, "CocListGreyGrey", { bg = "#e2e2e9", fg = "#e2e2e9" })
hi(0, "CocListGreyMagenta", { bg = "#46006a", fg = "#e2e2e9" })
hi(0, "CocListGreyRed", { bg = "#6a003e", fg = "#e2e2e9" })
hi(0, "CocListGreyWhite", { bg = "#2e2e33", fg = "#e2e2e9" })
hi(0, "CocListGreyYellow", { bg = "#7e5c00", fg = "#e2e2e9" })
hi(0, "CocListMagentaBlack", { bg = "#e2e2e9", fg = "#46006a" })
hi(0, "CocListMagentaBlue", { bg = "#00738b", fg = "#46006a" })
hi(0, "CocListMagentaCyan", { bg = "#007c65", fg = "#46006a" })
hi(0, "CocListMagentaGreen", { bg = "#426200", fg = "#46006a" })
hi(0, "CocListMagentaGrey", { bg = "#e2e2e9", fg = "#46006a" })
hi(0, "CocListMagentaMagenta", { bg = "#46006a", fg = "#46006a" })
hi(0, "CocListMagentaRed", { bg = "#6a003e", fg = "#46006a" })
hi(0, "CocListMagentaWhite", { bg = "#2e2e33", fg = "#46006a" })
hi(0, "CocListMagentaYellow", { bg = "#7e5c00", fg = "#46006a" })
hi(0, "CocListRedBlack", { bg = "#e2e2e9", fg = "#6a003e" })
hi(0, "CocListRedBlue", { bg = "#00738b", fg = "#6a003e" })
hi(0, "CocListRedCyan", { bg = "#007c65", fg = "#6a003e" })
hi(0, "CocListRedGreen", { bg = "#426200", fg = "#6a003e" })
hi(0, "CocListRedGrey", { bg = "#e2e2e9", fg = "#6a003e" })
hi(0, "CocListRedMagenta", { bg = "#46006a", fg = "#6a003e" })
hi(0, "CocListRedRed", { bg = "#6a003e", fg = "#6a003e" })
hi(0, "CocListRedWhite", { bg = "#2e2e33", fg = "#6a003e" })
hi(0, "CocListRedYellow", { bg = "#7e5c00", fg = "#6a003e" })
hi(0, "CocListWhiteBlack", { bg = "#e2e2e9", fg = "#2e2e33" })
hi(0, "CocListWhiteBlue", { bg = "#00738b", fg = "#2e2e33" })
hi(0, "CocListWhiteCyan", { bg = "#007c65", fg = "#2e2e33" })
hi(0, "CocListWhiteGreen", { bg = "#426200", fg = "#2e2e33" })
hi(0, "CocListWhiteGrey", { bg = "#e2e2e9", fg = "#2e2e33" })
hi(0, "CocListWhiteMagenta", { bg = "#46006a", fg = "#2e2e33" })
hi(0, "CocListWhiteRed", { bg = "#6a003e", fg = "#2e2e33" })
hi(0, "CocListWhiteWhite", { bg = "#2e2e33", fg = "#2e2e33" })
hi(0, "CocListWhiteYellow", { bg = "#7e5c00", fg = "#2e2e33" })
hi(0, "CocListYellowBlack", { bg = "#e2e2e9", fg = "#7e5c00" })
hi(0, "CocListYellowBlue", { bg = "#00738b", fg = "#7e5c00" })
hi(0, "CocListYellowCyan", { bg = "#007c65", fg = "#7e5c00" })
hi(0, "CocListYellowGreen", { bg = "#426200", fg = "#7e5c00" })
hi(0, "CocListYellowGrey", { bg = "#e2e2e9", fg = "#7e5c00" })
hi(0, "CocListYellowMagenta", { bg = "#46006a", fg = "#7e5c00" })
hi(0, "CocListYellowRed", { bg = "#6a003e", fg = "#7e5c00" })
hi(0, "CocListYellowWhite", { bg = "#2e2e33", fg = "#7e5c00" })
hi(0, "CocListYellowYellow", { bg = "#7e5c00", fg = "#7e5c00" })
hi(0, "CocMarkdownLink", { fg = "#001f7d" })
hi(0, "CocMenuSel", { bg = "#a2a2a8" })
hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
hi(0, "CocSearch", { fg = "#001f7d" })
hi(0, "CocSelectedText", { fg = "#7e5c00" })
hi(0, "CocStrikeThrough", { strikethrough = true })
hi(0, "CocSymbolArray", { ctermfg = 223, fg = "#00738b" })
hi(0, "CocSymbolBoolean", { ctermfg = 223, fg = "#46006a" })
hi(0, "CocSymbolClass", { ctermfg = 223, fg = "#007c65" })
hi(0, "CocSymbolColor", { ctermfg = 223, fg = "#46006a" })
hi(0, "CocSymbolConstant", { ctermfg = 223, fg = "#46006a" })
hi(0, "CocSymbolConstructor", { ctermfg = 223, fg = "#007c65" })
hi(0, "CocSymbolEnum", { ctermfg = 223, fg = "#2e2e33" })
hi(0, "CocSymbolEnumMember", { ctermfg = 223, fg = "#7e5c00" })
hi(0, "CocSymbolEvent", { ctermfg = 223, fg = "#46006a" })
hi(0, "CocSymbolField", { ctermfg = 223, fg = "#7e5c00" })
hi(0, "CocSymbolFile", { ctermfg = 223, fg = "#2e2e33" })
hi(0, "CocSymbolFolder", { ctermfg = 223, fg = "#00738b" })
hi(0, "CocSymbolFunction", { ctermfg = 223, fg = "#00738b" })
hi(0, "CocSymbolInterface", { ctermfg = 223, fg = "#2e2e33" })
hi(0, "CocSymbolKey", { ctermfg = 223, fg = "#7e5c00" })
hi(0, "CocSymbolKeyword", { ctermfg = 223, fg = "#2e2e33" })
hi(0, "CocSymbolMethod", { ctermfg = 223, fg = "#00738b" })
hi(0, "CocSymbolModule", { ctermfg = 223, fg = "#7e5c00" })
hi(0, "CocSymbolNamespace", { ctermfg = 223, fg = "#7e5c00" })
hi(0, "CocSymbolNull", { ctermfg = 223, fg = "#2e2e33" })
hi(0, "CocSymbolNumber", { ctermfg = 223, fg = "#46006a" })
hi(0, "CocSymbolObject", { ctermfg = 223, fg = "#00738b" })
hi(0, "CocSymbolOperator", { ctermfg = 223, fg = "#2e2e33" })
hi(0, "CocSymbolPackage", { ctermfg = 223, fg = "#2e2e33" })
hi(0, "CocSymbolProperty", { ctermfg = 223, fg = "#7e5c00" })
hi(0, "CocSymbolReference", { ctermfg = 223, fg = "#7e5c00" })
hi(0, "CocSymbolSnippet", { ctermfg = 223, fg = "#00738b" })
hi(0, "CocSymbolString", { ctermfg = 223, fg = "#426200" })
hi(0, "CocSymbolStruct", { ctermfg = 223, fg = "#2e2e33" })
hi(0, "CocSymbolText", { ctermfg = 223, fg = "#00738b" })
hi(0, "CocSymbolTypeParameter", { ctermfg = 223, fg = "#001f7d" })
hi(0, "CocSymbolUnit", { ctermfg = 223, fg = "#00738b" })
hi(0, "CocSymbolValue", { ctermfg = 223, fg = "#00738b" })
hi(0, "CocSymbolVariable", { ctermfg = 223, fg = "#007c65" })
hi(0, "CocUnderline", { sp = "#ebdbb2", underline = true })
hi(0, "CocVirtualText", { ctermfg = 12, fg = "#504945" })
hi(0, "ColorColumn", { bg = "#a2a2a8" })
hi(0, "Comment", { fg = "#66666c" })
hi(0, "Conceal", { fg = "#00738b" })
hi(0, "Constant", { fg = "#46006a" })
hi(0, "CurSearch", { bg = "#7e5c00", fg = "#e2e2e9" })
hi(0, "Cursor", { bg = "#2e2e33", fg = "#e2e2e9" })
hi(0, "CursorColumn", { bg = "#c2c2c9" })
hi(0, "CursorLine", { bg = "#c2c2c9" })
hi(0, "CursorLineFold", { fg = "#a2a2a8" })
hi(0, "CursorLineNr", { bold = true, fg = "#2f0d79" })
hi(0, "CursorLineSign", { fg = "#a2a2a8" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#426200" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { link = "Title" })
hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
hi(0, "DapUILineNumber", { link = "Title" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#772200" })
hi(0, "DapUIScope", { link = "Title" })
hi(0, "DapUISource", { link = "Directory" })
hi(0, "DapUIStoppedThread", { link = "Title" })
hi(0, "DapUIThread", { link = "String" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
hi(0, "DapUIWatchesValue", { link = "String" })
hi(0, "DashboardCenter", { link = "Delimiter" })
hi(0, "DashboardFooter", { link = "Comment" })
hi(0, "DashboardHeader", { link = "Title" })
hi(0, "DashboardShortCut", { link = "WarningMsg" })
hi(0, "Definitions", { fg = "#426200" })
hi(0, "DefinitionsIcon", { fg = "#00738b" })
hi(0, "Delimiter", { fg = "#772200" })
hi(0, "DiagnosticDeprecated", { sp = "#6a003e", strikethrough = true })
hi(0, "DiagnosticError", { fg = "#6a003e" })
hi(0, "DiagnosticFloatingError", { bg = "#ebebf2", fg = "#6a003e" })
hi(0, "DiagnosticFloatingHint", { bg = "#ebebf2", fg = "#007c65" })
hi(0, "DiagnosticFloatingInfo", { bg = "#ebebf2", fg = "#001f7d" })
hi(0, "DiagnosticFloatingOk", { bg = "#ebebf2", fg = "#426200" })
hi(0, "DiagnosticFloatingWarn", { bg = "#ebebf2", fg = "#7e5c00" })
hi(0, "DiagnosticHint", { fg = "#007c65" })
hi(0, "DiagnosticInfo", { fg = "#001f7d" })
hi(0, "DiagnosticOk", { fg = "#426200" })
hi(0, "DiagnosticUnderlineError", { sp = "#6a003e", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#007c65", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#001f7d", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#426200", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#7e5c00", underline = true })
hi(0, "DiagnosticWarn", { fg = "#7e5c00" })
hi(0, "DiffAdd", { bg = "#c3f77e" })
hi(0, "DiffChange", { bg = "#ffd580" })
hi(0, "DiffDelete", { bg = "#ffacd3" })
hi(0, "DiffText", { bg = "#a2a2a8" })
hi(0, "Directory", { fg = "#00738b" })
hi(0, "EndOfBuffer", { fg = "#a2a2a8" })
hi(0, "Error", { bg = "#ffacd3" })
hi(0, "ErrorMsg", { fg = "#6a003e" })
hi(0, "FinderParam", { fg = "#7e5c00" })
hi(0, "FinderSpinner", { fg = "#426200" })
hi(0, "FinderSpinnerBorder", { fg = "#2f0d79" })
hi(0, "FinderSpinnerTitle", { link = "Title" })
hi(0, "FinderVirtText", { fg = "#772200" })
hi(0, "Float", { link = "Constant" })
hi(0, "FloatBorder", { bg = "#ebebf2", fg = "#2f0d79" })
hi(0, "FloatTitle", { bg = "#ebebf2", bold = true, fg = "#2f0d79" })
hi(0, "FoldColumn", { fg = "#a2a2a8" })
hi(0, "Folded", { bg = "#c2c2c9", fg = "#66666c" })
hi(0, "Function", { fg = "#00738b" })
hi(0, "GitSignsAdd", { fg = "#426200" })
hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
hi(0, "GitSignsChange", { fg = "#7e5c00" })
hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
hi(0, "GitSignsDelete", { fg = "#6a003e" })
hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
hi(0, "GitSignsUntracked", { fg = "#00738b" })
hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
hi(0, "HopNextKey", { bold = true, fg = "#426200", nocombine = true })
hi(0, "HopNextKey1", { bold = true, fg = "#772200", nocombine = true })
hi(0, "HopNextKey2", { bold = true, fg = "#49494f", nocombine = true })
hi(0, "HopPreview", { bold = true, fg = "#7e5c00", nocombine = true })
hi(0, "HopUnmatched", { fg = "#a2a2a8" })
hi(0, "HydraAmaranth", { fg = "#46006a" })
hi(0, "HydraBlue", { fg = "#00738b" })
hi(0, "HydraHint", { link = "NormalFloat" })
hi(0, "HydraPink", { fg = "#772200" })
hi(0, "HydraRed", { fg = "#6a003e" })
hi(0, "HydraTeal", { fg = "#007c65" })
hi(0, "Identifier", { fg = "#7e5c00" })
hi(0, "Ignore", {})
hi(0, "IncSearch", { bg = "#7e5c00", fg = "#e2e2e9" })
hi(0, "IndentBlanklineChar", { fg = "#a2a2a8", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#2f0d79", nocombine = true })
hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#2f0d79", underline = true })
hi(0, "IndentBlanklineIndent1", { fg = "#001f7d", nocombine = true })
hi(0, "IndentBlanklineIndent2", { fg = "#007c65", nocombine = true })
hi(0, "IndentBlanklineIndent3", { fg = "#7e5c00", nocombine = true })
hi(0, "IndentBlanklineIndent4", { fg = "#6a003e", nocombine = true })
hi(0, "IndentBlanklineIndent5", { fg = "#00738b", nocombine = true })
hi(0, "IndentBlanklineIndent6", { fg = "#426200", nocombine = true })
hi(0, "IndentBlanklineIndent7", { fg = "#772200", nocombine = true })
hi(0, "IndentBlanklineIndent8", { fg = "#46006a", nocombine = true })
hi(0, "Italic", { italic = true })
hi(0, "LSOutlinePreviewBorder", { fg = "#2f0d79" })
hi(0, "LazyButton", { bg = "#c2c2c9" })
hi(0, "LazyButtonActive", { bg = "#a2a2a8" })
hi(0, "LazyDimmed", { link = "Comment" })
hi(0, "LazyH1", { bg = "#a2a2a8", bold = true, fg = "#2f0d79" })
hi(0, "LeapBackdrop", { link = "Comment" })
hi(0, "LeapLabelPrimary", { bold = true, fg = "#7e5c00", nocombine = true })
hi(0, "LeapLabelSecondary", { bold = true, fg = "#2e2e33", nocombine = true })
hi(0, "LeapLabelSelected", { bold = true, fg = "#007c65", nocombine = true })
hi(0, "LeapMatch", { bold = true, fg = "#426200", nocombine = true, underline = true })
hi(0, "LineNr", { fg = "#a2a2a8" })
hi(0, "LspCodeLens", { link = "Comment" })
hi(0, "LspCodeLensSeparator", { link = "Comment" })
hi(0, "LspReferenceRead", { link = "LspReferenceText" })
hi(0, "LspReferenceText", { bg = "#a2a2a8" })
hi(0, "LspReferenceWrite", { link = "LspReferenceText" })
hi(0, "LspSagaAutoPreview", { fg = "#001f7d" })
hi(0, "LspSagaBorderTitle", { link = "FloatTitle" })
hi(0, "LspSagaCodeActionBorder", { fg = "#2f0d79" })
hi(0, "LspSagaCodeActionContent", { fg = "#2e2e33" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#00738b" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#2f0d79" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#2f0d79" })
hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
hi(0, "LspSagaDiagnosticSource", { fg = "#772200" })
hi(0, "LspSagaFinderSelection", { fg = "#007c65" })
hi(0, "LspSagaHoverBorder", { fg = "#2f0d79" })
hi(0, "LspSagaLspFinderBorder", { fg = "#2f0d79" })
hi(0, "LspSagaRenameBorder", { fg = "#2f0d79" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#2f0d79" })
hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
hi(0, "MasonError", { fg = "#6a003e" })
hi(0, "MasonHeader", { bg = "#00738b", bold = true, fg = "#e2e2e9" })
hi(0, "MasonHeaderSecondary", { bg = "#001f7d", bold = true, fg = "#e2e2e9" })
hi(0, "MasonHeading", { link = "Bold" })
hi(0, "MasonHighlight", { fg = "#2f0d79" })
hi(0, "MasonHighlightBlock", { bg = "#2f0d79", fg = "#e2e2e9" })
hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
hi(0, "MasonHighlightBlockSecondary", { bg = "#00738b", fg = "#e2e2e9" })
hi(0, "MasonHighlightSecondary", { fg = "#00738b" })
hi(0, "MasonLink", { link = "MasonHighlight" })
hi(0, "MasonMuted", { link = "Comment" })
hi(0, "MasonMutedBlock", { bg = "#a2a2a8", fg = "#e2e2e9" })
hi(0, "MasonMutedBlockBold", { bg = "#a2a2a8", bold = true, fg = "#e2e2e9" })
hi(0, "MatchParen", { bg = "#a2a2a8", bold = true })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { link = "FloatTitle" })
hi(0, "MiniCompletionActiveParameter", { bg = "#a2a2a8" })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { link = "DiffDelete" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
hi(0, "MiniFilesBorder", { link = "FloatBorder" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { fg = "#2e2e33" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { link = "FloatTitle" })
hi(0, "MiniFilesTitleFocused", { bg = "#ebebf2", bold = true, fg = "#2e2e33" })
hi(0, "MiniHipatternsFixme", { bg = "#6a003e", bold = true, fg = "#e2e2e9" })
hi(0, "MiniHipatternsHack", { bg = "#7e5c00", bold = true, fg = "#e2e2e9" })
hi(0, "MiniHipatternsNote", { bg = "#007c65", bold = true, fg = "#e2e2e9" })
hi(0, "MiniHipatternsTodo", { bg = "#001f7d", bold = true, fg = "#e2e2e9" })
hi(0, "MiniIndentscopeSymbol", { fg = "#2f0d79" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#6a003e" })
hi(0, "MiniJump", { sp = "#2f0d79", undercurl = true })
hi(0, "MiniJump2dDim", { fg = "#a2a2a8" })
hi(0, "MiniJump2dSpot", { bg = "#f5f5fc", bold = true, fg = "#0d0d11", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#f5f5fc", fg = "#1e1e23", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
hi(0, "MiniMapNormal", { bg = "#ebebf2", fg = "#66666c" })
hi(0, "MiniMapSymbolCount", { fg = "#66666c" })
hi(0, "MiniMapSymbolLine", { fg = "#2f0d79" })
hi(0, "MiniMapSymbolView", { fg = "#2f0d79" })
hi(0, "MiniNotifyBorder", { link = "FloatBorder" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "FloatBorder" })
hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniPickBorderText", { link = "FloatTitle" })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
hi(0, "MiniPickMatchMarked", { link = "Visual" })
hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniStarterCurrent", { link = "MiniStarterItem" })
hi(0, "MiniStarterFooter", { link = "Comment" })
hi(0, "MiniStarterHeader", { bold = true, fg = "#2f0d79" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItemBullet", { fg = "#66666c" })
hi(0, "MiniStarterItemPrefix", { bold = true, fg = "#7e5c00" })
hi(0, "MiniStarterQuery", { bold = true, fg = "#426200" })
hi(0, "MiniStarterSection", { fg = "#46006a" })
hi(0, "MiniStatuslineDevinfo", { bg = "#c2c2c9", fg = "#49494f" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { bg = "#e2e2e9", fg = "#49494f" })
hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
hi(0, "MiniStatuslineModeCommand", { bg = "#7e5c00", bold = true, fg = "#e2e2e9" })
hi(0, "MiniStatuslineModeInsert", { bg = "#00738b", bold = true, fg = "#e2e2e9" })
hi(0, "MiniStatuslineModeNormal", { bg = "#2e2e33", bold = true, fg = "#e2e2e9" })
hi(0, "MiniStatuslineModeOther", { bg = "#007c65", bold = true, fg = "#e2e2e9" })
hi(0, "MiniStatuslineModeReplace", { bg = "#6a003e", bold = true, fg = "#e2e2e9" })
hi(0, "MiniStatuslineModeVisual", { bg = "#426200", bold = true, fg = "#e2e2e9" })
hi(0, "MiniSurround", { link = "IncSearch" })
hi(0, "MiniTablineCurrent", { bg = "#e2e2e9", bold = true, fg = "#2f0d79" })
hi(0, "MiniTablineFill", { link = "MiniTablineHidden" })
hi(0, "MiniTablineHidden", { bg = "#ebebf2", fg = "#49494f" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#2f0d79", bold = true, fg = "#e2e2e9" })
hi(0, "MiniTablineModifiedHidden", { bg = "#49494f", fg = "#ebebf2" })
hi(0, "MiniTablineModifiedVisible", { bg = "#49494f", bold = true, fg = "#ebebf2" })
hi(0, "MiniTablineTabpagesection", { bg = "#426200", bold = true, fg = "#e2e2e9" })
hi(0, "MiniTablineVisible", { bg = "#ebebf2", bold = true, fg = "#49494f" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#6a003e" })
hi(0, "MiniTestPass", { bold = true, fg = "#426200" })
hi(0, "MiniTrailspace", { bg = "#ffacd3" })
hi(0, "ModeMsg", { fg = "#426200" })
hi(0, "MoreMsg", { fg = "#00738b" })
hi(0, "MsgArea", { link = "Normal" })
hi(0, "MsgSeparator", { bg = "#a2a2a8", fg = "#66666c" })
hi(0, "NeoTreeDimText", { fg = "#a2a2a8" })
hi(0, "NeoTreeDotfile", { fg = "#49494f" })
hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
hi(0, "NeoTreeFadeText2", { fg = "#a2a2a8" })
hi(0, "NeoTreeGitAdded", { fg = "#426200" })
hi(0, "NeoTreeGitConflict", { bold = true, fg = "#772200" })
hi(0, "NeoTreeGitDeleted", { fg = "#6a003e" })
hi(0, "NeoTreeGitModified", { fg = "#7e5c00" })
hi(0, "NeoTreeGitUnstaged", { fg = "#46006a" })
hi(0, "NeoTreeGitUntracked", { fg = "#007c65" })
hi(0, "NeoTreeMessage", { bg = "#c2c2c9", fg = "#2e2e33" })
hi(0, "NeoTreeModified", { fg = "#1e1e23" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#2f0d79" })
hi(0, "NeoTreeTabInactive", { fg = "#66666c" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#a2a2a8", fg = "#66666c" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#c2c2c9", fg = "#c2c2c9" })
hi(0, "NeogitCommitViewHeader", { link = "Special" })
hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitFold", { link = "FoldColumn" })
hi(0, "NeogitHunkHeader", { fg = "#2f0d79" })
hi(0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#2f0d79" })
hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
hi(0, "NoiceCmdlinePopupBorder", { fg = "#00738b" })
hi(0, "NoiceConfirmBorder", { fg = "#7e5c00" })
hi(0, "NonText", { fg = "#a2a2a8" })
hi(0, "Normal", { bg = "#e2e2e9", fg = "#2e2e33" })
hi(0, "NormalFloat", { bg = "#ebebf2", fg = "#2e2e33" })
hi(0, "NormalNC", { link = "Normal" })
hi(0, "NotifyDEBUGBorder", { fg = "#426200" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyERRORBorder", { fg = "#6a003e" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
hi(0, "NotifyINFOBorder", { fg = "#001f7d" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
hi(0, "NotifyTRACEBorder", { fg = "#007c65" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
hi(0, "NotifyWARNBorder", { fg = "#7e5c00" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#426200" })
hi(0, "NvimTreeFolderIcon", { fg = "#66666c" })
hi(0, "NvimTreeGitDeleted", { fg = "#6a003e" })
hi(0, "NvimTreeGitDirty", { fg = "#7e5c00" })
hi(0, "NvimTreeGitMerge", { fg = "#772200" })
hi(0, "NvimTreeGitNew", { fg = "#007c65" })
hi(0, "NvimTreeGitRenamed", { fg = "#46006a" })
hi(0, "NvimTreeGitStaged", { fg = "#426200" })
hi(0, "NvimTreeImageFile", { fg = "#772200" })
hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#2f0d79" })
hi(0, "NvimTreeSpecialFile", { fg = "#2f0d79", underline = true })
hi(0, "NvimTreeSymlink", { bold = true, fg = "#001f7d" })
hi(0, "NvimTreeWindowPicker", { bg = "#a2a2a8", bold = true, fg = "#2e2e33" })
hi(0, "Operator", { fg = "#2e2e33" })
hi(0, "OutlineDetail", { fg = "#a2a2a8" })
hi(0, "OutlineFoldPrefix", { fg = "#7e5c00" })
hi(0, "OutlineIndentEvn", { fg = "#66666c" })
hi(0, "OutlineIndentOdd", { fg = "#2e2e33" })
hi(0, "Pmenu", { bg = "#c2c2c9", fg = "#2e2e33" })
hi(0, "PmenuSel", { bg = "#2e2e33", blend = 0, fg = "#e2e2e9" })
hi(0, "PmenuThumb", { bg = "#a2a2a8" })
hi(0, "PounceAccept", { bg = "#7e5c00", bold = true, fg = "#e2e2e9", nocombine = true })
hi(0, "PounceAcceptBest", { bg = "#426200", bold = true, fg = "#e2e2e9", nocombine = true })
hi(0, "PounceGap", { bg = "#a2a2a8", bold = true, fg = "#e2e2e9", nocombine = true })
hi(0, "PounceMatch", { bg = "#2e2e33", bold = true, fg = "#e2e2e9", nocombine = true })
hi(0, "PreProc", { fg = "#001f7d" })
hi(0, "Question", { fg = "#00738b" })
hi(0, "QuickFixLine", { bg = "#c2c2c9" })
hi(0, "RainbowDelimiterBlue", { fg = "#00738b" })
hi(0, "RainbowDelimiterCyan", { fg = "#007c65" })
hi(0, "RainbowDelimiterGreen", { fg = "#426200" })
hi(0, "RainbowDelimiterOrange", { fg = "#772200" })
hi(0, "RainbowDelimiterRed", { fg = "#6a003e" })
hi(0, "RainbowDelimiterViolet", { fg = "#46006a" })
hi(0, "RainbowDelimiterYellow", { fg = "#7e5c00" })
hi(0, "References", { fg = "#426200" })
hi(0, "ReferencesIcon", { fg = "#00738b" })
hi(0, "Removed", { fg = "#6a003e" })
hi(0, "Search", { bg = "#2f0d79", fg = "#e2e2e9" })
hi(0, "SignColumn", { fg = "#a2a2a8" })
hi(0, "Sneak", { bg = "#772200", fg = "#e2e2e9" })
hi(0, "SneakLabel", { bg = "#772200", bold = true, fg = "#e2e2e9" })
hi(0, "SneakScope", { bg = "#0d0d11", fg = "#e2e2e9" })
hi(0, "Special", { fg = "#007c65" })
hi(0, "SpecialKey", { fg = "#a2a2a8" })
hi(0, "SpellBad", { sp = "#6a003e", undercurl = true })
hi(0, "SpellCap", { sp = "#007c65", undercurl = true })
hi(0, "SpellLocal", { sp = "#7e5c00", undercurl = true })
hi(0, "SpellRare", { sp = "#001f7d", undercurl = true })
hi(0, "Statement", { bold = true, fg = "#2e2e33" })
hi(0, "StatusLine", { bg = "#e2e2e9", fg = "#49494f" })
hi(0, "StatusLineNC", { bg = "#ebebf2", fg = "#49494f" })
hi(0, "String", { fg = "#426200" })
hi(0, "Substitute", { bg = "#001f7d", fg = "#e2e2e9" })
hi(0, "TabLine", { bg = "#ebebf2", fg = "#49494f" })
hi(0, "TabLineSel", { bg = "#ebebf2", fg = "#2f0d79" })
hi(0, "TargetFileName", { fg = "#2e2e33" })
hi(0, "TelescopeBorder", { fg = "#2f0d79" })
hi(0, "TelescopeMatching", { bold = true })
hi(0, "TelescopeMultiSelection", { bg = "#a2a2a8" })
hi(0, "TelescopeSelection", { bg = "#c2c2c9" })
hi(0, "TermCursorNC", { reverse = true })
hi(0, "Title", { fg = "#2f0d79" })
hi(0, "Todo", { bg = "#e2e2e9", bold = true, fg = "#2f0d79" })
hi(0, "TroubleCount", { bold = true, fg = "#2f0d79" })
hi(0, "TroubleFoldIcon", { bold = true, fg = "#2f0d79" })
hi(0, "TroubleIndent", { fg = "#a2a2a8" })
hi(0, "TroubleLocation", { fg = "#49494f" })
hi(0, "TroubleSignError", { link = "DiagnosticError" })
hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
hi(0, "TroubleText", { fg = "#2e2e33" })
hi(0, "TroubleTextError", { link = "TroubleText" })
hi(0, "TroubleTextHint", { link = "TroubleText" })
hi(0, "TroubleTextInformation", { link = "TroubleText" })
hi(0, "TroubleTextWarning", { link = "TroubleText" })
hi(0, "Type", { fg = "#2e2e33" })
hi(0, "UfoFoldedBg", { bg = "#c2c2c9" })
hi(0, "UfoFoldedFg", { fg = "#2e2e33" })
hi(0, "VertSplit", { fg = "#2f0d79" })
hi(0, "Visual", { bg = "#a2a2a8" })
hi(0, "VisualNOS", { bg = "#c2c2c9" })
hi(0, "WarningMsg", { fg = "#7e5c00" })
hi(0, "WhichKey", { fg = "#007c65" })
hi(0, "WhichKeyBorder", { link = "FloatBorder" })
hi(0, "WhichKeyDesc", { fg = "#2e2e33" })
hi(0, "WhichKeyFloat", { bg = "#ebebf2", fg = "#2e2e33" })
hi(0, "WhichKeyGroup", { fg = "#6a003e" })
hi(0, "WhichKeySeparator", { fg = "#426200" })
hi(0, "WhichKeyValue", { link = "Comment" })
hi(0, "Whitespace", { fg = "#a2a2a8" })
hi(0, "WinBar", { link = "StatusLine" })
hi(0, "WinBarNC", { link = "StatusLineNC" })
hi(0, "WinSeparator", { fg = "#2f0d79" })
hi(0, "diffAdded", { fg = "#426200" })
hi(0, "diffChanged", { fg = "#007c65" })
hi(0, "diffFile", { fg = "#7e5c00" })
hi(0, "diffLine", { fg = "#001f7d" })
hi(0, "diffRemoved", { fg = "#6a003e" })
hi(0, "gitcommitBranch", { bold = true, fg = "#772200" })
hi(0, "gitcommitComment", { link = "Comment" })
hi(0, "gitcommitDiscarded", { link = "Comment" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#7e5c00" })
hi(0, "gitcommitDiscardedType", { fg = "#00738b" })
hi(0, "gitcommitHeader", { link = "Title" })
hi(0, "gitcommitOverflow", { fg = "#7e5c00" })
hi(0, "gitcommitSelected", { link = "Comment" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#426200" })
hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitSummary", { fg = "#426200" })
hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitUntracked", { link = "Comment" })
hi(0, "gitcommitUntrackedFile", { fg = "#007c65" })
hi(0, "lCursor", { bg = "#2e2e33", fg = "#e2e2e9" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#e2e2e9"
g.terminal_color_1 = "#6a003e"
g.terminal_color_2 = "#426200"
g.terminal_color_3 = "#7e5c00"
g.terminal_color_4 = "#00738b"
g.terminal_color_5 = "#46006a"
g.terminal_color_6 = "#007c65"
g.terminal_color_7 = "#2e2e33"
g.terminal_color_8 = "#e2e2e9"
g.terminal_color_9 = "#6a003e"
g.terminal_color_10 = "#426200"
g.terminal_color_11 = "#7e5c00"
g.terminal_color_12 = "#00738b"
g.terminal_color_13 = "#46006a"
g.terminal_color_14 = "#007c65"
g.terminal_color_15 = "#2e2e33"
