alias chgrp='chgrp --preserve-root'
alias chmod='chmod --preserve-root'
alias chown='chown --preserve-root'
alias cp='cp -iv'
alias df='df -h'
alias du='du -h'
alias free='free -h'
alias mkdir='mkdir -pv'
alias mv='mv -iv'
alias rm='rm -iv'
alias tree='tree --filesfirst -a -I ".git"'
alias clear "printf '\033[2J\033[3J\033[1;1H'"
