"      .-.      _______                             .  '  *   .  . '
"     {}``; |==|_______D                                  . *  -+-  .
"     / ('        /|\                                 . '   * .    '  *
" (  /  |        / | \                                    * .  ' .  .-+-
"  \(_)_%s      /  |  \                                *   *  .   .
"
" This configuration is shared among Vim and Vim emulation layers.
"
" {{{ z-o to expand.

" NOTE: when |vimrc| or |gvimrc| file exists, Vim will use Vim defaults; but this doesn't
" apply with system-wide vimrc or gvimrc file, nor for file given with the |-u| argument.
"
if &compatible
  set nocompatible
endif

" {{{ Modern Terminal Features. z-o to expand.

" Sadly, vim has very poor out-of-the-box detection for modern terminal
" features. Furthermore, it recently broke detection even more. It kind of,
" but not really, supports terminfo, except it overrides it with its own
" hard-coded values when it feels like it. Worst of all, it has no ability to
" detect modern features not present in terminfo, at all, even security
" sensitive ones like bracketed paste.
"
" Thankfully, probably as a consequence of this lack of detection, vim allows
" users to configure these low level details.

set mouse=a
set ttymouse=sgr
set balloonevalterm

" Styled and colored underline support
"
let &t_AU = "\e[58:5:%dm"
let &t_8u = "\e[58:2:%lu:%lu:%lum"
let &t_Us = "\e[4:2m"
let &t_Cs = "\e[4:3m"
let &t_ds = "\e[4:4m"
let &t_Ds = "\e[4:5m"
let &t_Ce = "\e[4:0m"

" Strikethrough
"
let &t_Ts = "\e[9m"
let &t_Te = "\e[29m"

" Truecolor support
"
let &t_8f = "\e[38:2:%lu:%lu:%lum"
let &t_8b = "\e[48:2:%lu:%lu:%lum"
let &t_RF = "\e]10;?\e\\"
let &t_RB = "\e]11;?\e\\"

" Bracketed paste
"
let &t_BE = "\e[?2004h"
let &t_BD = "\e[?2004l"
let &t_PS = "\e[200~"
let &t_PE = "\e[201~"

" Cursor control
"
let &t_RC = "\e[?12$p"
let &t_SH = "\e[%d q"
let &t_RS = "\eP$q q\e\\"
let &t_SI = "\e[5 q"
let &t_SR = "\e[3 q"
let &t_EI = "\e[1 q"
let &t_VS = "\e[?12l"

" Focus tracking
"
let &t_fe = "\e[?1004h"
let &t_fd = "\e[?1004l"
execute "set <FocusGained>=\<Esc>[I"
execute "set <FocusLost>=\<Esc>[O"

" Window title
"
let &t_ST = "\e[22;2t"
let &t_RT = "\e[23;2t"

" vim hardcodes background color erase even if the terminfo file does
" not contain bce. This causes incorrect background rendering when
" using a color theme with a background color in terminals such as
" kitty that do not support background color erase.
"
let &t_ut=''

" Wayland clipboard
" https://github.com/vim/vim/issues/5157
"
if exists('$WAYLAND_DISPLAY') && executable('wl-copy') && executable('wl-paste')
  autocmd TextYankPost * 
    \ if (v:event.operator == 'y' || v:event.operator == 'd') | 
    \ silent! execute 'call system("wl-copy", @")' | 
\ endif
  nnoremap p :let @"=substitute(system("wl-paste --no-newline"), '<C-v><C-m>', '', 'g')<cr>p
endif
set clipboard+=unnamedplus

" }}}

" {{{ Setting options. z-o to expand.

colorscheme habamax

set whichwrap+=b,s,<,>,h,l
set signcolumn=yes
set virtualedit=block
set titlestring=%t
set splitkeep=screen
set number
set relativenumber
set nowrap
set title
set confirm
set splitbelow
set splitright
set termguicolors
set undofile
set expandtab
set breakindent
set smartindent
set preserveindent
set cursorline
set gdefault
set tabstop=2
set shiftwidth=0
set scrolloff=4
set pumheight=8
set list
set fillchars=diff:░,fold:\ ,vert:│
set listchars=nbsp:·,tab:▸\ ,trail:·
set suffixes-=.h
set cinkeys-=:
set indentkeys-=:
set shortmess+=sI

" }}}
" }}}
" vim:fileencoding=utf-8:foldmethod=marker
