# Stylua uses the top-level configuration file, as determined by git rev-parse
# --show-toplevel, instead of the closest configuration to the file.
#
# https://github.com/JohnnyMorganz/StyLua/issues/831

column_width = 120
indent_width = 2
indent_type = "Spaces"
call_parentheses = "None"
collapse_simple_statement = "Always"
