#!/usr/bin/env bash

v=`gsettings get org.gnome.desktop.interface color-scheme`
d="dark"
l="light"

# Valid values are “default”, “prefer-dark”, “prefer-light”.
#
case $v in
  *default* )
    kitty +kitten themes --reload-in=all $l 2>/dev/null
    ;;
  *prefer-dark* )
    kitty +kitten themes --reload-in=all $d 2>/dev/null
    ;;
  *prefer-light* )
    kitty +kitten themes --reload-in=all $l 2>/dev/null
    ;;
esac



