;;; custom.el --- -*- lexical-binding: t -*-

;;; Commentary:
;;
;; This file is automatically generated and managed by Emacs.
;;
;; Customization variables recorded here are configured through the
;; Customize interface (`M-x customize`). Manual edits are discouraged,
;; as changes may be overwritten automatically.

;;; Code:

(custom-set-variables
  '(indent-tabs-mode nil)
  '(kill-do-not-save-duplicates t)
  '(mouse-yank-at-point t)
  '(standard-indent 2)
  '(xterm-mouse-mode t)
  '(savehist-mode t)
  '(recentf-mode t)
  '(winner-mode t)
  '(editorconfig-mode t)
  '(dired-auto-revert-buffer t)
  '(delete-selection-mode t)
  '(scroll-conservatively 101)
  '(scroll-margin 4)
  '(mouse-wheel-progressive-speed nil)
  '(mouse-wheel-scroll-amount '(3 ((shift) . 5) ((control) . nil)))
  '(auto-save-default nil)
  '(create-lockfiles nil)
  '(make-backup-files nil)
  '(auto-hscroll-mode nil)
  '(auto-mode-case-fold nil)
  '(bidi-display-reordering 'left-to-right)
  '(bidi-paragraph-direction 'left-to-right)
  '(bidi-inhibit-bpa t)
  '(fast-but-imprecise-scrolling t)
  '(inhibit-compacting-font-caches t)
  '(read-process-output-max (* 64 1024))
  '(redisplay-skip-fontification-on-input t)
  '(set-language-environment "UTF-8")
  '(default-input-method nil)
  '(visible-bell nil)
  '(ring-bell-function #'ignore))

(when (boundp 'pgtk-wait-for-event-timeout)
  (setq pgtk-wait-for-event-timeout 0.001))

(global-set-key [wheel-left] 'ignore)
(global-set-key [double-wheel-left] 'ignore)
(global-set-key [triple-wheel-left] 'ignore)
(global-set-key [wheel-right] 'ignore)
(global-set-key [double-wheel-right] 'ignore)
(global-set-key [triple-wheel-right] 'ignore)
