---@type LazyPluginSpec
return {
  [[echasnovski/mini.pick]],

  keys = {
    { [[<leader>pvp]],  function() require [[mini.extra]].pickers.visit_labels() end,                        desc = [[Labels]] },
    { [[<leader>pvl]],  function() require [[mini.extra]].pickers.visit_paths() end,                         desc = [[Paths]] },
    { [[<leader>pc]],   function() require [[mini.pick]].builtin.cli() end,                                  desc = [[CLI]] },
    { [[<leader>pld]],  function() require [[mini.extra]].pickers.lsp({ scope = [[declaration]] }) end,      desc = [[Declaration]] },
    { [[<leader>plD]],  function() require [[mini.extra]].pickers.lsp({ scope = [[definition]] }) end,       desc = [[Definition]] },
    { [[<leader>pli]],  function() require [[mini.extra]].pickers.lsp({ scope = [[implementation]] }) end,   desc = [[Implementation]] },
    { [[<leader>plr]],  function() require [[mini.extra]].pickers.lsp({ scope = [[references]] }) end,       desc = [[References]] },
    { [[<leader>plt]],  function() require [[mini.extra]].pickers.lsp({ scope = [[type_definition]] }) end,  desc = [[Type definition]] },
    { [[<leader>plsw]], function() require [[mini.extra]].pickers.lsp({ scope = [[workspace_symbol]] }) end, desc = [[Workspace]] },
    { [[<leader>plsd]], function() require [[mini.extra]].pickers.lsp({ scope = [[document_symbol]] }) end,  desc = [[Document]] },
    { [[<leader>pgg]],  function() require [[mini.pick]].builtin.grep() end,                                 desc = [[Grep]] },
    { [[<leader>pLq]],  function() require [[mini.extra]].pickers.list({ scope = [[quickfix]] }) end,        desc = [[Quickfix]] },
    { [[<leader>pLl]],  function() require [[mini.extra]].pickers.list({ scope = [[location-list]] }) end,   desc = [[Location]] },
    { [[<leader>pLj]],  function() require [[mini.extra]].pickers.list({ scope = [[jumplist]] }) end,        desc = [[Jump]] },
    { [[<leader>pLc]],  function() require [[mini.extra]].pickers.list({ scope = [[changelist]] }) end,      desc = [[Change]] },
    { [[<leader>pf]],   function() require [[mini.pick]].builtin.files() end,                                desc = [[Files]] },
    { [[<leader>pma]],  function() require [[mini.extra]].pickers.marks({ scope = [[all]] }) end,            desc = [[All]] },
    { [[<leader>pmg]],  function() require [[mini.extra]].pickers.marks({ scope = [[global]] }) end,         desc = [[Global]] },
    { [[<leader>pmb]],  function() require [[mini.extra]].pickers.marks({ scope = [[buf]] }) end,            desc = [[Buf]] },
    { [[<leader>pr]],   function() require [[mini.pick]].builtin.resume() end,                               desc = [[Resume]] },
    { [[<leader>pb]],   function() require [[mini.pick]].builtin.buffers() end,                              desc = [[Buffers]] },
    { [[<leader>ph/]],  function() require [[mini.extra]].pickers.history({ scope = [[/]] }) end,            desc = [[/]] },
    { [[<leader>ph:]],  function() require [[mini.extra]].pickers.history({ scope = [[:]] }) end,            desc = [[:]] },
    { [[<leader>ph=]],  function() require [[mini.extra]].pickers.history({ scope = [[=]] }) end,            desc = [[=]] },
    { [[<leader>ph>]],  function() require [[mini.extra]].pickers.history({ scope = [[>]] }) end,            desc = [[>]] },
    { [[<leader>ph?]],  function() require [[mini.extra]].pickers.history({ scope = [[?]] }) end,            desc = [[?]] },
    { [[<leader>ph@]],  function() require [[mini.extra]].pickers.history({ scope = [[@]] }) end,            desc = [[@]] },
    { [[<leader>pha]],  function() require [[mini.extra]].pickers.history({ scope = [[all]] }) end,          desc = [[All]] },
    { [[<leader>phc]],  function() require [[mini.extra]].pickers.history({ scope = [[cmd]] }) end,          desc = [[Cmd]] },
    { [[<leader>phe]],  function() require [[mini.extra]].pickers.history({ scope = [[expr]] }) end,         desc = [[Expr]] },
    { [[<leader>phd]],  function() require [[mini.extra]].pickers.history({ scope = [[debug]] }) end,        desc = [[Debug]] },
    { [[<leader>phi]],  function() require [[mini.extra]].pickers.history({ scope = [[input]] }) end,        desc = [[Input]] },
    { [[<leader>phs]],  function() require [[mini.extra]].pickers.history({ scope = [[search]] }) end,       desc = [[Search]] },
    { [[<leader>poa]],  function() require [[mini.extra]].pickers.options({ scope = [[all]] }) end,          desc = [[All]] },
    { [[<leader>pog]],  function() require [[mini.extra]].pickers.options({ scope = [[global]] }) end,       desc = [[Global]] },
    { [[<leader>pow]],  function() require [[mini.extra]].pickers.options({ scope = [[win]] }) end,          desc = [[Win]] },
    { [[<leader>pob]],  function() require [[mini.extra]].pickers.options({ scope = [[buf]] }) end,          desc = [[Buf]] },
    { [[<leader>pe]],   function() require [[mini.extra]].pickers.explorer() end,                            desc = [[Explorer]] },
    { [[<leader>p?]],   function() require [[mini.pick]].builtin.help() end,                                 desc = [[Help]] },
    { [[<leader>pka]],  function() require [[mini.extra]].pickers.keymaps({ scope = [[all]] }) end,          desc = [[All]] },
    { [[<leader>pkg]],  function() require [[mini.extra]].pickers.keymaps({ scope = [[global]] }) end,       desc = [[Global]] },
    { [[<leader>pkb]],  function() require [[mini.extra]].pickers.keymaps({ scope = [[buf]] }) end,          desc = [[Buf]] },
    { [[<leader>pC]],   function() require [[mini.extra]].pickers.commands() end,                            desc = [[Commands]] },
    { [[<leader>pO]],   function() require [[mini.extra]].pickers.oldfiles() end,                            desc = [[Oldfiles]] },
    { [[<leader>pBa]],  function() require [[mini.extra]].pickers.buf_lines({ scope = [[all]] }) end,        desc = [[All]] },
    { [[<leader>pBc]],  function() require [[mini.extra]].pickers.buf_lines({ scope = [[current]] }) end,    desc = [[Current]] },
    { [[<leader>pGfc]], function() require [[mini.extra]].pickers.git_files({ scope = [[cached]] }) end,     desc = [[Cached]] },
    { [[<leader>pGfm]], function() require [[mini.extra]].pickers.git_files({ scope = [[modified]] }) end,   desc = [[Modified]] },
    { [[<leader>pGfo]], function() require [[mini.extra]].pickers.git_files({ scope = [[others]] }) end,     desc = [[Others]] },
    { [[<leader>pGfi]], function() require [[mini.extra]].pickers.git_files({ scope = [[ignored]] }) end,    desc = [[Ignored]] },
    { [[<leader>pGfd]], function() require [[mini.extra]].pickers.git_files({ scope = [[deleted]] }) end,    desc = [[Deleted]] },
    { [[<leader>pGhu]], function() require [[mini.extra]].pickers.git_hunks({ scope = [[unstaged]] }) end,   desc = [[Unstaged]] },
    { [[<leader>pGhs]], function() require [[mini.extra]].pickers.git_hunks({ scope = [[staged]] }) end,     desc = [[Staged]] },
    { [[<leader>pGc]],  function() require [[mini.extra]].pickers.git_commits() end,                         desc = [[Git commits]] },
    { [[<leader>pGba]], function() require [[mini.extra]].pickers.git_branches({ scope = [[all]] }) end,     desc = [[All]] },
    { [[<leader>pGbl]], function() require [[mini.extra]].pickers.git_branches({ scope = [[local]] }) end,   desc = [[Local]] },
    { [[<leader>pGbr]], function() require [[mini.extra]].pickers.git_branches({ scope = [[remotes]] }) end, desc = [[Remotes]] },
    { [[<leader>pgl]],  function() require [[mini.pick]].builtin.grep_live() end,                            desc = [[Grep live ]] },
    { [[<leader>pHg]],  function() require [[mini.extra]].pickers.hl_groups() end,                           desc = [[Groups]] },
    { [[<leader>pR]],   function() require [[mini.extra]].pickers.registers() end,                           desc = [[Registers]] },
    { [[<leader>pda]],  function() require [[mini.extra]].pickers.diagnostic({ scope = [[all]] }) end,       desc = [[All]] },
    { [[<leader>pdc]],  function() require [[mini.extra]].pickers.diagnostic({ scope = [[current]] }) end,   desc = [[Current]] },
    { [[<leader>pHpa]], function() require [[mini.extra]].pickers.hipatterns({ scope = [[all]] }) end,       desc = [[All]] },
    { [[<leader>pHpc]], function() require [[mini.extra]].pickers.hipatterns({ scope = [[current]] }) end,   desc = [[Current]] },
    { [[<leader>pt]],   function() require [[mini.extra]].pickers.treesitter() end,                          desc = [[Treesitter]] },
    { [[<leader>ps]],   function() require [[mini.extra]].pickers.spellsuggest() end,                        desc = [[Spell suggest]] }
  },

  config = function(_, opts)
    local MiniPick = require [[mini.pick]]
    MiniPick.setup(opts)
    vim.ui.select = MiniPick.ui_select
  end
}
