---@type LazyPluginSpec
return {
  [[mini.clue]],
  event = [[VeryLazy]],

  opts = {
    triggers = {
      { mode = [[n]], keys = [[<Leader>]] },
      { mode = [[x]], keys = [[<Leader>]] },

      -- mini.align, mini.operators, mini.split, mini.surround, comments
      { mode = [[n]], keys = [[g]] },
      { mode = [[x]], keys = [[g]] },

      -- mini.ai
      { mode = [[v]], keys = [[a]] },
      { mode = [[x]], keys = [[a]] },
      { mode = [[v]], keys = [[i]] },
      { mode = [[x]], keys = [[i]] },

      -- mini.bracketed
      { mode = [[n]], keys = ']' },
      { mode = [[n]], keys = '[' },
      { mode = [[x]], keys = '[' },
      { mode = [[x]], keys = ']' },
    },

    clues = {
      -- Lsp
      { mode = [[n]], keys = [[<leader>l]],    desc = [[Lsp]] },
      { mode = [[x]], keys = [[<leader>l]],    desc = [[Lsp]] },
      { mode = [[n]], keys = [[<leader>lw]],   desc = [[Workspace folder]] },
      { mode = [[x]], keys = [[<leader>lw]],   desc = [[Workspace folder]] },
      { mode = [[n]], keys = [[<leader>le]],   desc = [[Extract]] },
      { mode = [[x]], keys = [[<leader>le]],   desc = [[Extract]] },
      { mode = [[n]], keys = [[<leader>li]],   desc = [[Inline]] },
      { mode = [[x]], keys = [[<leader>li]],   desc = [[Inline]] },
      { mode = [[n]], keys = [[<leader>lL]],   desc = [[Lint]] },
      { mode = [[x]], keys = [[<leader>lL]],   desc = [[Lint]] },


      -- Git (sign, neo)
      { mode = [[n]], keys = [[<leader>g]],    desc = [[Git]] },
      { mode = [[x]], keys = [[<leader>g]],    desc = [[Git]] },
      { mode = [[n]], keys = [[<leader>gh]],   desc = [[Hunk]] },
      { mode = [[x]], keys = [[<leader>gh]],   desc = [[Hunks]] },
      { mode = [[n]], keys = [[<leader>ght]],  desc = [[Toggle]] },
      { mode = [[x]], keys = [[<leader>ght]],  desc = [[Toggle]] },
      { mode = [[n]], keys = [[<leader>ghth]], desc = [[Highlights]] },
      { mode = [[x]], keys = [[<leader>ghth]], desc = [[Highlights]] },
      { mode = [[n]], keys = [[<leader>ghP]],  desc = [[Populate list]] },
      { mode = [[x]], keys = [[<leader>ghP]],  desc = [[Populate list]] },
      { mode = [[n]], keys = [[<leader>ghp]],  desc = [[Preview]] },
      { mode = [[x]], keys = [[<leader>ghp]],  desc = [[Preview]] },
      { mode = [[n]], keys = [[<leader>ghj]],  desc = [[Jump]] },
      { mode = [[x]], keys = [[<leader>ghj]],  desc = [[Jump]] },
      { mode = [[n]], keys = [[<leader>ghb]],  desc = [[Buffer]] },
      { mode = [[x]], keys = [[<leader>ghb]],  desc = [[Buffer]] },
      { mode = [[n]], keys = [[<leader>ghbr]], desc = [[Reset]] },
      { mode = [[x]], keys = [[<leader>ghbr]], desc = [[Reset]] },
      { mode = [[n]], keys = [[<leader>ghl]],  desc = [[Line]] },
      { mode = [[x]], keys = [[<leader>ghl]],  desc = [[Line]] },

      -- mini.bufremove
      { mode = [[n]], keys = [[<leader>b]],    desc = [[Buffer]] },
      { mode = [[x]], keys = [[<leader>b]],    desc = [[Buffer]] },

      -- mini.visists
      { mode = [[n]], keys = [[<leader>v]],    desc = [[Visits]] },
      { mode = [[n]], keys = [[<leader>va]],   desc = [[Add]] },

      -- mini.pick
      { mode = [[n]], keys = [[<leader>p]],    desc = [[Pick]] },
      { mode = [[n]], keys = [[<leader>pB]],   desc = [[Buffer Lines]] },
      { mode = [[n]], keys = [[<leader>pG]],   desc = [[Git]] },
      { mode = [[n]], keys = [[<leader>pGb]],  desc = [[Git branches]] },
      { mode = [[n]], keys = [[<leader>pGf]],  desc = [[Git files]] },
      { mode = [[n]], keys = [[<leader>pGh]],  desc = [[Git hunks]] },
      { mode = [[n]], keys = [[<leader>pH]],   desc = [[Highlights]] },
      { mode = [[n]], keys = [[<leader>pHp]],  desc = [[Patterns]] },
      { mode = [[n]], keys = [[<leader>pL]],   desc = [[List]] },
      { mode = [[n]], keys = [[<leader>pd]],   desc = [[Diagnostic]] },
      { mode = [[n]], keys = [[<leader>pg]],   desc = [[Grep]] },
      { mode = [[n]], keys = [[<leader>ph]],   desc = [[History]] },
      { mode = [[n]], keys = [[<leader>pk]],   desc = [[Keymaps]] },
      { mode = [[n]], keys = [[<leader>pl]],   desc = [[Lsp]] },
      { mode = [[n]], keys = [[<leader>pls]],  desc = [[Symbol]] },
      { mode = [[n]], keys = [[<leader>pm]],   desc = [[Marks]] },
      { mode = [[n]], keys = [[<leader>po]],   desc = [[Options]] },
      { mode = [[n]], keys = [[<leader>pv]],   desc = [[Vists]] },

      -- mini.ai
      { mode = [[v]], keys = [[a ]],           desc = "Around Whitespace" },
      { mode = [[v]], keys = [[a"]],           desc = 'Around Balanced "' },
      { mode = [[v]], keys = [[a']],           desc = "Around Balanced '" },
      { mode = [[v]], keys = [[a`]],           desc = "Around Balanced `" },
      { mode = [[v]], keys = [[a(]],           desc = "Around Balanced (" },
      { mode = [[v]], keys = [[a)]],           desc = "Around Balanced ) including white-space" },
      { mode = [[v]], keys = [[a>]],           desc = "Around Balanced > including white-space" },
      { mode = [[v]], keys = [[a<lt>]],        desc = "Around Balanced <" },
      { mode = [[v]], keys = 'a]',             desc = "Around Balanced ] including white-space" },
      { mode = [[v]], keys = 'a[',             desc = "Around Balanced [" },
      { mode = [[v]], keys = [[a}]],           desc = "Around Balanced } including white-space" },
      { mode = [[v]], keys = [[a{]],           desc = "Around Balanced {" },
      { mode = [[v]], keys = [[a?]],           desc = "Around User Prompt" },
      { mode = [[v]], keys = [[a_]],           desc = "Around Underscore" },
      { mode = [[v]], keys = [[aa]],           desc = "Around Argument" },
      { mode = [[v]], keys = [[ab]],           desc = "Around Balanced ), ], }" },
      { mode = [[v]], keys = [[ac]],           desc = "Around Class" },
      { mode = [[v]], keys = [[af]],           desc = "Around Function" },
      { mode = [[v]], keys = [[ao]],           desc = "Around Block, conditional, loop" },
      { mode = [[v]], keys = [[aq]],           desc = "Around Quote `, \", '" },
      { mode = [[v]], keys = [[at]],           desc = "Around Tag" },
      { mode = [[x]], keys = [[a ]],           desc = "Around Whitespace" },
      { mode = [[x]], keys = [[a"]],           desc = 'Around Balanced "' },
      { mode = [[x]], keys = [[a']],           desc = "Around Balanced '" },
      { mode = [[x]], keys = [[a`]],           desc = "Around Balanced `" },
      { mode = [[x]], keys = [[a(]],           desc = "Around Balanced (" },
      { mode = [[x]], keys = [[a)]],           desc = "Around Balanced ) including white-space" },
      { mode = [[x]], keys = [[a>]],           desc = "Around Balanced > including white-space" },
      { mode = [[x]], keys = [[a<lt>]],        desc = "Around Balanced <" },
      { mode = [[x]], keys = 'a]',             desc = "Around Balanced ] including white-space" },
      { mode = [[x]], keys = 'a[',             desc = "Around Balanced [" },
      { mode = [[x]], keys = [[a}]],           desc = "Around Balanced } including white-space" },
      { mode = [[x]], keys = [[a{]],           desc = "Around Balanced {" },
      { mode = [[x]], keys = [[a?]],           desc = "Around User Prompt" },
      { mode = [[x]], keys = [[a_]],           desc = "Around Underscore" },
      { mode = [[x]], keys = [[aa]],           desc = "Around Argument" },
      { mode = [[x]], keys = [[ab]],           desc = "Around Balanced ), ], }" },
      { mode = [[x]], keys = [[ac]],           desc = "Around Class" },
      { mode = [[x]], keys = [[af]],           desc = "Around Function" },
      { mode = [[x]], keys = [[ao]],           desc = "Around Block, conditional, loop" },
      { mode = [[x]], keys = [[aq]],           desc = "Around Quote `, \", '" },
      { mode = [[x]], keys = [[at]],           desc = "Around Tag" },
      { mode = [[v]], keys = [[i ]],           desc = "Inside Whitespace" },
      { mode = [[v]], keys = [[i"]],           desc = 'Inside Balanced "' },
      { mode = [[v]], keys = [[i']],           desc = "Inside Balanced '" },
      { mode = [[v]], keys = [[i`]],           desc = "Inside Balanced `" },
      { mode = [[v]], keys = [[i(]],           desc = "Inside Balanced (" },
      { mode = [[v]], keys = [[i)]],           desc = "Inside Balanced ) including white-space" },
      { mode = [[v]], keys = [[i>]],           desc = "Inside Balanced > including white-space" },
      { mode = [[v]], keys = [[i<lt>]],        desc = "Inside Balanced <" },
      { mode = [[v]], keys = 'i]',             desc = "Inside Balanced ] including white-space" },
      { mode = [[v]], keys = 'i[',             desc = "Inside Balanced [" },
      { mode = [[v]], keys = [[i}]],           desc = "Inside Balanced } including white-space" },
      { mode = [[v]], keys = [[i{]],           desc = "Inside Balanced {" },
      { mode = [[v]], keys = [[i?]],           desc = "Inside User Prompt" },
      { mode = [[v]], keys = [[i_]],           desc = "Inside Underscore" },
      { mode = [[v]], keys = [[ia]],           desc = "Inside Argument" },
      { mode = [[v]], keys = [[ib]],           desc = "Inside Balanced ), ], }" },
      { mode = [[v]], keys = [[ic]],           desc = "Inside Class" },
      { mode = [[v]], keys = [[if]],           desc = "Inside Function" },
      { mode = [[v]], keys = [[io]],           desc = "Inside Block, conditional, loop" },
      { mode = [[v]], keys = [[iq]],           desc = "Inside Quote `, \", '" },
      { mode = [[v]], keys = [[it]],           desc = "Inside Tag" },
      { mode = [[x]], keys = [[i ]],           desc = "Inside Whitespace" },
      { mode = [[x]], keys = [[i"]],           desc = 'Inside Balanced "' },
      { mode = [[x]], keys = [[i']],           desc = "Inside Balanced '" },
      { mode = [[x]], keys = [[i`]],           desc = "Inside Balanced `" },
      { mode = [[x]], keys = [[i(]],           desc = "Inside Balanced (" },
      { mode = [[x]], keys = [[i)]],           desc = "Inside Balanced ) including white-space" },
      { mode = [[x]], keys = [[i>]],           desc = "Inside Balanced > including white-space" },
      { mode = [[x]], keys = [[i<lt>]],        desc = "Inside Balanced <" },
      { mode = [[x]], keys = 'i]',             desc = "Inside Balanced ] including white-space" },
      { mode = [[x]], keys = 'i[',             desc = "Inside Balanced [" },
      { mode = [[x]], keys = [[i}]],           desc = "Inside Balanced } including white-space" },
      { mode = [[x]], keys = [[i{]],           desc = "Inside Balanced {" },
      { mode = [[x]], keys = [[i?]],           desc = "Inside User Prompt" },
      { mode = [[x]], keys = [[i_]],           desc = "Inside Underscore" },
      { mode = [[x]], keys = [[ia]],           desc = "Inside Argument" },
      { mode = [[x]], keys = [[ib]],           desc = "Inside Balanced ), ], }" },
      { mode = [[x]], keys = [[ic]],           desc = "Inside Class" },
      { mode = [[x]], keys = [[if]],           desc = "Inside Function" },
      { mode = [[x]], keys = [[io]],           desc = "Inside Block, conditional, loop" },
      { mode = [[x]], keys = [[iq]],           desc = "Inside Quote `, \", '" },
      { mode = [[x]], keys = [[it]],           desc = "Inside Tag" },
    },

    -- Ideally, we'd use 'auto' for the width, but auto calculation is a bit
    -- too overzealous, so let's use 55 as a sweet spot, which seems to  cover
    -- basically every case.
    --
    window = { config = { width = 55 }, delay = 500 }
  }
}
