vim.keymap.set([[x]], [[p]],      [['pgv"'.v:register.'y`>']], { silent = true, expr = true })
vim.keymap.set([[x]], [[P]],      [['Pgv"'.v:register.'y`>']], { silent = true, expr = true })
vim.keymap.set([[n]], [[j]],      [[v:count?'j':'gj']],        { silent = true, expr = true })
vim.keymap.set([[n]], [[k]],      [[v:count?'k':'gk']],        { silent = true, expr = true })
vim.keymap.set([[n]], [[<Down>]], [[v:count?'j':'gj']],        { silent = true, expr = true })
vim.keymap.set([[n]], [[<Up>]],   [[v:count?'k':'gk']],        { silent = true, expr = true })
vim.keymap.set([[x]], [[<]],      [[<gv]],                     { silent = true })
vim.keymap.set([[x]], [[>]],      [[>gv]],                     { silent = true })
vim.keymap.set([[n]], [[x]],      [["_x]],                     { silent = true })
vim.keymap.set([[n]], [[X]],      [["_X]],                     { silent = true })
vim.keymap.set([[x]], [[x]],      [["_x]],                     { silent = true })
vim.keymap.set([[x]], [[X]],      [["_X]],                     { silent = true })
vim.keymap.set([[i]], [[,]],      [[,<c-g>u]],                 { silent = true })
vim.keymap.set([[i]], [[.]],      [[.<c-g>u]],                 { silent = true })
vim.keymap.set([[i]], [[;]],      [[;<c-g>u]],                 { silent = true })
vim.keymap.set([[i]], [[{]],      [[{<c-g>u]],                 { silent = true })
vim.keymap.set([[i]], [[}]],      [[}<c-g>u]],                 { silent = true })
vim.keymap.set([[i]], [["]],      [["<c-g>u]],                 { silent = true })
vim.keymap.set([[i]], [[']],      [['<c-g>u]],                 { silent = true })
vim.keymap.set([[i]], [[<]],      [[<<c-g>u]],                 { silent = true })
vim.keymap.set([[i]], [[>]],      [[><c-g>u]],                 { silent = true })
vim.keymap.set([[i]], "[",        "[<c-g>u",                   { silent = true })
vim.keymap.set([[i]], "]",        "]<c-g>u",                   { silent = true })

-- Avoid triggering accidental keystrokes by disabling built-in keybindings we don't use.
--
vim.keymap.set({[[n]], [[x]]},         [[q]],           [[<Nop>]],                 { silent = true, desc = [[Record a macro in {register}]] })
vim.keymap.set({[[n]], [[x]]},         [[@]],           [[<Nop>]],                 { silent = true, desc = [[Execute macro {register}]] })
vim.keymap.set({[[n]], [[x]]},         [[@@]],          [[<Nop>]],                 { silent = true, desc = [[Repeat last macro]] })
vim.keymap.set({[[n]], [[x]]},         [[Q]],           [[<Nop>]],                 { silent = true, desc = [[Replay last macro (nvim) or Ex mode (vim)]] })
vim.keymap.set({[[n]], [[x]]},         [[gQ]],          [[<Nop>]],                 { silent = true, desc = [[Switch to ex mode]] })
vim.keymap.set({[[n]], [[x]], [[i]]},  [[<F1>]],        [[<Nop>]],                 { silent = true, desc = [[Help page]] })
vim.keymap.set({[[n]], [[x]]},         [[q:]],          [[<Nop>]],                 { silent = true, desc = [[Command-line window]] })

return {}
