---@type LazyPluginSpec
return {
  [[mini.bracketed]],
  config = true,
  keys = {
    { '[b', desc = [[Buffer first]] },
    { '[B', desc = [[Buffer backward]] },
    { '[C', desc = [[Comment first]] },
    { '[c', desc = [[Comment backward]] },
    { '[D', desc = [[Diagnostic first]] },
    { '[d', desc = [[Diagnostic backward]] },
    { '[F', desc = [[File first]] },
    { '[f', desc = [[File backward]] },
    { '[I', desc = [[Indent first]] },
    { '[i', desc = [[Indent backward]] },
    { '[J', desc = [[Jump first]] },
    { '[j', desc = [[Jump backward]] },
    { '[L', desc = [[Location first]] },
    { '[l', desc = [[Location backward]] },
    { '[O', desc = [[Oldfile first]] },
    { '[o', desc = [[Oldfile backward]] },
    { '[Q', desc = [[Quickfix first]] },
    { '[q', desc = [[Quickfix backward]] },
    { '[T', desc = [[Treesitter first]] },
    { '[t', desc = [[Treesitter backward]] },
    { '[U', desc = [[Undo first]] },
    { '[u', desc = [[Undo backward]] },
    { '[W', desc = [[Window first]] },
    { '[w', desc = [[Window backward]] },
    { '[X', desc = [[Conflict first]] },
    { '[x', desc = [[Conflict backward]] },
    { '[Y', desc = [[Yank first]] },
    { '[y', desc = [[Yank backward]] },

    { ']b', desc = [[Buffer last]] },
    { ']B', desc = [[Buffer forward]] },
    { ']C', desc = [[Comment last]] },
    { ']c', desc = [[Comment forward]] },
    { ']D', desc = [[Diagnostic last]] },
    { ']d', desc = [[Diagnostic forward]] },
    { ']F', desc = [[File last]] },
    { ']f', desc = [[File forward]] },
    { ']I', desc = [[Indent last]] },
    { ']i', desc = [[Indent forward]] },
    { ']J', desc = [[Jump last]] },
    { ']j', desc = [[Jump forward]] },
    { ']L', desc = [[Location last]] },
    { ']l', desc = [[Location forward]] },
    { ']O', desc = [[Oldfile last]] },
    { ']o', desc = [[Oldfile forward]] },
    { ']Q', desc = [[Quickfix last]] },
    { ']q', desc = [[Quickfix forward]] },
    { ']T', desc = [[Treesitter last]] },
    { ']t', desc = [[Treesitter forward]] },
    { ']U', desc = [[Undo last]] },
    { ']u', desc = [[Undo forward]] },
    { ']W', desc = [[Window last]] },
    { ']w', desc = [[Window forward]] },
    { ']X', desc = [[Conflict last]] },
    { ']x', desc = [[Conflict forward]] },
    { ']Y', desc = [[Yank last]] },
    { ']y', desc = [[Yank forward]] }
  }
}
