---@type LazySpec
return {
--{ import = [[spec.mini.mini-ai]] },
--{ import = [[spec.mini.mini-align]] },
--{ import = [[spec.mini.mini-animate]] },
--{ import = [[spec.mini.mini-base16]] },
  { import = [[spec.mini.mini-basics]] },
--{ import = [[spec.mini.mini-bracketed]] },
--{ import = [[spec.mini.mini-bufremove]] },
  { import = [[spec.mini.mini-clue]] },
  { import = [[spec.mini.mini-colors]] },
  { import = [[spec.mini.mini-comment]] },
--{ import = [[spec.mini.mini-completion]] },
--{ import = [[spec.mini.mini-cursorword]] },
--{ import = [[spec.mini.mini-doc]] },
  { import = [[spec.mini.mini-files]] },
--{ import = [[spec.mini.mini-fuzzy]] },
  { import = [[spec.mini.mini-hipatterns]] },
  { import = [[spec.mini.mini-hues]] },
--{ import = [[spec.mini.mini-indentscope]] },
--{ import = [[spec.mini.mini-jump]] },
--{ import = [[spec.mini.mini-jump2d]] },
  { import = [[spec.mini.mini-misc]] },
--{ import = [[spec.mini.mini-move]] },
--{ import = [[spec.mini.mini-operators]] },
--{ import = [[spec.mini.mini-pairs]] },
--{ import = [[spec.mini.mini-sessions]] },
--{ import = [[spec.mini.mini-splitjoin]] },
--{ import = [[spec.mini.mini-starter]] },
--{ import = [[spec.mini.mini-statusline]] },
--{ import = [[spec.mini.mini-surround]] },
  { import = [[spec.mini.mini-tabline]] },
--{ import = [[spec.mini.mini-test]] },
--{ import = [[spec.mini.mini-trailspace]] },
  { import = [[spec.mini.mini-pick]] }
}
