shell = "fish"

[font.bold]
family = "MonoLisa"
style = "Bold"

[font.bold_italic]
family = "MonoLisa"
style = "Bold Italic"

[font.italic]
family = "MonoLisa"
style = "Italic"

[font.normal]
family = "MonoLisa"
style = "Regular"

[font]
size = 14.0

[terminal]
osc52 = "CopyPaste"

[window]
dynamic_padding = true
dynamic_title = true
padding = { x = 10, y = 10 }
