-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd("highlight clear") end
vim.g.colors_name = "mini"

-- Highlight groups
local hi = vim.api.nvim_set_hl

if vim.o.background == "dark" then
  hi(0, "@character.special", { link = "SpecialChar" })
  hi(0, "@comment.documentation", { link = "@comment" })
  hi(0, "@comment.error", { link = "@text.danger" })
  hi(0, "@comment.note", { link = "@text.note" })
  hi(0, "@comment.todo", { link = "@text.todo" })
  hi(0, "@comment.warning", { link = "@text.warning" })
  hi(0, "@conditional", { link = "Conditional" })
  hi(0, "@constant.builtin", { link = "Special" })
  hi(0, "@constant.macro", { link = "Macro" })
  hi(0, "@debug", { link = "Debug" })
  hi(0, "@define", { link = "Define" })
  hi(0, "@diff.delta", { link = "diffChanged" })
  hi(0, "@diff.minus", { link = "diffRemoved" })
  hi(0, "@diff.plus", { link = "diffAdded" })
  hi(0, "@exception", { link = "Exception" })
  hi(0, "@field", { link = "Identifier" })
  hi(0, "@float", { link = "Float" })
  hi(0, "@function.builtin", { link = "Special" })
  hi(0, "@function.call", { link = "Function" })
  hi(0, "@function.macro", { link = "Macro" })
  hi(0, "@function.method", { link = "@method" })
  hi(0, "@function.method.call", { link = "@method.call" })
  hi(0, "@include", { link = "Include" })
  hi(0, "@keyword.conditional", { link = "@keyword" })
  hi(0, "@keyword.conditional.ternary", { link = "Keyword" })
  hi(0, "@keyword.coroutine", { link = "@keyword" })
  hi(0, "@keyword.debug", { bold = true, fg = "#87d8d2" })
  hi(0, "@keyword.directive", { bold = true, fg = "#bcc2fb" })
  hi(0, "@keyword.directive.define", { link = "@keyword.directive" })
  hi(0, "@keyword.exception", { link = "@keyword" })
  hi(0, "@keyword.function", { link = "@keyword" })
  hi(0, "@keyword.import", { bold = true, fg = "#bcc2fb" })
  hi(0, "@keyword.operator", { link = "@keyword" })
  hi(0, "@keyword.repeat", { link = "@keyword" })
  hi(0, "@keyword.return", { bold = true, fg = "#f0ba95" })
  hi(0, "@keyword.storage", { bold = true, fg = "#c3c7cd" })
  hi(0, "@lsp.mod.defaultLibrary", { link = "Special" })
  hi(0, "@lsp.mod.deprecated", { fg = "#f6b2bb" })
  hi(0, "@lsp.type.class", { link = "@structure" })
  hi(0, "@lsp.type.decorator", { link = "@function" })
  hi(0, "@lsp.type.enum", { link = "@type" })
  hi(0, "@lsp.type.enumMember", { link = "@constant" })
  hi(0, "@lsp.type.function", { link = "@function" })
  hi(0, "@lsp.type.interface", { link = "@type" })
  hi(0, "@lsp.type.macro", { link = "@macro" })
  hi(0, "@lsp.type.method", { link = "@method" })
  hi(0, "@lsp.type.namespace", { link = "@namespace" })
  hi(0, "@lsp.type.parameter", { link = "@parameter" })
  hi(0, "@lsp.type.property", { link = "@property" })
  hi(0, "@lsp.type.struct", { link = "@structure" })
  hi(0, "@lsp.type.type", { link = "@type" })
  hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
  hi(0, "@lsp.type.variable", { link = "@variable" })
  hi(0, "@macro", { link = "Macro" })
  hi(0, "@markup.environment", { link = "@module" })
  hi(0, "@markup.heading", { link = "@text.title" })
  hi(0, "@markup.italic", { link = "@text.emphasis" })
  hi(0, "@markup.link", { link = "@text.reference" })
  hi(0, "@markup.link.label", { link = "@markup.link" })
  hi(0, "@markup.link.url", { fg = "#c3c7cd", underline = true })
  hi(0, "@markup.list", { link = "@punctuation.special" })
  hi(0, "@markup.list.checked", { link = "DiagnosticOk" })
  hi(0, "@markup.list.unchecked", { link = "DiagnosticWarn" })
  hi(0, "@markup.math", { link = "@string.special" })
  hi(0, "@markup.quote", { link = "@string.special" })
  hi(0, "@markup.raw", { link = "@text.literal" })
  hi(0, "@markup.raw.block", { link = "@markup.raw" })
  hi(0, "@markup.strikethrough", { link = "@text.strikethrough" })
  hi(0, "@markup.strong", { link = "@text.strong" })
  hi(0, "@markup.underline", { link = "@text.underline" })
  hi(0, "@method", { link = "Function" })
  hi(0, "@method.call", { link = "Function" })
  hi(0, "@module", { link = "@namespace" })
  hi(0, "@module.builtin", { link = "@variable.builtin" })
  hi(0, "@namespace", { link = "Identifier" })
  hi(0, "@none", { link = "Normal" })
  hi(0, "@number.float", { link = "@float" })
  hi(0, "@parameter", { fg = "#bcc2fb" })
  hi(0, "@preproc", { link = "PreProc" })
  hi(0, "@punctuation.bracket", { link = "@punctuation" })
  hi(0, "@punctuation.delimiter", { link = "@punctuation" })
  hi(0, "@punctuation.special", { link = "Special" })
  hi(0, "@repeat", { link = "Repeat" })
  hi(0, "@storageclass", { link = "StorageClass" })
  hi(0, "@string.documentation", { link = "@string" })
  hi(0, "@string.escape", { link = "SpecialChar" })
  hi(0, "@string.regexp", { link = "SpecialChar" })
  hi(0, "@string.special", { link = "SpecialChar" })
  hi(0, "@string.special.path", { link = "Directory" })
  hi(0, "@string.special.symbol", { link = "@constant" })
  hi(0, "@string.special.url", { link = "@markup.link.url" })
  hi(0, "@structure", { link = "Structure" })
  hi(0, "@symbol", { link = "Keyword" })
  hi(0, "@tag.attribute", { link = "@tag" })
  hi(0, "@tag.delimiter", { link = "@punctuation" })
  hi(0, "@text.danger", { link = "ErrorMsg" })
  hi(0, "@text.emphasis", { italic = true })
  hi(0, "@text.literal", { link = "Special" })
  hi(0, "@text.note", { link = "MoreMsg" })
  hi(0, "@text.reference", { link = "Identifier" })
  hi(0, "@text.strike", { strikethrough = true })
  hi(0, "@text.strong", { bold = true })
  hi(0, "@text.title", { link = "Title" })
  hi(0, "@text.todo", { link = "Todo" })
  hi(0, "@text.underline", { link = "Underlined" })
  hi(0, "@text.uri", { link = "Underlined" })
  hi(0, "@text.warning", { link = "WarningMsg" })
  hi(0, "@type.builtin", { link = "Special" })
  hi(0, "@type.definition", { link = "Typedef" })
  hi(0, "@type.qualifier", { link = "StorageClass" })
  hi(0, "@variable", { fg = "#c3c7cd" })
  hi(0, "@variable.builtin", { link = "Special" })
  hi(0, "@variable.member", { link = "@field" })
  hi(0, "@variable.parameter", { link = "@parameter" })
  hi(0, "Added", { fg = "#a7d5a7" })
  hi(0, "Beacon", { bg = "#e8edf3" })
  hi(0, "Bold", { bold = true })
  hi(0, "BufferCurrent", { bg = "#192331", bold = true, fg = "#a6c9fb" })
  hi(0, "BufferCurrentIcon", { bg = "#192331" })
  hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
  hi(0, "BufferCurrentMod", { bg = "#323c4c", bold = true, fg = "#a6c9fb" })
  hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
  hi(0, "BufferCurrentTarget", { bg = "#4c5767", bold = true, fg = "#a6c9fb" })
  hi(0, "BufferInactive", { bg = "#0d1724", fg = "#c3c7cd" })
  hi(0, "BufferInactiveIcon", { bg = "#0d1724" })
  hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
  hi(0, "BufferInactiveMod", { bg = "#323c4c", fg = "#c3c7cd" })
  hi(0, "BufferInactiveSign", { link = "BufferInactive" })
  hi(0, "BufferInactiveTarget", { bg = "#4c5767", fg = "#c3c7cd" })
  hi(0, "BufferLineBuffer", { fg = "#898c92" })
  hi(0, "BufferLineBufferSelected", { bold = true, fg = "#c3c7cd" })
  hi(0, "BufferLineBufferVisible", { fg = "#c3c7cd" })
  hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
  hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
  hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
  hi(0, "BufferLineFill", { link = "Normal" })
  hi(0, "BufferLineTab", { bg = "#a7d5a7", fg = "#192331" })
  hi(0, "BufferLineTabSelected", { bg = "#a7d5a7", bold = true, fg = "#192331" })
  hi(0, "BufferOffset", { link = "Normal" })
  hi(0, "BufferTabpageFill", { link = "Normal" })
  hi(0, "BufferTabpages", { bg = "#a7d5a7", bold = true, fg = "#192331" })
  hi(0, "BufferVisible", { bg = "#192331", bold = true, fg = "#c3c7cd" })
  hi(0, "BufferVisibleIcon", { bg = "#192331" })
  hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
  hi(0, "BufferVisibleMod", { bg = "#323c4c", bold = true, fg = "#c3c7cd" })
  hi(0, "BufferVisibleSign", { link = "BufferVisible" })
  hi(0, "BufferVisibleTarget", { bg = "#4c5767", bold = true, fg = "#c3c7cd" })
  hi(0, "Changed", { fg = "#87d8d2" })
  hi(0, "CmpItemAbbr", { fg = "#c3c7cd" })
  hi(0, "CmpItemAbbrDeprecated", { link = "Comment" })
  hi(0, "CmpItemAbbrMatch", { bold = true })
  hi(0, "CmpItemAbbrMatchFuzzy", { bold = true })
  hi(0, "CmpItemKind", { fg = "#c3c7cd" })
  hi(0, "CmpItemKindClass", { link = "Type" })
  hi(0, "CmpItemKindColor", { link = "Special" })
  hi(0, "CmpItemKindConstant", { link = "Constant" })
  hi(0, "CmpItemKindConstructor", { link = "Type" })
  hi(0, "CmpItemKindEnum", { link = "Structure" })
  hi(0, "CmpItemKindEnumMember", { link = "Structure" })
  hi(0, "CmpItemKindEvent", { link = "Exception" })
  hi(0, "CmpItemKindField", { link = "Structure" })
  hi(0, "CmpItemKindFile", { link = "Tag" })
  hi(0, "CmpItemKindFolder", { link = "Directory" })
  hi(0, "CmpItemKindFunction", { link = "Function" })
  hi(0, "CmpItemKindInterface", { link = "Structure" })
  hi(0, "CmpItemKindKeyword", { link = "Keyword" })
  hi(0, "CmpItemKindMethod", { link = "Function" })
  hi(0, "CmpItemKindModule", { link = "Structure" })
  hi(0, "CmpItemKindOperator", { link = "Operator" })
  hi(0, "CmpItemKindProperty", { link = "Structure" })
  hi(0, "CmpItemKindReference", { link = "Tag" })
  hi(0, "CmpItemKindSnippet", { link = "Special" })
  hi(0, "CmpItemKindStruct", { link = "Structure" })
  hi(0, "CmpItemKindText", { link = "Normal" })
  hi(0, "CmpItemKindTypeParameter", { link = "Type" })
  hi(0, "CmpItemKindUnit", { link = "Special" })
  hi(0, "CmpItemKindValue", { link = "Identifier" })
  hi(0, "CmpItemKindVariable", { link = "Delimiter" })
  hi(0, "CmpItemMenu", { fg = "#c3c7cd" })
  hi(0, "CocBold", { bold = true })
  hi(0, "CocCodeLens", { link = "LspCodeLens" })
  hi(0, "CocCursorTransparent", { blend = 100, strikethrough = true })
  hi(0, "CocDisabled", { link = "Comment" })
  hi(0, "CocFadeOut", { link = "Comment" })
  hi(0, "CocInlayHint", { ctermfg = 116, fg = "#87d8d2" })
  hi(0, "CocItalic", { italic = true })
  hi(0, "CocLink", { sp = "#15aabf", underline = true })
  hi(0, "CocListBgBlack", { bg = "#192331", ctermbg = 0 })
  hi(0, "CocListBgBlue", { bg = "#93d0f4", ctermbg = 12 })
  hi(0, "CocListBgCyan", { bg = "#87d8d2", ctermbg = 14 })
  hi(0, "CocListBgGreen", { bg = "#a7d5a7", ctermbg = 10 })
  hi(0, "CocListBgGrey", { bg = "#192331", ctermbg = 248 })
  hi(0, "CocListBgMagenta", { bg = "#e2b5e4", ctermbg = 13 })
  hi(0, "CocListBgRed", { bg = "#f6b2bb", ctermbg = 9 })
  hi(0, "CocListBgWhite", { bg = "#c3c7cd", ctermbg = 15 })
  hi(0, "CocListBgYellow", { bg = "#d2c98c", ctermbg = 11 })
  hi(0, "CocListBlackBlack", { bg = "#192331", fg = "#192331" })
  hi(0, "CocListBlackBlue", { bg = "#93d0f4", fg = "#192331" })
  hi(0, "CocListBlackCyan", { bg = "#87d8d2", fg = "#192331" })
  hi(0, "CocListBlackGreen", { bg = "#a7d5a7", fg = "#192331" })
  hi(0, "CocListBlackGrey", { bg = "#192331", fg = "#192331" })
  hi(0, "CocListBlackMagenta", { bg = "#e2b5e4", fg = "#192331" })
  hi(0, "CocListBlackRed", { bg = "#f6b2bb", fg = "#192331" })
  hi(0, "CocListBlackWhite", { bg = "#c3c7cd", fg = "#192331" })
  hi(0, "CocListBlackYellow", { bg = "#d2c98c", fg = "#192331" })
  hi(0, "CocListBlueBlack", { bg = "#192331", fg = "#93d0f4" })
  hi(0, "CocListBlueBlue", { bg = "#93d0f4", fg = "#93d0f4" })
  hi(0, "CocListBlueCyan", { bg = "#87d8d2", fg = "#93d0f4" })
  hi(0, "CocListBlueGreen", { bg = "#a7d5a7", fg = "#93d0f4" })
  hi(0, "CocListBlueGrey", { bg = "#192331", fg = "#93d0f4" })
  hi(0, "CocListBlueMagenta", { bg = "#e2b5e4", fg = "#93d0f4" })
  hi(0, "CocListBlueRed", { bg = "#f6b2bb", fg = "#93d0f4" })
  hi(0, "CocListBlueWhite", { bg = "#c3c7cd", fg = "#93d0f4" })
  hi(0, "CocListBlueYellow", { bg = "#d2c98c", fg = "#93d0f4" })
  hi(0, "CocListCyanBlack", { bg = "#192331", fg = "#87d8d2" })
  hi(0, "CocListCyanBlue", { bg = "#93d0f4", fg = "#87d8d2" })
  hi(0, "CocListCyanCyan", { bg = "#87d8d2", fg = "#87d8d2" })
  hi(0, "CocListCyanGreen", { bg = "#a7d5a7", fg = "#87d8d2" })
  hi(0, "CocListCyanGrey", { bg = "#192331", fg = "#87d8d2" })
  hi(0, "CocListCyanMagenta", { bg = "#e2b5e4", fg = "#87d8d2" })
  hi(0, "CocListCyanRed", { bg = "#f6b2bb", fg = "#87d8d2" })
  hi(0, "CocListCyanWhite", { bg = "#c3c7cd", fg = "#87d8d2" })
  hi(0, "CocListCyanYellow", { bg = "#d2c98c", fg = "#87d8d2" })
  hi(0, "CocListFgBlack", { ctermfg = 0, fg = "#192331" })
  hi(0, "CocListFgBlue", { ctermfg = 12, fg = "#93d0f4" })
  hi(0, "CocListFgCyan", { ctermfg = 14, fg = "#87d8d2" })
  hi(0, "CocListFgGreen", { ctermfg = 10, fg = "#a7d5a7" })
  hi(0, "CocListFgGrey", { ctermfg = 248, fg = "#192331" })
  hi(0, "CocListFgMagenta", { ctermfg = 13, fg = "#e2b5e4" })
  hi(0, "CocListFgRed", { ctermfg = 9, fg = "#f6b2bb" })
  hi(0, "CocListFgWhite", { ctermfg = 15, fg = "#c3c7cd" })
  hi(0, "CocListFgYellow", { ctermfg = 11, fg = "#d2c98c" })
  hi(0, "CocListGreenBlack", { bg = "#192331", fg = "#a7d5a7" })
  hi(0, "CocListGreenBlue", { bg = "#93d0f4", fg = "#a7d5a7" })
  hi(0, "CocListGreenCyan", { bg = "#87d8d2", fg = "#a7d5a7" })
  hi(0, "CocListGreenGreen", { bg = "#a7d5a7", fg = "#a7d5a7" })
  hi(0, "CocListGreenGrey", { bg = "#192331", fg = "#a7d5a7" })
  hi(0, "CocListGreenMagenta", { bg = "#e2b5e4", fg = "#a7d5a7" })
  hi(0, "CocListGreenRed", { bg = "#f6b2bb", fg = "#a7d5a7" })
  hi(0, "CocListGreenWhite", { bg = "#c3c7cd", fg = "#a7d5a7" })
  hi(0, "CocListGreenYellow", { bg = "#d2c98c", fg = "#a7d5a7" })
  hi(0, "CocListGreyBlack", { bg = "#192331", fg = "#192331" })
  hi(0, "CocListGreyBlue", { bg = "#93d0f4", fg = "#192331" })
  hi(0, "CocListGreyCyan", { bg = "#87d8d2", fg = "#192331" })
  hi(0, "CocListGreyGreen", { bg = "#a7d5a7", fg = "#192331" })
  hi(0, "CocListGreyGrey", { bg = "#192331", fg = "#192331" })
  hi(0, "CocListGreyMagenta", { bg = "#e2b5e4", fg = "#192331" })
  hi(0, "CocListGreyRed", { bg = "#f6b2bb", fg = "#192331" })
  hi(0, "CocListGreyWhite", { bg = "#c3c7cd", fg = "#192331" })
  hi(0, "CocListGreyYellow", { bg = "#d2c98c", fg = "#192331" })
  hi(0, "CocListMagentaBlack", { bg = "#192331", fg = "#e2b5e4" })
  hi(0, "CocListMagentaBlue", { bg = "#93d0f4", fg = "#e2b5e4" })
  hi(0, "CocListMagentaCyan", { bg = "#87d8d2", fg = "#e2b5e4" })
  hi(0, "CocListMagentaGreen", { bg = "#a7d5a7", fg = "#e2b5e4" })
  hi(0, "CocListMagentaGrey", { bg = "#192331", fg = "#e2b5e4" })
  hi(0, "CocListMagentaMagenta", { bg = "#e2b5e4", fg = "#e2b5e4" })
  hi(0, "CocListMagentaRed", { bg = "#f6b2bb", fg = "#e2b5e4" })
  hi(0, "CocListMagentaWhite", { bg = "#c3c7cd", fg = "#e2b5e4" })
  hi(0, "CocListMagentaYellow", { bg = "#d2c98c", fg = "#e2b5e4" })
  hi(0, "CocListRedBlack", { bg = "#192331", fg = "#f6b2bb" })
  hi(0, "CocListRedBlue", { bg = "#93d0f4", fg = "#f6b2bb" })
  hi(0, "CocListRedCyan", { bg = "#87d8d2", fg = "#f6b2bb" })
  hi(0, "CocListRedGreen", { bg = "#a7d5a7", fg = "#f6b2bb" })
  hi(0, "CocListRedGrey", { bg = "#192331", fg = "#f6b2bb" })
  hi(0, "CocListRedMagenta", { bg = "#e2b5e4", fg = "#f6b2bb" })
  hi(0, "CocListRedRed", { bg = "#f6b2bb", fg = "#f6b2bb" })
  hi(0, "CocListRedWhite", { bg = "#c3c7cd", fg = "#f6b2bb" })
  hi(0, "CocListRedYellow", { bg = "#d2c98c", fg = "#f6b2bb" })
  hi(0, "CocListWhiteBlack", { bg = "#192331", fg = "#c3c7cd" })
  hi(0, "CocListWhiteBlue", { bg = "#93d0f4", fg = "#c3c7cd" })
  hi(0, "CocListWhiteCyan", { bg = "#87d8d2", fg = "#c3c7cd" })
  hi(0, "CocListWhiteGreen", { bg = "#a7d5a7", fg = "#c3c7cd" })
  hi(0, "CocListWhiteGrey", { bg = "#192331", fg = "#c3c7cd" })
  hi(0, "CocListWhiteMagenta", { bg = "#e2b5e4", fg = "#c3c7cd" })
  hi(0, "CocListWhiteRed", { bg = "#f6b2bb", fg = "#c3c7cd" })
  hi(0, "CocListWhiteWhite", { bg = "#c3c7cd", fg = "#c3c7cd" })
  hi(0, "CocListWhiteYellow", { bg = "#d2c98c", fg = "#c3c7cd" })
  hi(0, "CocListYellowBlack", { bg = "#192331", fg = "#d2c98c" })
  hi(0, "CocListYellowBlue", { bg = "#93d0f4", fg = "#d2c98c" })
  hi(0, "CocListYellowCyan", { bg = "#87d8d2", fg = "#d2c98c" })
  hi(0, "CocListYellowGreen", { bg = "#a7d5a7", fg = "#d2c98c" })
  hi(0, "CocListYellowGrey", { bg = "#192331", fg = "#d2c98c" })
  hi(0, "CocListYellowMagenta", { bg = "#e2b5e4", fg = "#d2c98c" })
  hi(0, "CocListYellowRed", { bg = "#f6b2bb", fg = "#d2c98c" })
  hi(0, "CocListYellowWhite", { bg = "#c3c7cd", fg = "#d2c98c" })
  hi(0, "CocListYellowYellow", { bg = "#d2c98c", fg = "#d2c98c" })
  hi(0, "CocMarkdownLink", { fg = "#bcc2fb" })
  hi(0, "CocMenuSel", { bg = "#4c5767" })
  hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
  hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
  hi(0, "CocSearch", { fg = "#bcc2fb" })
  hi(0, "CocSelectedText", { fg = "#d2c98c" })
  hi(0, "CocStrikeThrough", { strikethrough = true })
  hi(0, "CocSymbolArray", { ctermfg = 223, fg = "#93d0f4" })
  hi(0, "CocSymbolBoolean", { ctermfg = 223, fg = "#e2b5e4" })
  hi(0, "CocSymbolClass", { ctermfg = 223, fg = "#87d8d2" })
  hi(0, "CocSymbolColor", { ctermfg = 223, fg = "#e2b5e4" })
  hi(0, "CocSymbolConstant", { ctermfg = 223, fg = "#e2b5e4" })
  hi(0, "CocSymbolConstructor", { ctermfg = 223, fg = "#87d8d2" })
  hi(0, "CocSymbolEnum", { ctermfg = 223, fg = "#c3c7cd" })
  hi(0, "CocSymbolEnumMember", { ctermfg = 223, fg = "#d2c98c" })
  hi(0, "CocSymbolEvent", { ctermfg = 223, fg = "#e2b5e4" })
  hi(0, "CocSymbolField", { ctermfg = 223, fg = "#d2c98c" })
  hi(0, "CocSymbolFile", { ctermfg = 223, fg = "#c3c7cd" })
  hi(0, "CocSymbolFolder", { ctermfg = 223, fg = "#93d0f4" })
  hi(0, "CocSymbolFunction", { ctermfg = 223, fg = "#93d0f4" })
  hi(0, "CocSymbolInterface", { ctermfg = 223, fg = "#c3c7cd" })
  hi(0, "CocSymbolKey", { ctermfg = 223, fg = "#d2c98c" })
  hi(0, "CocSymbolKeyword", { ctermfg = 223, fg = "#c3c7cd" })
  hi(0, "CocSymbolMethod", { ctermfg = 223, fg = "#93d0f4" })
  hi(0, "CocSymbolModule", { ctermfg = 223, fg = "#d2c98c" })
  hi(0, "CocSymbolNamespace", { ctermfg = 223, fg = "#d2c98c" })
  hi(0, "CocSymbolNull", { ctermfg = 223, fg = "#c3c7cd" })
  hi(0, "CocSymbolNumber", { ctermfg = 223, fg = "#e2b5e4" })
  hi(0, "CocSymbolObject", { ctermfg = 223, fg = "#93d0f4" })
  hi(0, "CocSymbolOperator", { ctermfg = 223, fg = "#c3c7cd" })
  hi(0, "CocSymbolPackage", { ctermfg = 223, fg = "#c3c7cd" })
  hi(0, "CocSymbolProperty", { ctermfg = 223, fg = "#d2c98c" })
  hi(0, "CocSymbolReference", { ctermfg = 223, fg = "#d2c98c" })
  hi(0, "CocSymbolSnippet", { ctermfg = 223, fg = "#93d0f4" })
  hi(0, "CocSymbolString", { ctermfg = 223, fg = "#a7d5a7" })
  hi(0, "CocSymbolStruct", { ctermfg = 223, fg = "#c3c7cd" })
  hi(0, "CocSymbolText", { ctermfg = 223, fg = "#93d0f4" })
  hi(0, "CocSymbolTypeParameter", { ctermfg = 223, fg = "#bcc2fb" })
  hi(0, "CocSymbolUnit", { ctermfg = 223, fg = "#93d0f4" })
  hi(0, "CocSymbolValue", { ctermfg = 223, fg = "#93d0f4" })
  hi(0, "CocSymbolVariable", { ctermfg = 223, fg = "#87d8d2" })
  hi(0, "CocUnderline", { sp = "#ebdbb2", underline = true })
  hi(0, "CocVirtualText", { ctermfg = 12, fg = "#504945" })
  hi(0, "ColorColumn", { bg = "#4c5767" })
  hi(0, "Comment", { fg = "#898c92" })
  hi(0, "Conceal", { fg = "#93d0f4" })
  hi(0, "Constant", { fg = "#e2b5e4" })
  hi(0, "CurSearch", { bg = "#d2c98c", fg = "#192331" })
  hi(0, "Cursor", { bg = "#c3c7cd", fg = "#192331" })
  hi(0, "CursorColumn", { bg = "#323c4c" })
  hi(0, "CursorLine", { bg = "#323c4c" })
  hi(0, "CursorLineFold", { fg = "#4c5767" })
  hi(0, "CursorLineNr", { bold = true, fg = "#a6c9fb" })
  hi(0, "CursorLineSign", { fg = "#4c5767" })
  hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#a7d5a7" })
  hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
  hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
  hi(0, "DapUIBreakpointsPath", { link = "Directory" })
  hi(0, "DapUIDecoration", { link = "Title" })
  hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
  hi(0, "DapUILineNumber", { link = "Title" })
  hi(0, "DapUIModifiedValue", { bold = true, fg = "#f0ba95" })
  hi(0, "DapUIScope", { link = "Title" })
  hi(0, "DapUISource", { link = "Directory" })
  hi(0, "DapUIStoppedThread", { link = "Title" })
  hi(0, "DapUIThread", { link = "String" })
  hi(0, "DapUIType", { link = "Type" })
  hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
  hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
  hi(0, "DapUIWatchesValue", { link = "String" })
  hi(0, "DashboardCenter", { link = "Delimiter" })
  hi(0, "DashboardFooter", { link = "Comment" })
  hi(0, "DashboardHeader", { link = "Title" })
  hi(0, "DashboardShortCut", { link = "WarningMsg" })
  hi(0, "Definitions", { fg = "#a7d5a7" })
  hi(0, "DefinitionsIcon", { fg = "#93d0f4" })
  hi(0, "Delimiter", { fg = "#f0ba95" })
  hi(0, "DiagnosticDeprecated", { sp = "#f6b2bb", strikethrough = true })
  hi(0, "DiagnosticError", { fg = "#f6b2bb" })
  hi(0, "DiagnosticFloatingError", { bg = "#0d1724", fg = "#f6b2bb" })
  hi(0, "DiagnosticFloatingHint", { bg = "#0d1724", fg = "#87d8d2" })
  hi(0, "DiagnosticFloatingInfo", { bg = "#0d1724", fg = "#bcc2fb" })
  hi(0, "DiagnosticFloatingOk", { bg = "#0d1724", fg = "#a7d5a7" })
  hi(0, "DiagnosticFloatingWarn", { bg = "#0d1724", fg = "#d2c98c" })
  hi(0, "DiagnosticHint", { fg = "#87d8d2" })
  hi(0, "DiagnosticInfo", { fg = "#bcc2fb" })
  hi(0, "DiagnosticOk", { fg = "#a7d5a7" })
  hi(0, "DiagnosticUnderlineError", { sp = "#f6b2bb", underline = true })
  hi(0, "DiagnosticUnderlineHint", { sp = "#87d8d2", underline = true })
  hi(0, "DiagnosticUnderlineInfo", { sp = "#bcc2fb", underline = true })
  hi(0, "DiagnosticUnderlineOk", { sp = "#a7d5a7", underline = true })
  hi(0, "DiagnosticUnderlineWarn", { sp = "#d2c98c", underline = true })
  hi(0, "DiagnosticWarn", { fg = "#d2c98c" })
  hi(0, "DiffAdd", { bg = "#002c06" })
  hi(0, "DiffChange", { bg = "#004c49" })
  hi(0, "DiffDelete", { bg = "#400c19" })
  hi(0, "DiffText", { bg = "#403700" })
  hi(0, "Directory", { fg = "#93d0f4" })
  hi(0, "EndOfBuffer", { fg = "#4c5767" })
  hi(0, "Error", { bg = "#400c19" })
  hi(0, "ErrorMsg", { fg = "#f6b2bb" })
  hi(0, "FinderParam", { fg = "#d2c98c" })
  hi(0, "FinderSpinner", { fg = "#a7d5a7" })
  hi(0, "FinderSpinnerBorder", { fg = "#a6c9fb" })
  hi(0, "FinderSpinnerTitle", { link = "Title" })
  hi(0, "FinderVirtText", { fg = "#f0ba95" })
  hi(0, "Float", { link = "Constant" })
  hi(0, "FloatBorder", { bg = "#0d1724", fg = "#a6c9fb" })
  hi(0, "FloatTitle", { bg = "#0d1724", bold = true, fg = "#a6c9fb" })
  hi(0, "FoldColumn", { fg = "#4c5767" })
  hi(0, "Folded", { bg = "#0d1724", fg = "#898c92" })
  hi(0, "Function", { fg = "#93d0f4" })
  hi(0, "GitSignsAdd", { fg = "#a7d5a7" })
  hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
  hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
  hi(0, "GitSignsChange", { fg = "#d2c98c" })
  hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
  hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
  hi(0, "GitSignsDelete", { fg = "#f6b2bb" })
  hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
  hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
  hi(0, "GitSignsUntracked", { fg = "#93d0f4" })
  hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
  hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
  hi(0, "HopNextKey", { bold = true, fg = "#a7d5a7", nocombine = true })
  hi(0, "HopNextKey1", { bold = true, fg = "#f0ba95", nocombine = true })
  hi(0, "HopNextKey2", { bold = true, fg = "#a6aab0", nocombine = true })
  hi(0, "HopPreview", { bold = true, fg = "#d2c98c", nocombine = true })
  hi(0, "HopUnmatched", { fg = "#4c5767" })
  hi(0, "HydraAmaranth", { fg = "#e2b5e4" })
  hi(0, "HydraBlue", { fg = "#93d0f4" })
  hi(0, "HydraHint", { link = "NormalFloat" })
  hi(0, "HydraPink", { fg = "#f0ba95" })
  hi(0, "HydraRed", { fg = "#f6b2bb" })
  hi(0, "HydraTeal", { fg = "#87d8d2" })
  hi(0, "Identifier", { fg = "#d2c98c" })
  hi(0, "Ignore", vim.empty_dict())
  hi(0, "IncSearch", { bg = "#d2c98c", fg = "#192331" })
  hi(0, "IndentBlanklineChar", { fg = "#4c5767", nocombine = true })
  hi(0, "IndentBlanklineContextChar", { fg = "#a6c9fb", nocombine = true })
  hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#a6c9fb", underline = true })
  hi(0, "IndentBlanklineIndent1", { fg = "#bcc2fb", nocombine = true })
  hi(0, "IndentBlanklineIndent2", { fg = "#87d8d2", nocombine = true })
  hi(0, "IndentBlanklineIndent3", { fg = "#d2c98c", nocombine = true })
  hi(0, "IndentBlanklineIndent4", { fg = "#f6b2bb", nocombine = true })
  hi(0, "IndentBlanklineIndent5", { fg = "#93d0f4", nocombine = true })
  hi(0, "IndentBlanklineIndent6", { fg = "#a7d5a7", nocombine = true })
  hi(0, "IndentBlanklineIndent7", { fg = "#f0ba95", nocombine = true })
  hi(0, "IndentBlanklineIndent8", { fg = "#e2b5e4", nocombine = true })
  hi(0, "Italic", { italic = true })
  hi(0, "LSOutlinePreviewBorder", { fg = "#a6c9fb" })
  hi(0, "LazyButton", { bg = "#323c4c" })
  hi(0, "LazyButtonActive", { bg = "#4c5767" })
  hi(0, "LazyDimmed", { link = "Comment" })
  hi(0, "LazyH1", { bg = "#4c5767", bold = true, fg = "#a6c9fb" })
  hi(0, "LeapBackdrop", { link = "Comment" })
  hi(0, "LeapLabel", { bold = true, fg = "#d2c98c", nocombine = true })
  hi(0, "LeapLabelSelected", { bold = true, fg = "#87d8d2", nocombine = true })
  hi(0, "LeapMatch", { bold = true, fg = "#a7d5a7", nocombine = true, underline = true })
  hi(0, "LineNr", { fg = "#4c5767" })
  hi(0, "LspCodeLens", { link = "Comment" })
  hi(0, "LspCodeLensSeparator", { link = "Comment" })
  hi(0, "LspReferenceText", { bg = "#4c5767" })
  hi(0, "LspSagaAutoPreview", { fg = "#bcc2fb" })
  hi(0, "LspSagaBorderTitle", { link = "FloatTitle" })
  hi(0, "LspSagaCodeActionBorder", { fg = "#a6c9fb" })
  hi(0, "LspSagaCodeActionContent", { fg = "#c3c7cd" })
  hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#93d0f4" })
  hi(0, "LspSagaDefPreviewBorder", { fg = "#a6c9fb" })
  hi(0, "LspSagaDiagnosticBorder", { fg = "#a6c9fb" })
  hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
  hi(0, "LspSagaDiagnosticSource", { fg = "#f0ba95" })
  hi(0, "LspSagaFinderSelection", { fg = "#87d8d2" })
  hi(0, "LspSagaHoverBorder", { fg = "#a6c9fb" })
  hi(0, "LspSagaLspFinderBorder", { fg = "#a6c9fb" })
  hi(0, "LspSagaRenameBorder", { fg = "#a6c9fb" })
  hi(0, "LspSagaSignatureHelpBorder", { fg = "#a6c9fb" })
  hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
  hi(0, "MasonError", { fg = "#f6b2bb" })
  hi(0, "MasonHeader", { bg = "#93d0f4", bold = true, fg = "#192331" })
  hi(0, "MasonHeaderSecondary", { bg = "#bcc2fb", bold = true, fg = "#192331" })
  hi(0, "MasonHeading", { link = "Bold" })
  hi(0, "MasonHighlight", { fg = "#a6c9fb" })
  hi(0, "MasonHighlightBlock", { bg = "#a6c9fb", fg = "#192331" })
  hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
  hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
  hi(0, "MasonHighlightBlockSecondary", { bg = "#93d0f4", fg = "#192331" })
  hi(0, "MasonHighlightSecondary", { fg = "#93d0f4" })
  hi(0, "MasonLink", { link = "MasonHighlight" })
  hi(0, "MasonMuted", { link = "Comment" })
  hi(0, "MasonMutedBlock", { bg = "#4c5767", fg = "#192331" })
  hi(0, "MasonMutedBlockBold", { bg = "#4c5767", bold = true, fg = "#192331" })
  hi(0, "MatchParen", { bg = "#4c5767", bold = true })
  hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
  hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
  hi(0, "MiniClueBorder", { link = "FloatBorder" })
  hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
  hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
  hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
  hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
  hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
  hi(0, "MiniClueTitle", { link = "FloatTitle" })
  hi(0, "MiniCompletionActiveParameter", { bg = "#4c5767" })
  hi(0, "MiniCursorword", { underline = true })
  hi(0, "MiniCursorwordCurrent", { underline = true })
  hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
  hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
  hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
  hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
  hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
  hi(0, "MiniDepsPlaceholder", { link = "Comment" })
  hi(0, "MiniDepsTitle", { link = "Title" })
  hi(0, "MiniDepsTitleError", { link = "DiffDelete" })
  hi(0, "MiniDepsTitleSame", { link = "DiffText" })
  hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
  hi(0, "MiniDiffOverAdd", { link = "DiffAdd" })
  hi(0, "MiniDiffOverChange", { link = "DiffText" })
  hi(0, "MiniDiffOverContext", { link = "DiffChange" })
  hi(0, "MiniDiffOverDelete", { link = "DiffDelete" })
  hi(0, "MiniDiffSignAdd", { link = "diffAdded" })
  hi(0, "MiniDiffSignChange", { link = "diffChanged" })
  hi(0, "MiniDiffSignDelete", { link = "diffRemoved" })
  hi(0, "MiniFilesBorder", { link = "FloatBorder" })
  hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
  hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
  hi(0, "MiniFilesDirectory", { link = "Directory" })
  hi(0, "MiniFilesFile", { fg = "#c3c7cd" })
  hi(0, "MiniFilesNormal", { link = "NormalFloat" })
  hi(0, "MiniFilesTitle", { link = "FloatTitle" })
  hi(0, "MiniFilesTitleFocused", { bg = "#0d1724", bold = true, fg = "#c3c7cd" })
  hi(0, "MiniHipatternsFixme", { bg = "#f6b2bb", bold = true, fg = "#192331" })
  hi(0, "MiniHipatternsHack", { bg = "#d2c98c", bold = true, fg = "#192331" })
  hi(0, "MiniHipatternsNote", { bg = "#87d8d2", bold = true, fg = "#192331" })
  hi(0, "MiniHipatternsTodo", { bg = "#bcc2fb", bold = true, fg = "#192331" })
  hi(0, "MiniIconsAzure", { fg = "#93d0f4" })
  hi(0, "MiniIconsBlue", { fg = "#bcc2fb" })
  hi(0, "MiniIconsCyan", { fg = "#87d8d2" })
  hi(0, "MiniIconsGreen", { fg = "#a7d5a7" })
  hi(0, "MiniIconsGrey", { fg = "#d5d9df" })
  hi(0, "MiniIconsOrange", { fg = "#f0ba95" })
  hi(0, "MiniIconsPurple", { fg = "#e2b5e4" })
  hi(0, "MiniIconsRed", { fg = "#f6b2bb" })
  hi(0, "MiniIconsYellow", { fg = "#d2c98c" })
  hi(0, "MiniIndentscopeSymbol", { fg = "#a6c9fb" })
  hi(0, "MiniIndentscopeSymbolOff", { fg = "#f6b2bb" })
  hi(0, "MiniJump", { sp = "#a6c9fb", undercurl = true })
  hi(0, "MiniJump2dDim", { fg = "#4c5767" })
  hi(0, "MiniJump2dSpot", { bg = "#020814", bold = true, fg = "#e8edf3", nocombine = true })
  hi(0, "MiniJump2dSpotAhead", { bg = "#020814", fg = "#d5d9df", nocombine = true })
  hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
  hi(0, "MiniMapNormal", { bg = "#0d1724", fg = "#898c92" })
  hi(0, "MiniMapSymbolCount", { fg = "#898c92" })
  hi(0, "MiniMapSymbolLine", { fg = "#a6c9fb" })
  hi(0, "MiniMapSymbolView", { fg = "#a6c9fb" })
  hi(0, "MiniNotifyBorder", { link = "FloatBorder" })
  hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
  hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
  hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
  hi(0, "MiniPickBorder", { link = "FloatBorder" })
  hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
  hi(0, "MiniPickBorderText", { link = "FloatTitle" })
  hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
  hi(0, "MiniPickIconDirectory", { link = "Directory" })
  hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
  hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
  hi(0, "MiniPickMatchMarked", { link = "Visual" })
  hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
  hi(0, "MiniPickNormal", { link = "NormalFloat" })
  hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
  hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
  hi(0, "MiniPickPrompt", { link = "DiagnosticFloatingInfo" })
  hi(0, "MiniStarterCurrent", { link = "MiniStarterItem" })
  hi(0, "MiniStarterFooter", { link = "Comment" })
  hi(0, "MiniStarterHeader", { bold = true, fg = "#a6c9fb" })
  hi(0, "MiniStarterInactive", { link = "Comment" })
  hi(0, "MiniStarterItemBullet", { fg = "#898c92" })
  hi(0, "MiniStarterItemPrefix", { bold = true, fg = "#d2c98c" })
  hi(0, "MiniStarterQuery", { bold = true, fg = "#a7d5a7" })
  hi(0, "MiniStarterSection", { fg = "#e2b5e4" })
  hi(0, "MiniStatuslineDevinfo", { bg = "#323c4c", fg = "#a6aab0" })
  hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
  hi(0, "MiniStatuslineFilename", { bg = "#192331", fg = "#a6aab0" })
  hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
  hi(0, "MiniStatuslineModeCommand", { bg = "#d2c98c", bold = true, fg = "#192331" })
  hi(0, "MiniStatuslineModeInsert", { bg = "#93d0f4", bold = true, fg = "#192331" })
  hi(0, "MiniStatuslineModeNormal", { bg = "#c3c7cd", bold = true, fg = "#192331" })
  hi(0, "MiniStatuslineModeOther", { bg = "#87d8d2", bold = true, fg = "#192331" })
  hi(0, "MiniStatuslineModeReplace", { bg = "#f6b2bb", bold = true, fg = "#192331" })
  hi(0, "MiniStatuslineModeVisual", { bg = "#a7d5a7", bold = true, fg = "#192331" })
  hi(0, "MiniSurround", { link = "IncSearch" })
  hi(0, "MiniTablineCurrent", { bg = "#192331", bold = true, fg = "#a6c9fb" })
  hi(0, "MiniTablineFill", { link = "MiniTablineHidden" })
  hi(0, "MiniTablineHidden", { bg = "#0d1724", fg = "#a6aab0" })
  hi(0, "MiniTablineModifiedCurrent", { bg = "#a6c9fb", bold = true, fg = "#192331" })
  hi(0, "MiniTablineModifiedHidden", { bg = "#a6aab0", fg = "#0d1724" })
  hi(0, "MiniTablineModifiedVisible", { bg = "#a6aab0", bold = true, fg = "#0d1724" })
  hi(0, "MiniTablineTabpagesection", { bg = "#a7d5a7", bold = true, fg = "#192331" })
  hi(0, "MiniTablineVisible", { bg = "#0d1724", bold = true, fg = "#a6aab0" })
  hi(0, "MiniTestEmphasis", { bold = true })
  hi(0, "MiniTestFail", { bold = true, fg = "#f6b2bb" })
  hi(0, "MiniTestPass", { bold = true, fg = "#a7d5a7" })
  hi(0, "MiniTrailspace", { bg = "#400c19" })
  hi(0, "ModeMsg", { fg = "#a7d5a7" })
  hi(0, "MoreMsg", { fg = "#93d0f4" })
  hi(0, "MsgArea", { link = "Normal" })
  hi(0, "MsgSeparator", { bg = "#4c5767", fg = "#898c92" })
  hi(0, "NeoTreeDimText", { fg = "#4c5767" })
  hi(0, "NeoTreeDotfile", { fg = "#a6aab0" })
  hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
  hi(0, "NeoTreeFadeText2", { fg = "#4c5767" })
  hi(0, "NeoTreeGitAdded", { fg = "#a7d5a7" })
  hi(0, "NeoTreeGitConflict", { bold = true, fg = "#f0ba95" })
  hi(0, "NeoTreeGitDeleted", { fg = "#f6b2bb" })
  hi(0, "NeoTreeGitModified", { fg = "#d2c98c" })
  hi(0, "NeoTreeGitUnstaged", { fg = "#e2b5e4" })
  hi(0, "NeoTreeGitUntracked", { fg = "#87d8d2" })
  hi(0, "NeoTreeMessage", { bg = "#323c4c", fg = "#c3c7cd" })
  hi(0, "NeoTreeModified", { fg = "#d5d9df" })
  hi(0, "NeoTreeRootName", { bold = true, fg = "#a6c9fb" })
  hi(0, "NeoTreeTabInactive", { fg = "#898c92" })
  hi(0, "NeoTreeTabSeparatorActive", { bg = "#4c5767", fg = "#898c92" })
  hi(0, "NeoTreeTabSeparatorInactive", { bg = "#323c4c", fg = "#323c4c" })
  hi(0, "NeogitCommitViewHeader", { link = "Special" })
  hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
  hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
  hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
  hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
  hi(0, "NeogitFold", { link = "FoldColumn" })
  hi(0, "NeogitHunkHeader", { fg = "#a6c9fb" })
  hi(0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#a6c9fb" })
  hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
  hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
  hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
  hi(0, "NoiceCmdlinePopupBorder", { fg = "#93d0f4" })
  hi(0, "NoiceConfirmBorder", { fg = "#d2c98c" })
  hi(0, "NonText", { fg = "#4c5767" })
  hi(0, "Normal", { bg = "#192331", fg = "#c3c7cd" })
  hi(0, "NormalFloat", { bg = "#0d1724", fg = "#c3c7cd" })
  hi(0, "NormalNC", { link = "Normal" })
  hi(0, "NotifyDEBUGBorder", { fg = "#a7d5a7" })
  hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
  hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
  hi(0, "NotifyERRORBorder", { fg = "#f6b2bb" })
  hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
  hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
  hi(0, "NotifyINFOBorder", { fg = "#bcc2fb" })
  hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
  hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
  hi(0, "NotifyTRACEBorder", { fg = "#87d8d2" })
  hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
  hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
  hi(0, "NotifyWARNBorder", { fg = "#d2c98c" })
  hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
  hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
  hi(0, "NvimTreeExecFile", { bold = true, fg = "#a7d5a7" })
  hi(0, "NvimTreeFolderIcon", { fg = "#898c92" })
  hi(0, "NvimTreeGitDeleted", { fg = "#f6b2bb" })
  hi(0, "NvimTreeGitDirty", { fg = "#d2c98c" })
  hi(0, "NvimTreeGitMerge", { fg = "#f0ba95" })
  hi(0, "NvimTreeGitNew", { fg = "#87d8d2" })
  hi(0, "NvimTreeGitRenamed", { fg = "#e2b5e4" })
  hi(0, "NvimTreeGitStaged", { fg = "#a7d5a7" })
  hi(0, "NvimTreeImageFile", { fg = "#f0ba95" })
  hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
  hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
  hi(0, "NvimTreeRootFolder", { bold = true, fg = "#a6c9fb" })
  hi(0, "NvimTreeSpecialFile", { fg = "#a6c9fb", underline = true })
  hi(0, "NvimTreeSymlink", { bold = true, fg = "#bcc2fb" })
  hi(0, "NvimTreeWindowPicker", { bg = "#4c5767", bold = true, fg = "#c3c7cd" })
  hi(0, "Operator", { fg = "#c3c7cd" })
  hi(0, "OutlineDetail", { fg = "#4c5767" })
  hi(0, "OutlineFoldPrefix", { fg = "#d2c98c" })
  hi(0, "OutlineIndentEvn", { fg = "#898c92" })
  hi(0, "OutlineIndentOdd", { fg = "#c3c7cd" })
  hi(0, "Pmenu", { bg = "#323c4c", fg = "#c3c7cd" })
  hi(0, "PmenuSel", { bg = "#c3c7cd", blend = 0, fg = "#192331" })
  hi(0, "PmenuThumb", { bg = "#4c5767" })
  hi(0, "PounceAccept", { bg = "#d2c98c", bold = true, fg = "#192331", nocombine = true })
  hi(0, "PounceAcceptBest", { bg = "#a7d5a7", bold = true, fg = "#192331", nocombine = true })
  hi(0, "PounceGap", { bg = "#4c5767", bold = true, fg = "#192331", nocombine = true })
  hi(0, "PounceMatch", { bg = "#c3c7cd", bold = true, fg = "#192331", nocombine = true })
  hi(0, "PreProc", { fg = "#bcc2fb" })
  hi(0, "Question", { fg = "#93d0f4" })
  hi(0, "QuickFixLine", { bold = true })
  hi(0, "RainbowDelimiterBlue", { fg = "#93d0f4" })
  hi(0, "RainbowDelimiterCyan", { fg = "#87d8d2" })
  hi(0, "RainbowDelimiterGreen", { fg = "#a7d5a7" })
  hi(0, "RainbowDelimiterOrange", { fg = "#f0ba95" })
  hi(0, "RainbowDelimiterRed", { fg = "#f6b2bb" })
  hi(0, "RainbowDelimiterViolet", { fg = "#e2b5e4" })
  hi(0, "RainbowDelimiterYellow", { fg = "#d2c98c" })
  hi(0, "References", { fg = "#a7d5a7" })
  hi(0, "ReferencesIcon", { fg = "#93d0f4" })
  hi(0, "Removed", { fg = "#f6b2bb" })
  hi(0, "Search", { bg = "#a6c9fb", fg = "#192331" })
  hi(0, "SignColumn", { fg = "#4c5767" })
  hi(0, "Sneak", { bg = "#f0ba95", fg = "#192331" })
  hi(0, "SneakLabel", { bg = "#f0ba95", bold = true, fg = "#192331" })
  hi(0, "SneakScope", { bg = "#e8edf3", fg = "#192331" })
  hi(0, "Special", { fg = "#87d8d2" })
  hi(0, "SpecialKey", { fg = "#4c5767" })
  hi(0, "SpellBad", { sp = "#f6b2bb", undercurl = true })
  hi(0, "SpellCap", { sp = "#87d8d2", undercurl = true })
  hi(0, "SpellLocal", { sp = "#d2c98c", undercurl = true })
  hi(0, "SpellRare", { sp = "#bcc2fb", undercurl = true })
  hi(0, "Statement", { bold = true, fg = "#c3c7cd" })
  hi(0, "StatusLine", { bg = "#192331", fg = "#a6aab0" })
  hi(0, "StatusLineNC", { bg = "#0d1724", fg = "#a6aab0" })
  hi(0, "String", { fg = "#a7d5a7" })
  hi(0, "Substitute", { bg = "#bcc2fb", fg = "#192331" })
  hi(0, "TabLine", { bg = "#0d1724", fg = "#a6aab0" })
  hi(0, "TabLineSel", { bg = "#0d1724", fg = "#a6c9fb" })
  hi(0, "TargetFileName", { fg = "#c3c7cd" })
  hi(0, "TelescopeBorder", { fg = "#a6c9fb" })
  hi(0, "TelescopeMatching", { bold = true })
  hi(0, "TelescopeMultiSelection", { bg = "#4c5767" })
  hi(0, "TelescopeSelection", { bg = "#323c4c" })
  hi(0, "TermCursorNC", { reverse = true })
  hi(0, "Title", { fg = "#a6c9fb" })
  hi(0, "Todo", { bg = "#192331", bold = true, fg = "#a6c9fb" })
  hi(0, "TroubleCount", { bold = true, fg = "#a6c9fb" })
  hi(0, "TroubleFoldIcon", { bold = true, fg = "#a6c9fb" })
  hi(0, "TroubleIndent", { fg = "#4c5767" })
  hi(0, "TroubleLocation", { fg = "#a6aab0" })
  hi(0, "TroubleSignError", { link = "DiagnosticError" })
  hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
  hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
  hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
  hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
  hi(0, "TroubleText", { fg = "#c3c7cd" })
  hi(0, "TroubleTextError", { link = "TroubleText" })
  hi(0, "TroubleTextHint", { link = "TroubleText" })
  hi(0, "TroubleTextInformation", { link = "TroubleText" })
  hi(0, "TroubleTextWarning", { link = "TroubleText" })
  hi(0, "Type", { fg = "#c3c7cd" })
  hi(0, "VertSplit", { fg = "#a6c9fb" })
  hi(0, "Visual", { bg = "#4c5767" })
  hi(0, "VisualNOS", { bg = "#323c4c" })
  hi(0, "WarningMsg", { fg = "#d2c98c" })
  hi(0, "WhichKey", { fg = "#87d8d2" })
  hi(0, "WhichKeyBorder", { link = "FloatBorder" })
  hi(0, "WhichKeyDesc", { fg = "#c3c7cd" })
  hi(0, "WhichKeyFloat", { bg = "#0d1724", fg = "#c3c7cd" })
  hi(0, "WhichKeyGroup", { fg = "#f6b2bb" })
  hi(0, "WhichKeyIconAzure", { link = "MiniIconsAzure" })
  hi(0, "WhichKeyIconBlue", { link = "MiniIconsBlue" })
  hi(0, "WhichKeyIconCyan", { link = "MiniIconsCyan" })
  hi(0, "WhichKeyIconGreen", { link = "MiniIconsGreen" })
  hi(0, "WhichKeyIconGrey", { link = "MiniIconsGrey" })
  hi(0, "WhichKeyIconOrange", { link = "MiniIconsOrange" })
  hi(0, "WhichKeyIconPurple", { link = "MiniIconsPurple" })
  hi(0, "WhichKeyIconRed", { link = "MiniIconsRed" })
  hi(0, "WhichKeyIconYellow", { link = "MiniIconsYellow" })
  hi(0, "WhichKeySeparator", { fg = "#a7d5a7" })
  hi(0, "WhichKeyValue", { link = "Comment" })
  hi(0, "Whitespace", { fg = "#4c5767" })
  hi(0, "WinBar", { link = "StatusLine" })
  hi(0, "WinBarNC", { link = "StatusLineNC" })
  hi(0, "WinSeparator", { fg = "#a6c9fb" })
  hi(0, "diffAdded", { fg = "#a7d5a7" })
  hi(0, "diffChanged", { fg = "#87d8d2" })
  hi(0, "diffFile", { fg = "#d2c98c" })
  hi(0, "diffLine", { fg = "#bcc2fb" })
  hi(0, "diffRemoved", { fg = "#f6b2bb" })
  hi(0, "gitcommitBranch", { bold = true, fg = "#f0ba95" })
  hi(0, "gitcommitComment", { link = "Comment" })
  hi(0, "gitcommitDiscarded", { link = "Comment" })
  hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#d2c98c" })
  hi(0, "gitcommitDiscardedType", { fg = "#93d0f4" })
  hi(0, "gitcommitHeader", { link = "Title" })
  hi(0, "gitcommitOverflow", { fg = "#d2c98c" })
  hi(0, "gitcommitSelected", { link = "Comment" })
  hi(0, "gitcommitSelectedFile", { bold = true, fg = "#a7d5a7" })
  hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
  hi(0, "gitcommitSummary", { fg = "#a7d5a7" })
  hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
  hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
  hi(0, "gitcommitUntracked", { link = "Comment" })
  hi(0, "gitcommitUntrackedFile", { fg = "#87d8d2" })
  hi(0, "lCursor", { bg = "#c3c7cd", fg = "#192331" })

  -- Terminal colors
  local g = vim.g

  g.terminal_color_0 = "#192331"
  g.terminal_color_1 = "#f6b2bb"
  g.terminal_color_2 = "#a7d5a7"
  g.terminal_color_3 = "#d2c98c"
  g.terminal_color_4 = "#93d0f4"
  g.terminal_color_5 = "#e2b5e4"
  g.terminal_color_6 = "#87d8d2"
  g.terminal_color_7 = "#c3c7cd"
  g.terminal_color_8 = "#192331"
  g.terminal_color_9 = "#f6b2bb"
  g.terminal_color_10 = "#a7d5a7"
  g.terminal_color_11 = "#d2c98c"
  g.terminal_color_12 = "#93d0f4"
  g.terminal_color_13 = "#e2b5e4"
  g.terminal_color_14 = "#87d8d2"
  g.terminal_color_15 = "#c3c7cd"
end

if vim.o.background == "light" then
  hi(0, "@character.special", { link = "SpecialChar" })
  hi(0, "@comment.documentation", { link = "@comment" })
  hi(0, "@comment.error", { link = "@text.danger" })
  hi(0, "@comment.note", { link = "@text.note" })
  hi(0, "@comment.todo", { link = "@text.todo" })
  hi(0, "@comment.warning", { link = "@text.warning" })
  hi(0, "@conditional", { link = "Conditional" })
  hi(0, "@constant.builtin", { link = "Special" })
  hi(0, "@constant.macro", { link = "Macro" })
  hi(0, "@debug", { link = "Debug" })
  hi(0, "@define", { link = "Define" })
  hi(0, "@diff.delta", { link = "diffChanged" })
  hi(0, "@diff.minus", { link = "diffRemoved" })
  hi(0, "@diff.plus", { link = "diffAdded" })
  hi(0, "@exception", { link = "Exception" })
  hi(0, "@field", { link = "Identifier" })
  hi(0, "@float", { link = "Float" })
  hi(0, "@function.builtin", { link = "Special" })
  hi(0, "@function.call", { link = "Function" })
  hi(0, "@function.macro", { link = "Macro" })
  hi(0, "@function.method", { link = "@method" })
  hi(0, "@function.method.call", { link = "@method.call" })
  hi(0, "@include", { link = "Include" })
  hi(0, "@keyword.conditional", { link = "@keyword" })
  hi(0, "@keyword.conditional.ternary", { link = "Keyword" })
  hi(0, "@keyword.coroutine", { link = "@keyword" })
  hi(0, "@keyword.debug", { bold = true, fg = "#006f44" })
  hi(0, "@keyword.directive", { bold = true, fg = "#004d84" })
  hi(0, "@keyword.directive.define", { link = "@keyword.directive" })
  hi(0, "@keyword.exception", { link = "@keyword" })
  hi(0, "@keyword.function", { link = "@keyword" })
  hi(0, "@keyword.import", { bold = true, fg = "#004d84" })
  hi(0, "@keyword.operator", { link = "@keyword" })
  hi(0, "@keyword.repeat", { link = "@keyword" })
  hi(0, "@keyword.return", { bold = true, fg = "#700011" })
  hi(0, "@keyword.storage", { bold = true, fg = "#2c2e33" })
  hi(0, "@lsp.mod.defaultLibrary", { link = "Special" })
  hi(0, "@lsp.mod.deprecated", { fg = "#61004f" })
  hi(0, "@lsp.type.class", { link = "@structure" })
  hi(0, "@lsp.type.decorator", { link = "@function" })
  hi(0, "@lsp.type.enum", { link = "@type" })
  hi(0, "@lsp.type.enumMember", { link = "@constant" })
  hi(0, "@lsp.type.function", { link = "@function" })
  hi(0, "@lsp.type.interface", { link = "@type" })
  hi(0, "@lsp.type.macro", { link = "@macro" })
  hi(0, "@lsp.type.method", { link = "@method" })
  hi(0, "@lsp.type.namespace", { link = "@namespace" })
  hi(0, "@lsp.type.parameter", { link = "@parameter" })
  hi(0, "@lsp.type.property", { link = "@property" })
  hi(0, "@lsp.type.struct", { link = "@structure" })
  hi(0, "@lsp.type.type", { link = "@type" })
  hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
  hi(0, "@lsp.type.variable", { link = "@variable" })
  hi(0, "@macro", { link = "Macro" })
  hi(0, "@markup.environment", { link = "@module" })
  hi(0, "@markup.heading", { link = "@text.title" })
  hi(0, "@markup.italic", { link = "@text.emphasis" })
  hi(0, "@markup.link", { link = "@text.reference" })
  hi(0, "@markup.link.label", { link = "@markup.link" })
  hi(0, "@markup.link.url", { fg = "#2c2e33", underline = true })
  hi(0, "@markup.list", { link = "@punctuation.special" })
  hi(0, "@markup.list.checked", { link = "DiagnosticOk" })
  hi(0, "@markup.list.unchecked", { link = "DiagnosticWarn" })
  hi(0, "@markup.math", { link = "@string.special" })
  hi(0, "@markup.quote", { link = "@string.special" })
  hi(0, "@markup.raw", { link = "@text.literal" })
  hi(0, "@markup.raw.block", { link = "@markup.raw" })
  hi(0, "@markup.strikethrough", { link = "@text.strike" })
  hi(0, "@markup.strong", { link = "@text.strong" })
  hi(0, "@markup.underline", { link = "@text.underline" })
  hi(0, "@method", { link = "Function" })
  hi(0, "@method.call", { link = "Function" })
  hi(0, "@module", { link = "@namespace" })
  hi(0, "@module.builtin", { link = "@variable.builtin" })
  hi(0, "@namespace", { link = "Identifier" })
  hi(0, "@none", { link = "Normal" })
  hi(0, "@number.float", { link = "@float" })
  hi(0, "@parameter", { fg = "#004d84" })
  hi(0, "@preproc", { link = "PreProc" })
  hi(0, "@punctuation.bracket", { link = "@punctuation" })
  hi(0, "@punctuation.delimiter", { link = "@punctuation" })
  hi(0, "@punctuation.special", { link = "Special" })
  hi(0, "@repeat", { link = "Repeat" })
  hi(0, "@storageclass", { link = "StorageClass" })
  hi(0, "@string.documentation", { link = "@string" })
  hi(0, "@string.escape", { link = "SpecialChar" })
  hi(0, "@string.regexp", { link = "SpecialChar" })
  hi(0, "@string.special", { link = "SpecialChar" })
  hi(0, "@string.special.path", { link = "Directory" })
  hi(0, "@string.special.symbol", { link = "@constant" })
  hi(0, "@string.special.url", { link = "@markup.link.url" })
  hi(0, "@string.special.vimdoc", { link = "@constant" })
  hi(0, "@structure", { link = "Structure" })
  hi(0, "@symbol", { link = "Keyword" })
  hi(0, "@tag.attribute", { link = "@tag" })
  hi(0, "@tag.delimiter", { link = "@punctuation" })
  hi(0, "@text.danger", { link = "ErrorMsg" })
  hi(0, "@text.emphasis", { italic = true })
  hi(0, "@text.literal", { link = "Special" })
  hi(0, "@text.note", { link = "MoreMsg" })
  hi(0, "@text.reference", { link = "Identifier" })
  hi(0, "@text.strike", { strikethrough = true })
  hi(0, "@text.strong", { bold = true })
  hi(0, "@text.title", { link = "Title" })
  hi(0, "@text.todo", { link = "Todo" })
  hi(0, "@text.underline", { link = "Underlined" })
  hi(0, "@text.uri", { link = "Underlined" })
  hi(0, "@text.warning", { link = "WarningMsg" })
  hi(0, "@type.builtin", { link = "Special" })
  hi(0, "@type.definition", { link = "Typedef" })
  hi(0, "@type.qualifier", { link = "StorageClass" })
  hi(0, "@variable", { fg = "#2c2e33" })
  hi(0, "@variable.builtin", { link = "Special" })
  hi(0, "@variable.member", { link = "@field" })
  hi(0, "@variable.parameter", { link = "@parameter" })
  hi(0, "Added", { fg = "#636900" })
  hi(0, "Beacon", { bg = "#0b0d11" })
  hi(0, "Bold", { bold = true })
  hi(0, "BufferCurrent", { bg = "#e0e2e9", bold = true, fg = "#1c177c" })
  hi(0, "BufferCurrentIcon", { bg = "#e0e2e9" })
  hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
  hi(0, "BufferCurrentMod", { bg = "#c0c2c9", bold = true, fg = "#1c177c" })
  hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
  hi(0, "BufferCurrentTarget", { bg = "#a0a2a8", bold = true, fg = "#1c177c" })
  hi(0, "BufferInactive", { bg = "#e9ebf3", fg = "#2c2e33" })
  hi(0, "BufferInactiveIcon", { bg = "#e9ebf3" })
  hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
  hi(0, "BufferInactiveMod", { bg = "#c0c2c9", fg = "#2c2e33" })
  hi(0, "BufferInactiveSign", { link = "BufferInactive" })
  hi(0, "BufferInactiveTarget", { bg = "#a0a2a8", fg = "#2c2e33" })
  hi(0, "BufferLineBuffer", { fg = "#64666c" })
  hi(0, "BufferLineBufferSelected", { bold = true, fg = "#2c2e33" })
  hi(0, "BufferLineBufferVisible", { fg = "#2c2e33" })
  hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
  hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
  hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
  hi(0, "BufferLineFill", { link = "Normal" })
  hi(0, "BufferLineTab", { bg = "#636900", fg = "#e0e2e9" })
  hi(0, "BufferLineTabSelected", { bg = "#636900", bold = true, fg = "#e0e2e9" })
  hi(0, "BufferOffset", { link = "Normal" })
  hi(0, "BufferTabpageFill", { link = "Normal" })
  hi(0, "BufferTabpages", { bg = "#636900", bold = true, fg = "#e0e2e9" })
  hi(0, "BufferVisible", { bg = "#e0e2e9", bold = true, fg = "#2c2e33" })
  hi(0, "BufferVisibleIcon", { bg = "#e0e2e9" })
  hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
  hi(0, "BufferVisibleMod", { bg = "#c0c2c9", bold = true, fg = "#2c2e33" })
  hi(0, "BufferVisibleSign", { link = "BufferVisible" })
  hi(0, "BufferVisibleTarget", { bg = "#a0a2a8", bold = true, fg = "#2c2e33" })
  hi(0, "Changed", { fg = "#006f44" })
  hi(0, "CmpItemAbbr", { fg = "#2c2e33" })
  hi(0, "CmpItemAbbrDeprecated", { link = "Comment" })
  hi(0, "CmpItemAbbrMatch", { bold = true })
  hi(0, "CmpItemAbbrMatchFuzzy", { bold = true })
  hi(0, "CmpItemKind", { fg = "#2c2e33" })
  hi(0, "CmpItemKindClass", { link = "Type" })
  hi(0, "CmpItemKindColor", { link = "Special" })
  hi(0, "CmpItemKindConstant", { link = "Constant" })
  hi(0, "CmpItemKindConstructor", { link = "Type" })
  hi(0, "CmpItemKindEnum", { link = "Structure" })
  hi(0, "CmpItemKindEnumMember", { link = "Structure" })
  hi(0, "CmpItemKindEvent", { link = "Exception" })
  hi(0, "CmpItemKindField", { link = "Structure" })
  hi(0, "CmpItemKindFile", { link = "Tag" })
  hi(0, "CmpItemKindFolder", { link = "Directory" })
  hi(0, "CmpItemKindFunction", { link = "Function" })
  hi(0, "CmpItemKindInterface", { link = "Structure" })
  hi(0, "CmpItemKindKeyword", { link = "Keyword" })
  hi(0, "CmpItemKindMethod", { link = "Function" })
  hi(0, "CmpItemKindModule", { link = "Structure" })
  hi(0, "CmpItemKindOperator", { link = "Operator" })
  hi(0, "CmpItemKindProperty", { link = "Structure" })
  hi(0, "CmpItemKindReference", { link = "Tag" })
  hi(0, "CmpItemKindSnippet", { link = "Special" })
  hi(0, "CmpItemKindStruct", { link = "Structure" })
  hi(0, "CmpItemKindText", { link = "Normal" })
  hi(0, "CmpItemKindTypeParameter", { link = "Type" })
  hi(0, "CmpItemKindUnit", { link = "Special" })
  hi(0, "CmpItemKindValue", { link = "Identifier" })
  hi(0, "CmpItemKindVariable", { link = "Delimiter" })
  hi(0, "CmpItemMenu", { fg = "#2c2e33" })
  hi(0, "CocBold", { bold = true })
  hi(0, "CocCodeLens", { link = "LspCodeLens" })
  hi(0, "CocCursorTransparent", { blend = 100, strikethrough = true })
  hi(0, "CocDisabled", { link = "Comment" })
  hi(0, "CocFadeOut", { link = "Comment" })
  hi(0, "CocInlayHint", { ctermfg = 22, fg = "#006f44" })
  hi(0, "CocItalic", { italic = true })
  hi(0, "CocLink", { sp = "#15aabf", underline = true })
  hi(0, "CocListBgBlack", { bg = "#e0e2e9", ctermbg = 0 })
  hi(0, "CocListBgBlue", { bg = "#007e87", ctermbg = 12 })
  hi(0, "CocListBgCyan", { bg = "#006f44", ctermbg = 14 })
  hi(0, "CocListBgGreen", { bg = "#636900", ctermbg = 10 })
  hi(0, "CocListBgGrey", { bg = "#e0e2e9", ctermbg = 248 })
  hi(0, "CocListBgMagenta", { bg = "#370674", ctermbg = 13 })
  hi(0, "CocListBgRed", { bg = "#61004f", ctermbg = 9 })
  hi(0, "CocListBgWhite", { bg = "#2c2e33", ctermbg = 15 })
  hi(0, "CocListBgYellow", { bg = "#804e00", ctermbg = 11 })
  hi(0, "CocListBlackBlack", { bg = "#e0e2e9", fg = "#e0e2e9" })
  hi(0, "CocListBlackBlue", { bg = "#007e87", fg = "#e0e2e9" })
  hi(0, "CocListBlackCyan", { bg = "#006f44", fg = "#e0e2e9" })
  hi(0, "CocListBlackGreen", { bg = "#636900", fg = "#e0e2e9" })
  hi(0, "CocListBlackGrey", { bg = "#e0e2e9", fg = "#e0e2e9" })
  hi(0, "CocListBlackMagenta", { bg = "#370674", fg = "#e0e2e9" })
  hi(0, "CocListBlackRed", { bg = "#61004f", fg = "#e0e2e9" })
  hi(0, "CocListBlackWhite", { bg = "#2c2e33", fg = "#e0e2e9" })
  hi(0, "CocListBlackYellow", { bg = "#804e00", fg = "#e0e2e9" })
  hi(0, "CocListBlueBlack", { bg = "#e0e2e9", fg = "#007e87" })
  hi(0, "CocListBlueBlue", { bg = "#007e87", fg = "#007e87" })
  hi(0, "CocListBlueCyan", { bg = "#006f44", fg = "#007e87" })
  hi(0, "CocListBlueGreen", { bg = "#636900", fg = "#007e87" })
  hi(0, "CocListBlueGrey", { bg = "#e0e2e9", fg = "#007e87" })
  hi(0, "CocListBlueMagenta", { bg = "#370674", fg = "#007e87" })
  hi(0, "CocListBlueRed", { bg = "#61004f", fg = "#007e87" })
  hi(0, "CocListBlueWhite", { bg = "#2c2e33", fg = "#007e87" })
  hi(0, "CocListBlueYellow", { bg = "#804e00", fg = "#007e87" })
  hi(0, "CocListCyanBlack", { bg = "#e0e2e9", fg = "#006f44" })
  hi(0, "CocListCyanBlue", { bg = "#007e87", fg = "#006f44" })
  hi(0, "CocListCyanCyan", { bg = "#006f44", fg = "#006f44" })
  hi(0, "CocListCyanGreen", { bg = "#636900", fg = "#006f44" })
  hi(0, "CocListCyanGrey", { bg = "#e0e2e9", fg = "#006f44" })
  hi(0, "CocListCyanMagenta", { bg = "#370674", fg = "#006f44" })
  hi(0, "CocListCyanRed", { bg = "#61004f", fg = "#006f44" })
  hi(0, "CocListCyanWhite", { bg = "#2c2e33", fg = "#006f44" })
  hi(0, "CocListCyanYellow", { bg = "#804e00", fg = "#006f44" })
  hi(0, "CocListFgBlack", { ctermfg = 0, fg = "#e0e2e9" })
  hi(0, "CocListFgBlue", { ctermfg = 12, fg = "#007e87" })
  hi(0, "CocListFgCyan", { ctermfg = 14, fg = "#006f44" })
  hi(0, "CocListFgGreen", { ctermfg = 10, fg = "#636900" })
  hi(0, "CocListFgGrey", { ctermfg = 248, fg = "#e0e2e9" })
  hi(0, "CocListFgMagenta", { ctermfg = 13, fg = "#370674" })
  hi(0, "CocListFgRed", { ctermfg = 9, fg = "#61004f" })
  hi(0, "CocListFgWhite", { ctermfg = 15, fg = "#2c2e33" })
  hi(0, "CocListFgYellow", { ctermfg = 11, fg = "#804e00" })
  hi(0, "CocListGreenBlack", { bg = "#e0e2e9", fg = "#636900" })
  hi(0, "CocListGreenBlue", { bg = "#007e87", fg = "#636900" })
  hi(0, "CocListGreenCyan", { bg = "#006f44", fg = "#636900" })
  hi(0, "CocListGreenGreen", { bg = "#636900", fg = "#636900" })
  hi(0, "CocListGreenGrey", { bg = "#e0e2e9", fg = "#636900" })
  hi(0, "CocListGreenMagenta", { bg = "#370674", fg = "#636900" })
  hi(0, "CocListGreenRed", { bg = "#61004f", fg = "#636900" })
  hi(0, "CocListGreenWhite", { bg = "#2c2e33", fg = "#636900" })
  hi(0, "CocListGreenYellow", { bg = "#804e00", fg = "#636900" })
  hi(0, "CocListGreyBlack", { bg = "#e0e2e9", fg = "#e0e2e9" })
  hi(0, "CocListGreyBlue", { bg = "#007e87", fg = "#e0e2e9" })
  hi(0, "CocListGreyCyan", { bg = "#006f44", fg = "#e0e2e9" })
  hi(0, "CocListGreyGreen", { bg = "#636900", fg = "#e0e2e9" })
  hi(0, "CocListGreyGrey", { bg = "#e0e2e9", fg = "#e0e2e9" })
  hi(0, "CocListGreyMagenta", { bg = "#370674", fg = "#e0e2e9" })
  hi(0, "CocListGreyRed", { bg = "#61004f", fg = "#e0e2e9" })
  hi(0, "CocListGreyWhite", { bg = "#2c2e33", fg = "#e0e2e9" })
  hi(0, "CocListGreyYellow", { bg = "#804e00", fg = "#e0e2e9" })
  hi(0, "CocListMagentaBlack", { bg = "#e0e2e9", fg = "#370674" })
  hi(0, "CocListMagentaBlue", { bg = "#007e87", fg = "#370674" })
  hi(0, "CocListMagentaCyan", { bg = "#006f44", fg = "#370674" })
  hi(0, "CocListMagentaGreen", { bg = "#636900", fg = "#370674" })
  hi(0, "CocListMagentaGrey", { bg = "#e0e2e9", fg = "#370674" })
  hi(0, "CocListMagentaMagenta", { bg = "#370674", fg = "#370674" })
  hi(0, "CocListMagentaRed", { bg = "#61004f", fg = "#370674" })
  hi(0, "CocListMagentaWhite", { bg = "#2c2e33", fg = "#370674" })
  hi(0, "CocListMagentaYellow", { bg = "#804e00", fg = "#370674" })
  hi(0, "CocListRedBlack", { bg = "#e0e2e9", fg = "#61004f" })
  hi(0, "CocListRedBlue", { bg = "#007e87", fg = "#61004f" })
  hi(0, "CocListRedCyan", { bg = "#006f44", fg = "#61004f" })
  hi(0, "CocListRedGreen", { bg = "#636900", fg = "#61004f" })
  hi(0, "CocListRedGrey", { bg = "#e0e2e9", fg = "#61004f" })
  hi(0, "CocListRedMagenta", { bg = "#370674", fg = "#61004f" })
  hi(0, "CocListRedRed", { bg = "#61004f", fg = "#61004f" })
  hi(0, "CocListRedWhite", { bg = "#2c2e33", fg = "#61004f" })
  hi(0, "CocListRedYellow", { bg = "#804e00", fg = "#61004f" })
  hi(0, "CocListWhiteBlack", { bg = "#e0e2e9", fg = "#2c2e33" })
  hi(0, "CocListWhiteBlue", { bg = "#007e87", fg = "#2c2e33" })
  hi(0, "CocListWhiteCyan", { bg = "#006f44", fg = "#2c2e33" })
  hi(0, "CocListWhiteGreen", { bg = "#636900", fg = "#2c2e33" })
  hi(0, "CocListWhiteGrey", { bg = "#e0e2e9", fg = "#2c2e33" })
  hi(0, "CocListWhiteMagenta", { bg = "#370674", fg = "#2c2e33" })
  hi(0, "CocListWhiteRed", { bg = "#61004f", fg = "#2c2e33" })
  hi(0, "CocListWhiteWhite", { bg = "#2c2e33", fg = "#2c2e33" })
  hi(0, "CocListWhiteYellow", { bg = "#804e00", fg = "#2c2e33" })
  hi(0, "CocListYellowBlack", { bg = "#e0e2e9", fg = "#804e00" })
  hi(0, "CocListYellowBlue", { bg = "#007e87", fg = "#804e00" })
  hi(0, "CocListYellowCyan", { bg = "#006f44", fg = "#804e00" })
  hi(0, "CocListYellowGreen", { bg = "#636900", fg = "#804e00" })
  hi(0, "CocListYellowGrey", { bg = "#e0e2e9", fg = "#804e00" })
  hi(0, "CocListYellowMagenta", { bg = "#370674", fg = "#804e00" })
  hi(0, "CocListYellowRed", { bg = "#61004f", fg = "#804e00" })
  hi(0, "CocListYellowWhite", { bg = "#2c2e33", fg = "#804e00" })
  hi(0, "CocListYellowYellow", { bg = "#804e00", fg = "#804e00" })
  hi(0, "CocMarkdownLink", { fg = "#004d84" })
  hi(0, "CocMenuSel", { bg = "#a0a2a8" })
  hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
  hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
  hi(0, "CocSearch", { fg = "#004d84" })
  hi(0, "CocSelectedText", { fg = "#804e00" })
  hi(0, "CocStrikeThrough", { strikethrough = true })
  hi(0, "CocSymbolArray", { ctermfg = 223, fg = "#007e87" })
  hi(0, "CocSymbolBoolean", { ctermfg = 223, fg = "#370674" })
  hi(0, "CocSymbolClass", { ctermfg = 223, fg = "#006f44" })
  hi(0, "CocSymbolColor", { ctermfg = 223, fg = "#370674" })
  hi(0, "CocSymbolConstant", { ctermfg = 223, fg = "#370674" })
  hi(0, "CocSymbolConstructor", { ctermfg = 223, fg = "#006f44" })
  hi(0, "CocSymbolEnum", { ctermfg = 223, fg = "#2c2e33" })
  hi(0, "CocSymbolEnumMember", { ctermfg = 223, fg = "#804e00" })
  hi(0, "CocSymbolEvent", { ctermfg = 223, fg = "#370674" })
  hi(0, "CocSymbolField", { ctermfg = 223, fg = "#804e00" })
  hi(0, "CocSymbolFile", { ctermfg = 223, fg = "#2c2e33" })
  hi(0, "CocSymbolFolder", { ctermfg = 223, fg = "#007e87" })
  hi(0, "CocSymbolFunction", { ctermfg = 223, fg = "#007e87" })
  hi(0, "CocSymbolInterface", { ctermfg = 223, fg = "#2c2e33" })
  hi(0, "CocSymbolKey", { ctermfg = 223, fg = "#804e00" })
  hi(0, "CocSymbolKeyword", { ctermfg = 223, fg = "#2c2e33" })
  hi(0, "CocSymbolMethod", { ctermfg = 223, fg = "#007e87" })
  hi(0, "CocSymbolModule", { ctermfg = 223, fg = "#804e00" })
  hi(0, "CocSymbolNamespace", { ctermfg = 223, fg = "#804e00" })
  hi(0, "CocSymbolNull", { ctermfg = 223, fg = "#2c2e33" })
  hi(0, "CocSymbolNumber", { ctermfg = 223, fg = "#370674" })
  hi(0, "CocSymbolObject", { ctermfg = 223, fg = "#007e87" })
  hi(0, "CocSymbolOperator", { ctermfg = 223, fg = "#2c2e33" })
  hi(0, "CocSymbolPackage", { ctermfg = 223, fg = "#2c2e33" })
  hi(0, "CocSymbolProperty", { ctermfg = 223, fg = "#804e00" })
  hi(0, "CocSymbolReference", { ctermfg = 223, fg = "#804e00" })
  hi(0, "CocSymbolSnippet", { ctermfg = 223, fg = "#007e87" })
  hi(0, "CocSymbolString", { ctermfg = 223, fg = "#636900" })
  hi(0, "CocSymbolStruct", { ctermfg = 223, fg = "#2c2e33" })
  hi(0, "CocSymbolText", { ctermfg = 223, fg = "#007e87" })
  hi(0, "CocSymbolTypeParameter", { ctermfg = 223, fg = "#004d84" })
  hi(0, "CocSymbolUnit", { ctermfg = 223, fg = "#007e87" })
  hi(0, "CocSymbolValue", { ctermfg = 223, fg = "#007e87" })
  hi(0, "CocSymbolVariable", { ctermfg = 223, fg = "#006f44" })
  hi(0, "CocUnderline", { sp = "#ebdbb2", underline = true })
  hi(0, "CocVirtualText", { ctermfg = 12, fg = "#504945" })
  hi(0, "ColorColumn", { bg = "#a0a2a8" })
  hi(0, "Comment", { fg = "#64666c" })
  hi(0, "Conceal", { fg = "#007e87" })
  hi(0, "Constant", { fg = "#370674" })
  hi(0, "CurSearch", { bg = "#804e00", fg = "#e0e2e9" })
  hi(0, "Cursor", { bg = "#2c2e33", fg = "#e0e2e9" })
  hi(0, "CursorColumn", { bg = "#c0c2c9" })
  hi(0, "CursorLine", { bg = "#c0c2c9" })
  hi(0, "CursorLineFold", { fg = "#a0a2a8" })
  hi(0, "CursorLineNr", { bold = true, fg = "#1c177c" })
  hi(0, "CursorLineSign", { fg = "#a0a2a8" })
  hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#636900" })
  hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
  hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
  hi(0, "DapUIBreakpointsPath", { link = "Directory" })
  hi(0, "DapUIDecoration", { link = "Title" })
  hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
  hi(0, "DapUILineNumber", { link = "Title" })
  hi(0, "DapUIModifiedValue", { bold = true, fg = "#700011" })
  hi(0, "DapUIScope", { link = "Title" })
  hi(0, "DapUISource", { link = "Directory" })
  hi(0, "DapUIStoppedThread", { link = "Title" })
  hi(0, "DapUIThread", { link = "String" })
  hi(0, "DapUIType", { link = "Type" })
  hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
  hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
  hi(0, "DapUIWatchesValue", { link = "String" })
  hi(0, "DashboardCenter", { link = "Delimiter" })
  hi(0, "DashboardFooter", { link = "Comment" })
  hi(0, "DashboardHeader", { link = "Title" })
  hi(0, "DashboardShortCut", { link = "WarningMsg" })
  hi(0, "Definitions", { fg = "#636900" })
  hi(0, "DefinitionsIcon", { fg = "#007e87" })
  hi(0, "Delimiter", { fg = "#700011" })
  hi(0, "DiagnosticDeprecated", { sp = "#61004f", strikethrough = true })
  hi(0, "DiagnosticError", { fg = "#61004f" })
  hi(0, "DiagnosticFloatingError", { bg = "#e9ebf3", fg = "#61004f" })
  hi(0, "DiagnosticFloatingHint", { bg = "#e9ebf3", fg = "#006f44" })
  hi(0, "DiagnosticFloatingInfo", { bg = "#e9ebf3", fg = "#004d84" })
  hi(0, "DiagnosticFloatingOk", { bg = "#e9ebf3", fg = "#636900" })
  hi(0, "DiagnosticFloatingWarn", { bg = "#e9ebf3", fg = "#804e00" })
  hi(0, "DiagnosticHint", { fg = "#006f44" })
  hi(0, "DiagnosticInfo", { fg = "#004d84" })
  hi(0, "DiagnosticOk", { fg = "#636900" })
  hi(0, "DiagnosticUnderlineError", { sp = "#61004f", underline = true })
  hi(0, "DiagnosticUnderlineHint", { sp = "#006f44", underline = true })
  hi(0, "DiagnosticUnderlineInfo", { sp = "#004d84", underline = true })
  hi(0, "DiagnosticUnderlineOk", { sp = "#636900", underline = true })
  hi(0, "DiagnosticUnderlineWarn", { sp = "#804e00", underline = true })
  hi(0, "DiagnosticWarn", { fg = "#804e00" })
  hi(0, "DiffAdd", { bg = "#e3ed64" })
  hi(0, "DiffChange", { bg = "#7dffbb" })
  hi(0, "DiffDelete", { bg = "#ffb1ef" })
  hi(0, "DiffText", { bg = "#ffc787" })
  hi(0, "Directory", { fg = "#007e87" })
  hi(0, "EndOfBuffer", { fg = "#a0a2a8" })
  hi(0, "Error", { bg = "#ffb1ef" })
  hi(0, "ErrorMsg", { fg = "#61004f" })
  hi(0, "FgCocErrorFloatBgCocFloating", { bg = "#e9ebf3", ctermbg = 195, ctermfg = 53, fg = "#61004f" })
  hi(0, "FgCocHintFloatBgCocFloating", { bg = "#e9ebf3", ctermbg = 195, ctermfg = 22, fg = "#006f44" })
  hi(0, "FinderParam", { fg = "#804e00" })
  hi(0, "FinderSpinner", { fg = "#636900" })
  hi(0, "FinderSpinnerBorder", { fg = "#1c177c" })
  hi(0, "FinderSpinnerTitle", { link = "Title" })
  hi(0, "FinderVirtText", { fg = "#700011" })
  hi(0, "Float", { link = "Constant" })
  hi(0, "FloatBorder", { bg = "#e9ebf3", fg = "#1c177c" })
  hi(0, "FloatTitle", { bg = "#e9ebf3", bold = true, fg = "#1c177c" })
  hi(0, "FoldColumn", { fg = "#a0a2a8" })
  hi(0, "Folded", { bg = "#e9ebf3", fg = "#64666c" })
  hi(0, "Function", { fg = "#007e87" })
  hi(0, "GitSignsAdd", { fg = "#636900" })
  hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
  hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
  hi(0, "GitSignsChange", { fg = "#804e00" })
  hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
  hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
  hi(0, "GitSignsDelete", { fg = "#61004f" })
  hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
  hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
  hi(0, "GitSignsUntracked", { fg = "#007e87" })
  hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
  hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
  hi(0, "HopNextKey", { bold = true, fg = "#636900", nocombine = true })
  hi(0, "HopNextKey1", { bold = true, fg = "#700011", nocombine = true })
  hi(0, "HopNextKey2", { bold = true, fg = "#47494f", nocombine = true })
  hi(0, "HopPreview", { bold = true, fg = "#804e00", nocombine = true })
  hi(0, "HopUnmatched", { fg = "#a0a2a8" })
  hi(0, "HydraAmaranth", { fg = "#370674" })
  hi(0, "HydraBlue", { fg = "#007e87" })
  hi(0, "HydraHint", { link = "NormalFloat" })
  hi(0, "HydraPink", { fg = "#700011" })
  hi(0, "HydraRed", { fg = "#61004f" })
  hi(0, "HydraTeal", { fg = "#006f44" })
  hi(0, "Identifier", { fg = "#804e00" })
  hi(0, "Ignore", {})
  hi(0, "IncSearch", { bg = "#804e00", fg = "#e0e2e9" })
  hi(0, "IndentBlanklineChar", { fg = "#a0a2a8", nocombine = true })
  hi(0, "IndentBlanklineContextChar", { fg = "#1c177c", nocombine = true })
  hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#1c177c", underline = true })
  hi(0, "IndentBlanklineIndent1", { fg = "#004d84", nocombine = true })
  hi(0, "IndentBlanklineIndent2", { fg = "#006f44", nocombine = true })
  hi(0, "IndentBlanklineIndent3", { fg = "#804e00", nocombine = true })
  hi(0, "IndentBlanklineIndent4", { fg = "#61004f", nocombine = true })
  hi(0, "IndentBlanklineIndent5", { fg = "#007e87", nocombine = true })
  hi(0, "IndentBlanklineIndent6", { fg = "#636900", nocombine = true })
  hi(0, "IndentBlanklineIndent7", { fg = "#700011", nocombine = true })
  hi(0, "IndentBlanklineIndent8", { fg = "#370674", nocombine = true })
  hi(0, "Italic", { italic = true })
  hi(0, "LSOutlinePreviewBorder", { fg = "#1c177c" })
  hi(0, "LazyButton", { bg = "#c0c2c9" })
  hi(0, "LazyButtonActive", { bg = "#a0a2a8" })
  hi(0, "LazyDimmed", { link = "Comment" })
  hi(0, "LazyH1", { bg = "#a0a2a8", bold = true, fg = "#1c177c" })
  hi(0, "LeapBackdrop", { link = "Comment" })
  hi(0, "LeapLabel", { bold = true, fg = "#804e00", nocombine = true })
  hi(0, "LeapLabelSelected", { bold = true, fg = "#006f44", nocombine = true })
  hi(0, "LeapMatch", { bold = true, fg = "#636900", nocombine = true, underline = true })
  hi(0, "LineNr", { fg = "#a0a2a8" })
  hi(0, "LspCodeLens", { link = "Comment" })
  hi(0, "LspCodeLensSeparator", { link = "Comment" })
  hi(0, "LspReferenceText", { bg = "#a0a2a8" })
  hi(0, "LspSagaAutoPreview", { fg = "#004d84" })
  hi(0, "LspSagaBorderTitle", { link = "FloatTitle" })
  hi(0, "LspSagaCodeActionBorder", { fg = "#1c177c" })
  hi(0, "LspSagaCodeActionContent", { fg = "#2c2e33" })
  hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#007e87" })
  hi(0, "LspSagaDefPreviewBorder", { fg = "#1c177c" })
  hi(0, "LspSagaDiagnosticBorder", { fg = "#1c177c" })
  hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
  hi(0, "LspSagaDiagnosticSource", { fg = "#700011" })
  hi(0, "LspSagaFinderSelection", { fg = "#006f44" })
  hi(0, "LspSagaHoverBorder", { fg = "#1c177c" })
  hi(0, "LspSagaLspFinderBorder", { fg = "#1c177c" })
  hi(0, "LspSagaRenameBorder", { fg = "#1c177c" })
  hi(0, "LspSagaSignatureHelpBorder", { fg = "#1c177c" })
  hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
  hi(0, "MasonError", { fg = "#61004f" })
  hi(0, "MasonHeader", { bg = "#007e87", bold = true, fg = "#e0e2e9" })
  hi(0, "MasonHeaderSecondary", { bg = "#004d84", bold = true, fg = "#e0e2e9" })
  hi(0, "MasonHeading", { link = "Bold" })
  hi(0, "MasonHighlight", { fg = "#1c177c" })
  hi(0, "MasonHighlightBlock", { bg = "#1c177c", fg = "#e0e2e9" })
  hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
  hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
  hi(0, "MasonHighlightBlockSecondary", { bg = "#007e87", fg = "#e0e2e9" })
  hi(0, "MasonHighlightSecondary", { fg = "#007e87" })
  hi(0, "MasonLink", { link = "MasonHighlight" })
  hi(0, "MasonMuted", { link = "Comment" })
  hi(0, "MasonMutedBlock", { bg = "#a0a2a8", fg = "#e0e2e9" })
  hi(0, "MasonMutedBlockBold", { bg = "#a0a2a8", bold = true, fg = "#e0e2e9" })
  hi(0, "MatchParen", { bg = "#a0a2a8", bold = true })
  hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
  hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
  hi(0, "MiniClueBorder", { link = "FloatBorder" })
  hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
  hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
  hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
  hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
  hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
  hi(0, "MiniClueTitle", { link = "FloatTitle" })
  hi(0, "MiniCompletionActiveParameter", { bg = "#a0a2a8" })
  hi(0, "MiniCursorword", { underline = true })
  hi(0, "MiniCursorwordCurrent", { underline = true })
  hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
  hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
  hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
  hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
  hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
  hi(0, "MiniDepsPlaceholder", { link = "Comment" })
  hi(0, "MiniDepsTitle", { link = "Title" })
  hi(0, "MiniDepsTitleError", { link = "DiffDelete" })
  hi(0, "MiniDepsTitleSame", { link = "DiffText" })
  hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
  hi(0, "MiniDiffOverAdd", { link = "DiffAdd" })
  hi(0, "MiniDiffOverChange", { link = "DiffText" })
  hi(0, "MiniDiffOverContext", { link = "DiffChange" })
  hi(0, "MiniDiffOverDelete", { link = "DiffDelete" })
  hi(0, "MiniDiffSignAdd", { link = "diffAdded" })
  hi(0, "MiniDiffSignChange", { link = "diffChanged" })
  hi(0, "MiniDiffSignDelete", { link = "diffRemoved" })
  hi(0, "MiniFilesBorder", { link = "FloatBorder" })
  hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
  hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
  hi(0, "MiniFilesDirectory", { link = "Directory" })
  hi(0, "MiniFilesFile", { fg = "#2c2e33" })
  hi(0, "MiniFilesNormal", { link = "NormalFloat" })
  hi(0, "MiniFilesTitle", { link = "FloatTitle" })
  hi(0, "MiniFilesTitleFocused", { bg = "#e9ebf3", bold = true, fg = "#2c2e33" })
  hi(0, "MiniHipatternsFixme", { bg = "#61004f", bold = true, fg = "#e0e2e9" })
  hi(0, "MiniHipatternsHack", { bg = "#804e00", bold = true, fg = "#e0e2e9" })
  hi(0, "MiniHipatternsNote", { bg = "#006f44", bold = true, fg = "#e0e2e9" })
  hi(0, "MiniHipatternsTodo", { bg = "#004d84", bold = true, fg = "#e0e2e9" })
  hi(0, "MiniHipatterns_002c06_bg", { bg = "#002c06", fg = "#ffffff" })
  hi(0, "MiniHipatterns_004c49_bg", { bg = "#004c49", fg = "#ffffff" })
  hi(0, "MiniHipatterns_020814_bg", { bg = "#020814", fg = "#ffffff" })
  hi(0, "MiniHipatterns_0d1724_bg", { bg = "#0d1724", fg = "#ffffff" })
  hi(0, "MiniHipatterns_15aabf_bg", { bg = "#15aabf", fg = "#000000" })
  hi(0, "MiniHipatterns_192331_bg", { bg = "#192331", fg = "#ffffff" })
  hi(0, "MiniHipatterns_323c4c_bg", { bg = "#323c4c", fg = "#ffffff" })
  hi(0, "MiniHipatterns_400c19_bg", { bg = "#400c19", fg = "#ffffff" })
  hi(0, "MiniHipatterns_403700_bg", { bg = "#403700", fg = "#ffffff" })
  hi(0, "MiniHipatterns_4c5767_bg", { bg = "#4c5767", fg = "#ffffff" })
  hi(0, "MiniHipatterns_504945_bg", { bg = "#504945", fg = "#ffffff" })
  hi(0, "MiniHipatterns_87d8d2_bg", { bg = "#87d8d2", fg = "#000000" })
  hi(0, "MiniHipatterns_898c92_bg", { bg = "#898c92", fg = "#000000" })
  hi(0, "MiniHipatterns_93d0f4_bg", { bg = "#93d0f4", fg = "#000000" })
  hi(0, "MiniHipatterns_a6aab0_bg", { bg = "#a6aab0", fg = "#000000" })
  hi(0, "MiniHipatterns_a6c9fb_bg", { bg = "#a6c9fb", fg = "#000000" })
  hi(0, "MiniHipatterns_a7d5a7_bg", { bg = "#a7d5a7", fg = "#000000" })
  hi(0, "MiniHipatterns_bcc2fb_bg", { bg = "#bcc2fb", fg = "#000000" })
  hi(0, "MiniHipatterns_c3c7cd_bg", { bg = "#c3c7cd", fg = "#000000" })
  hi(0, "MiniHipatterns_d2c98c_bg", { bg = "#d2c98c", fg = "#000000" })
  hi(0, "MiniHipatterns_d5d9df_bg", { bg = "#d5d9df", fg = "#000000" })
  hi(0, "MiniHipatterns_e2b5e4_bg", { bg = "#e2b5e4", fg = "#000000" })
  hi(0, "MiniHipatterns_e8edf3_bg", { bg = "#e8edf3", fg = "#000000" })
  hi(0, "MiniHipatterns_ebdbb2_bg", { bg = "#ebdbb2", fg = "#000000" })
  hi(0, "MiniHipatterns_f0ba95_bg", { bg = "#f0ba95", fg = "#000000" })
  hi(0, "MiniHipatterns_f6b2bb_bg", { bg = "#f6b2bb", fg = "#000000" })
  hi(0, "MiniIconsAzure", { fg = "#007e87" })
  hi(0, "MiniIconsBlue", { fg = "#004d84" })
  hi(0, "MiniIconsCyan", { fg = "#006f44" })
  hi(0, "MiniIconsGreen", { fg = "#636900" })
  hi(0, "MiniIconsGrey", { fg = "#1d1e23" })
  hi(0, "MiniIconsOrange", { fg = "#700011" })
  hi(0, "MiniIconsPurple", { fg = "#370674" })
  hi(0, "MiniIconsRed", { fg = "#61004f" })
  hi(0, "MiniIconsYellow", { fg = "#804e00" })
  hi(0, "MiniIndentscopeSymbol", { fg = "#1c177c" })
  hi(0, "MiniIndentscopeSymbolOff", { fg = "#61004f" })
  hi(0, "MiniJump", { sp = "#1c177c", undercurl = true })
  hi(0, "MiniJump2dDim", { fg = "#a0a2a8" })
  hi(0, "MiniJump2dSpot", { bg = "#f3f5fc", bold = true, fg = "#0b0d11", nocombine = true })
  hi(0, "MiniJump2dSpotAhead", { bg = "#f3f5fc", fg = "#1d1e23", nocombine = true })
  hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
  hi(0, "MiniMapNormal", { bg = "#e9ebf3", fg = "#64666c" })
  hi(0, "MiniMapSymbolCount", { fg = "#64666c" })
  hi(0, "MiniMapSymbolLine", { fg = "#1c177c" })
  hi(0, "MiniMapSymbolView", { fg = "#1c177c" })
  hi(0, "MiniNotifyBorder", { link = "FloatBorder" })
  hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
  hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
  hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
  hi(0, "MiniPickBorder", { link = "FloatBorder" })
  hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
  hi(0, "MiniPickBorderText", { link = "FloatTitle" })
  hi(0, "MiniPickCursor", { blend = 100, nocombine = true })
  hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
  hi(0, "MiniPickIconDirectory", { link = "Directory" })
  hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
  hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
  hi(0, "MiniPickMatchMarked", { link = "Visual" })
  hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
  hi(0, "MiniPickNormal", { link = "NormalFloat" })
  hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
  hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
  hi(0, "MiniPickPrompt", { link = "DiagnosticFloatingInfo" })
  hi(0, "MiniStarterCurrent", { link = "MiniStarterItem" })
  hi(0, "MiniStarterFooter", { link = "Comment" })
  hi(0, "MiniStarterHeader", { bold = true, fg = "#1c177c" })
  hi(0, "MiniStarterInactive", { link = "Comment" })
  hi(0, "MiniStarterItemBullet", { fg = "#64666c" })
  hi(0, "MiniStarterItemPrefix", { bold = true, fg = "#804e00" })
  hi(0, "MiniStarterQuery", { bold = true, fg = "#636900" })
  hi(0, "MiniStarterSection", { fg = "#370674" })
  hi(0, "MiniStatuslineDevinfo", { bg = "#c0c2c9", fg = "#47494f" })
  hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
  hi(0, "MiniStatuslineFilename", { bg = "#e0e2e9", fg = "#47494f" })
  hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
  hi(0, "MiniStatuslineModeCommand", { bg = "#804e00", bold = true, fg = "#e0e2e9" })
  hi(0, "MiniStatuslineModeInsert", { bg = "#007e87", bold = true, fg = "#e0e2e9" })
  hi(0, "MiniStatuslineModeNormal", { bg = "#2c2e33", bold = true, fg = "#e0e2e9" })
  hi(0, "MiniStatuslineModeOther", { bg = "#006f44", bold = true, fg = "#e0e2e9" })
  hi(0, "MiniStatuslineModeReplace", { bg = "#61004f", bold = true, fg = "#e0e2e9" })
  hi(0, "MiniStatuslineModeVisual", { bg = "#636900", bold = true, fg = "#e0e2e9" })
  hi(0, "MiniSurround", { link = "IncSearch" })
  hi(0, "MiniTablineCurrent", { bg = "#e0e2e9", bold = true, fg = "#1c177c" })
  hi(0, "MiniTablineFill", { link = "MiniTablineHidden" })
  hi(0, "MiniTablineHidden", { bg = "#e9ebf3", fg = "#47494f" })
  hi(0, "MiniTablineModifiedCurrent", { bg = "#1c177c", bold = true, fg = "#e0e2e9" })
  hi(0, "MiniTablineModifiedHidden", { bg = "#47494f", fg = "#e9ebf3" })
  hi(0, "MiniTablineModifiedVisible", { bg = "#47494f", bold = true, fg = "#e9ebf3" })
  hi(0, "MiniTablineTabpagesection", { bg = "#636900", bold = true, fg = "#e0e2e9" })
  hi(0, "MiniTablineVisible", { bg = "#e9ebf3", bold = true, fg = "#47494f" })
  hi(0, "MiniTestEmphasis", { bold = true })
  hi(0, "MiniTestFail", { bold = true, fg = "#61004f" })
  hi(0, "MiniTestPass", { bold = true, fg = "#636900" })
  hi(0, "MiniTrailspace", { bg = "#ffb1ef" })
  hi(0, "ModeMsg", { fg = "#636900" })
  hi(0, "MoreMsg", { fg = "#007e87" })
  hi(0, "MsgArea", { link = "Normal" })
  hi(0, "MsgSeparator", { bg = "#a0a2a8", fg = "#64666c" })
  hi(0, "NeoTreeDimText", { fg = "#a0a2a8" })
  hi(0, "NeoTreeDotfile", { fg = "#47494f" })
  hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
  hi(0, "NeoTreeFadeText2", { fg = "#a0a2a8" })
  hi(0, "NeoTreeGitAdded", { fg = "#636900" })
  hi(0, "NeoTreeGitConflict", { bold = true, fg = "#700011" })
  hi(0, "NeoTreeGitDeleted", { fg = "#61004f" })
  hi(0, "NeoTreeGitModified", { fg = "#804e00" })
  hi(0, "NeoTreeGitUnstaged", { fg = "#370674" })
  hi(0, "NeoTreeGitUntracked", { fg = "#006f44" })
  hi(0, "NeoTreeMessage", { bg = "#c0c2c9", fg = "#2c2e33" })
  hi(0, "NeoTreeModified", { fg = "#1d1e23" })
  hi(0, "NeoTreeRootName", { bold = true, fg = "#1c177c" })
  hi(0, "NeoTreeTabInactive", { fg = "#64666c" })
  hi(0, "NeoTreeTabSeparatorActive", { bg = "#a0a2a8", fg = "#64666c" })
  hi(0, "NeoTreeTabSeparatorInactive", { bg = "#c0c2c9", fg = "#c0c2c9" })
  hi(0, "NeogitCommitViewHeader", { link = "Special" })
  hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
  hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
  hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
  hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
  hi(0, "NeogitFold", { link = "FoldColumn" })
  hi(0, "NeogitHunkHeader", { fg = "#1c177c" })
  hi(0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#1c177c" })
  hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
  hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
  hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
  hi(0, "NoiceCmdlinePopupBorder", { fg = "#007e87" })
  hi(0, "NoiceConfirmBorder", { fg = "#804e00" })
  hi(0, "NonText", { fg = "#a0a2a8" })
  hi(0, "Normal", { bg = "#e0e2e9", fg = "#2c2e33" })
  hi(0, "NormalFloat", { bg = "#e9ebf3", fg = "#2c2e33" })
  hi(0, "NormalNC", { link = "Normal" })
  hi(0, "NotifyDEBUGBorder", { fg = "#636900" })
  hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
  hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
  hi(0, "NotifyERRORBorder", { fg = "#61004f" })
  hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
  hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
  hi(0, "NotifyINFOBorder", { fg = "#004d84" })
  hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
  hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
  hi(0, "NotifyTRACEBorder", { fg = "#006f44" })
  hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
  hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
  hi(0, "NotifyWARNBorder", { fg = "#804e00" })
  hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
  hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
  hi(0, "NvimTreeExecFile", { bold = true, fg = "#636900" })
  hi(0, "NvimTreeFolderIcon", { fg = "#64666c" })
  hi(0, "NvimTreeGitDeleted", { fg = "#61004f" })
  hi(0, "NvimTreeGitDirty", { fg = "#804e00" })
  hi(0, "NvimTreeGitMerge", { fg = "#700011" })
  hi(0, "NvimTreeGitNew", { fg = "#006f44" })
  hi(0, "NvimTreeGitRenamed", { fg = "#370674" })
  hi(0, "NvimTreeGitStaged", { fg = "#636900" })
  hi(0, "NvimTreeImageFile", { fg = "#700011" })
  hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
  hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
  hi(0, "NvimTreeRootFolder", { bold = true, fg = "#1c177c" })
  hi(0, "NvimTreeSpecialFile", { fg = "#1c177c", underline = true })
  hi(0, "NvimTreeSymlink", { bold = true, fg = "#004d84" })
  hi(0, "NvimTreeWindowPicker", { bg = "#a0a2a8", bold = true, fg = "#2c2e33" })
  hi(0, "Operator", { fg = "#2c2e33" })
  hi(0, "OutlineDetail", { fg = "#a0a2a8" })
  hi(0, "OutlineFoldPrefix", { fg = "#804e00" })
  hi(0, "OutlineIndentEvn", { fg = "#64666c" })
  hi(0, "OutlineIndentOdd", { fg = "#2c2e33" })
  hi(0, "Pmenu", { bg = "#c0c2c9", fg = "#2c2e33" })
  hi(0, "PmenuMatch", { bg = "#c0c2c9", bold = true, fg = "#2c2e33" })
  hi(0, "PmenuMatchSel", { blend = 0, bold = true, reverse = true })
  hi(0, "PmenuSel", { blend = 0, reverse = true })
  hi(0, "PmenuThumb", { bg = "#a0a2a8" })
  hi(0, "PounceAccept", { bg = "#804e00", bold = true, fg = "#e0e2e9", nocombine = true })
  hi(0, "PounceAcceptBest", { bg = "#636900", bold = true, fg = "#e0e2e9", nocombine = true })
  hi(0, "PounceGap", { bg = "#a0a2a8", bold = true, fg = "#e0e2e9", nocombine = true })
  hi(0, "PounceMatch", { bg = "#2c2e33", bold = true, fg = "#e0e2e9", nocombine = true })
  hi(0, "PreProc", { fg = "#004d84" })
  hi(0, "Question", { fg = "#007e87" })
  hi(0, "QuickFixLine", { bold = true })
  hi(0, "RainbowDelimiterBlue", { fg = "#007e87" })
  hi(0, "RainbowDelimiterCyan", { fg = "#006f44" })
  hi(0, "RainbowDelimiterGreen", { fg = "#636900" })
  hi(0, "RainbowDelimiterOrange", { fg = "#700011" })
  hi(0, "RainbowDelimiterRed", { fg = "#61004f" })
  hi(0, "RainbowDelimiterViolet", { fg = "#370674" })
  hi(0, "RainbowDelimiterYellow", { fg = "#804e00" })
  hi(0, "References", { fg = "#636900" })
  hi(0, "ReferencesIcon", { fg = "#007e87" })
  hi(0, "Removed", { fg = "#61004f" })
  hi(0, "Search", { bg = "#1c177c", fg = "#e0e2e9" })
  hi(0, "SignColumn", { fg = "#a0a2a8" })
  hi(0, "Sneak", { bg = "#700011", fg = "#e0e2e9" })
  hi(0, "SneakLabel", { bg = "#700011", bold = true, fg = "#e0e2e9" })
  hi(0, "SneakScope", { bg = "#0b0d11", fg = "#e0e2e9" })
  hi(0, "Special", { fg = "#006f44" })
  hi(0, "SpecialKey", { fg = "#a0a2a8" })
  hi(0, "SpellBad", { sp = "#61004f", undercurl = true })
  hi(0, "SpellCap", { sp = "#006f44", undercurl = true })
  hi(0, "SpellLocal", { sp = "#804e00", undercurl = true })
  hi(0, "SpellRare", { sp = "#004d84", undercurl = true })
  hi(0, "Statement", { bold = true, fg = "#2c2e33" })
  hi(0, "StatusLine", { bg = "#e0e2e9", fg = "#47494f" })
  hi(0, "StatusLineNC", { bg = "#e9ebf3", fg = "#47494f" })
  hi(0, "String", { fg = "#636900" })
  hi(0, "Substitute", { bg = "#004d84", fg = "#e0e2e9" })
  hi(0, "TabLine", { bg = "#e9ebf3", fg = "#47494f" })
  hi(0, "TabLineSel", { bg = "#e9ebf3", fg = "#1c177c" })
  hi(0, "TargetFileName", { fg = "#2c2e33" })
  hi(0, "TelescopeBorder", { fg = "#1c177c" })
  hi(0, "TelescopeMatching", { bold = true })
  hi(0, "TelescopeMultiSelection", { bg = "#a0a2a8" })
  hi(0, "TelescopeSelection", { bg = "#c0c2c9" })
  hi(0, "TermCursorNC", { reverse = true })
  hi(0, "Title", { fg = "#1c177c" })
  hi(0, "Todo", { bg = "#e0e2e9", bold = true, fg = "#1c177c" })
  hi(0, "TroubleCount", { bold = true, fg = "#1c177c" })
  hi(0, "TroubleFoldIcon", { bold = true, fg = "#1c177c" })
  hi(0, "TroubleIndent", { fg = "#a0a2a8" })
  hi(0, "TroubleLocation", { fg = "#47494f" })
  hi(0, "TroubleSignError", { link = "DiagnosticError" })
  hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
  hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
  hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
  hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
  hi(0, "TroubleText", { fg = "#2c2e33" })
  hi(0, "TroubleTextError", { link = "TroubleText" })
  hi(0, "TroubleTextHint", { link = "TroubleText" })
  hi(0, "TroubleTextInformation", { link = "TroubleText" })
  hi(0, "TroubleTextWarning", { link = "TroubleText" })
  hi(0, "Type", { fg = "#2c2e33" })
  hi(0, "VertSplit", { fg = "#1c177c" })
  hi(0, "Visual", { bg = "#a0a2a8" })
  hi(0, "VisualNOS", { bg = "#c0c2c9" })
  hi(0, "WarningMsg", { fg = "#804e00" })
  hi(0, "WhichKey", { fg = "#006f44" })
  hi(0, "WhichKeyBorder", { link = "FloatBorder" })
  hi(0, "WhichKeyDesc", { fg = "#2c2e33" })
  hi(0, "WhichKeyFloat", { bg = "#e9ebf3", fg = "#2c2e33" })
  hi(0, "WhichKeyGroup", { fg = "#61004f" })
  hi(0, "WhichKeyIconAzure", { link = "MiniIconsAzure" })
  hi(0, "WhichKeyIconBlue", { link = "MiniIconsBlue" })
  hi(0, "WhichKeyIconCyan", { link = "MiniIconsCyan" })
  hi(0, "WhichKeyIconGreen", { link = "MiniIconsGreen" })
  hi(0, "WhichKeyIconGrey", { link = "MiniIconsGrey" })
  hi(0, "WhichKeyIconOrange", { link = "MiniIconsOrange" })
  hi(0, "WhichKeyIconPurple", { link = "MiniIconsPurple" })
  hi(0, "WhichKeyIconRed", { link = "MiniIconsRed" })
  hi(0, "WhichKeyIconYellow", { link = "MiniIconsYellow" })
  hi(0, "WhichKeySeparator", { fg = "#636900" })
  hi(0, "WhichKeyValue", { link = "Comment" })
  hi(0, "Whitespace", { fg = "#a0a2a8" })
  hi(0, "WinBar", { link = "StatusLine" })
  hi(0, "WinBarNC", { link = "StatusLineNC" })
  hi(0, "WinSeparator", { fg = "#1c177c" })
  hi(0, "diffAdded", { fg = "#636900" })
  hi(0, "diffChanged", { fg = "#006f44" })
  hi(0, "diffFile", { fg = "#804e00" })
  hi(0, "diffLine", { fg = "#004d84" })
  hi(0, "diffRemoved", { fg = "#61004f" })
  hi(0, "gitcommitBranch", { bold = true, fg = "#700011" })
  hi(0, "gitcommitComment", { link = "Comment" })
  hi(0, "gitcommitDiscarded", { link = "Comment" })
  hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#804e00" })
  hi(0, "gitcommitDiscardedType", { fg = "#007e87" })
  hi(0, "gitcommitHeader", { link = "Title" })
  hi(0, "gitcommitOverflow", { fg = "#804e00" })
  hi(0, "gitcommitSelected", { link = "Comment" })
  hi(0, "gitcommitSelectedFile", { bold = true, fg = "#636900" })
  hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
  hi(0, "gitcommitSummary", { fg = "#636900" })
  hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
  hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
  hi(0, "gitcommitUntracked", { link = "Comment" })
  hi(0, "gitcommitUntrackedFile", { fg = "#006f44" })
  hi(0, "lCursor", { bg = "#2c2e33", fg = "#e0e2e9" })

  -- Terminal colors
  local g = vim.g

  g.terminal_color_0 = "#e0e2e9"
  g.terminal_color_1 = "#61004f"
  g.terminal_color_2 = "#636900"
  g.terminal_color_3 = "#804e00"
  g.terminal_color_4 = "#007e87"
  g.terminal_color_5 = "#370674"
  g.terminal_color_6 = "#006f44"
  g.terminal_color_7 = "#2c2e33"
  g.terminal_color_8 = "#e0e2e9"
  g.terminal_color_9 = "#61004f"
  g.terminal_color_10 = "#636900"
  g.terminal_color_11 = "#804e00"
  g.terminal_color_12 = "#007e87"
  g.terminal_color_13 = "#370674"
  g.terminal_color_14 = "#006f44"
  g.terminal_color_15 = "#2c2e33"
end
