-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
	vim.cmd ("highlight clear")
end
vim.g.colors_name = "mini"

-- Highlight groups
local hi = vim.api.nvim_set_hl

if vim.o.background == "dark" then
	hi (0, "@character.special", { link = "SpecialChar" })
	hi (0, "@comment.documentation", { link = "@comment" })
	hi (0, "@comment.error", { fg = "#e0bace", italic = true })
	hi (0, "@comment.note", { fg = "#a2d0d9", italic = true })
	hi (0, "@comment.todo", { bg = "#14161b", bold = true, fg = "#b9c6e8", italic = true })
	hi (0, "@comment.warning", { fg = "#dbc3a3", italic = true })
	hi (0, "@conditional", { link = "Conditional" })
	hi (0, "@constant.builtin", { link = "Special" })
	hi (0, "@constant.macro", { link = "Macro" })
	hi (0, "@debug", { link = "Debug" })
	hi (0, "@define", { link = "Define" })
	hi (0, "@diff.delta", { link = "diffChanged" })
	hi (0, "@diff.minus", { link = "diffRemoved" })
	hi (0, "@diff.plus", { link = "diffAdded" })
	hi (0, "@exception", { link = "Exception" })
	hi (0, "@field", { link = "Identifier" })
	hi (0, "@float", { link = "Float" })
	hi (0, "@function.builtin", { link = "Special" })
	hi (0, "@function.call", { link = "Function" })
	hi (0, "@function.macro", { link = "Macro" })
	hi (0, "@function.method", { link = "@method" })
	hi (0, "@function.method.call", { link = "@method.call" })
	hi (0, "@include", { link = "Include" })
	hi (0, "@keyword.conditional", { link = "@keyword" })
	hi (0, "@keyword.conditional.ternary", { link = "Keyword" })
	hi (0, "@keyword.coroutine", { link = "@keyword" })
	hi (0, "@keyword.debug", { bold = true, fg = "#aad2bf" })
	hi (0, "@keyword.directive", { bold = true, fg = "#b1c9e8" })
	hi (0, "@keyword.directive.define", { link = "@keyword.directive" })
	hi (0, "@keyword.exception", { link = "@keyword" })
	hi (0, "@keyword.function", { link = "@keyword" })
	hi (0, "@keyword.import", { bold = true, fg = "#b1c9e8" })
	hi (0, "@keyword.operator", { link = "@keyword" })
	hi (0, "@keyword.repeat", { link = "@keyword" })
	hi (0, "@keyword.return", { bold = true, fg = "#e6bbb4" })
	hi (0, "@keyword.storage", { bold = true, fg = "#c6c6cd" })
	hi (0, "@lsp.mod.defaultLibrary", { link = "Special" })
	hi (0, "@lsp.mod.deprecated", { fg = "#e0bace" })
	hi (0, "@lsp.type.class", { link = "@structure" })
	hi (0, "@lsp.type.decorator", { link = "@function" })
	hi (0, "@lsp.type.enum", { link = "@type" })
	hi (0, "@lsp.type.enumMember", { link = "@constant" })
	hi (0, "@lsp.type.function", { link = "@function" })
	hi (0, "@lsp.type.interface", { link = "@type" })
	hi (0, "@lsp.type.macro", { link = "@macro" })
	hi (0, "@lsp.type.method", { link = "@method" })
	hi (0, "@lsp.type.namespace", { link = "@namespace" })
	hi (0, "@lsp.type.parameter", { link = "@parameter" })
	hi (0, "@lsp.type.property", { link = "@property" })
	hi (0, "@lsp.type.struct", { link = "@structure" })
	hi (0, "@lsp.type.type", { link = "@type" })
	hi (0, "@lsp.type.typeParameter", { link = "@type.definition" })
	hi (0, "@lsp.type.variable", { link = "@variable" })
	hi (0, "@macro", { link = "Macro" })
	hi (0, "@markup.environment", { link = "@module" })
	hi (0, "@markup.heading", { link = "@text.title" })
	hi (0, "@markup.italic", { link = "@text.emphasis" })
	hi (0, "@markup.link", { link = "@text.reference" })
	hi (0, "@markup.link.label", { link = "@markup.link" })
	hi (0, "@markup.link.url", { fg = "#c6c6cd", underline = true })
	hi (0, "@markup.list", { link = "@punctuation.special" })
	hi (0, "@markup.list.checked", { link = "DiagnosticOk" })
	hi (0, "@markup.list.unchecked", { link = "DiagnosticWarn" })
	hi (0, "@markup.math", { link = "@string.special" })
	hi (0, "@markup.quote", { link = "@string.special" })
	hi (0, "@markup.raw", { link = "@text.literal" })
	hi (0, "@markup.raw.block", { link = "@markup.raw" })
	hi (0, "@markup.strikethrough", { link = "@text.strike" })
	hi (0, "@markup.strong", { link = "@text.strong" })
	hi (0, "@markup.underline", { link = "@text.underline" })
	hi (0, "@method", { link = "Function" })
	hi (0, "@method.call", { link = "Function" })
	hi (0, "@module", { link = "@namespace" })
	hi (0, "@module.builtin", { link = "@variable.builtin" })
	hi (0, "@namespace", { link = "Identifier" })
	hi (0, "@none", { link = "Normal" })
	hi (0, "@number.float", { link = "@float" })
	hi (0, "@parameter", { fg = "#b1c9e8" })
	hi (0, "@preproc", { link = "PreProc" })
	hi (0, "@punctuation.bracket", { link = "@punctuation" })
	hi (0, "@punctuation.delimiter", { link = "@punctuation" })
	hi (0, "@punctuation.special", { link = "Special" })
	hi (0, "@repeat", { link = "Repeat" })
	hi (0, "@storageclass", { link = "StorageClass" })
	hi (0, "@string.documentation", { link = "@string" })
	hi (0, "@string.escape", { link = "SpecialChar" })
	hi (0, "@string.regexp", { link = "SpecialChar" })
	hi (0, "@string.special", { link = "SpecialChar" })
	hi (0, "@string.special.path", { link = "Directory" })
	hi (0, "@string.special.symbol", { link = "@constant" })
	hi (0, "@string.special.url", { link = "@markup.link.url" })
	hi (0, "@string.special.vimdoc", { link = "@constant" })
	hi (0, "@structure", { link = "Structure" })
	hi (0, "@symbol", { link = "Keyword" })
	hi (0, "@tag.attribute", { link = "@tag" })
	hi (0, "@tag.delimiter", { link = "@punctuation" })
	hi (0, "@text.danger", { link = "ErrorMsg" })
	hi (0, "@text.emphasis", { italic = true })
	hi (0, "@text.literal", { link = "Special" })
	hi (0, "@text.note", { link = "MoreMsg" })
	hi (0, "@text.reference", { link = "Identifier" })
	hi (0, "@text.strike", { strikethrough = true })
	hi (0, "@text.strong", { bold = true })
	hi (0, "@text.title", { link = "Title" })
	hi (0, "@text.todo", { link = "Todo" })
	hi (0, "@text.underline", { link = "Underlined" })
	hi (0, "@text.uri", { link = "Underlined" })
	hi (0, "@text.warning", { link = "WarningMsg" })
	hi (0, "@type.builtin", { link = "Special" })
	hi (0, "@type.definition", { link = "Typedef" })
	hi (0, "@type.qualifier", { link = "StorageClass" })
	hi (0, "@variable", { fg = "#c6c6cd" })
	hi (0, "@variable.builtin", { link = "Special" })
	hi (0, "@variable.member", { link = "@field" })
	hi (0, "@variable.parameter", { link = "@parameter" })
	hi (0, "Added", { fg = "#c2cca8" })
	hi (0, "Beacon", { bg = "#ebebf3" })
	hi (0, "Bold", { bold = true })
	hi (0, "BqfPreviewFloat", { link = "NormalFloat" })
	hi (0, "BqfPreviewTitle", { link = "FloatTitle" })
	hi (0, "BqfSign", { fg = "#aad2bf" })
	hi (0, "BufferCurrent", { bg = "#14161b", bold = true, fg = "#b9c6e8" })
	hi (0, "BufferCurrentIcon", { bg = "#14161b" })
	hi (0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
	hi (0, "BufferCurrentMod", { bg = "#2f3237", bold = true, fg = "#b9c6e8" })
	hi (0, "BufferCurrentSign", { link = "BufferCurrent" })
	hi (0, "BufferCurrentTarget", { bg = "#4b4e54", bold = true, fg = "#b9c6e8" })
	hi (0, "BufferInactive", { bg = "#0b0d12", fg = "#c6c6cd" })
	hi (0, "BufferInactiveIcon", { bg = "#0b0d12" })
	hi (0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
	hi (0, "BufferInactiveMod", { bg = "#2f3237", fg = "#c6c6cd" })
	hi (0, "BufferInactiveSign", { link = "BufferInactive" })
	hi (0, "BufferInactiveTarget", { bg = "#4b4e54", fg = "#c6c6cd" })
	hi (0, "BufferLineBuffer", { fg = "#87878e" })
	hi (0, "BufferLineBufferSelected", { bold = true, fg = "#c6c6cd" })
	hi (0, "BufferLineBufferVisible", { fg = "#c6c6cd" })
	hi (0, "BufferLineCloseButton", { link = "BufferLineBackground" })
	hi (0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
	hi (0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
	hi (0, "BufferLineFill", { link = "Normal" })
	hi (0, "BufferLineTab", { bg = "#c2cca8", fg = "#14161b" })
	hi (0, "BufferLineTabSelected", { bg = "#c2cca8", bold = true, fg = "#14161b" })
	hi (0, "BufferOffset", { link = "Normal" })
	hi (0, "BufferTabpageFill", { link = "Normal" })
	hi (0, "BufferTabpages", { bg = "#c2cca8", bold = true, fg = "#14161b" })
	hi (0, "BufferVisible", { bg = "#14161b", bold = true, fg = "#c6c6cd" })
	hi (0, "BufferVisibleIcon", { bg = "#14161b" })
	hi (0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
	hi (0, "BufferVisibleMod", { bg = "#2f3237", bold = true, fg = "#c6c6cd" })
	hi (0, "BufferVisibleSign", { link = "BufferVisible" })
	hi (0, "BufferVisibleTarget", { bg = "#4b4e54", bold = true, fg = "#c6c6cd" })
	hi (0, "Changed", { fg = "#aad2bf" })
	hi (0, "CmpItemAbbr", { fg = "#c6c6cd" })
	hi (0, "CmpItemAbbrDeprecated", { fg = "#87878e", strikethrough = true })
	hi (0, "CmpItemAbbrMatch", { bold = true })
	hi (0, "CmpItemAbbrMatchFuzzy", { bold = true })
	hi (0, "CmpItemKind", { fg = "#c6c6cd" })
	hi (0, "CmpItemKindClass", { link = "Type" })
	hi (0, "CmpItemKindColor", { link = "Special" })
	hi (0, "CmpItemKindConstant", { link = "Constant" })
	hi (0, "CmpItemKindConstructor", { link = "Type" })
	hi (0, "CmpItemKindEnum", { link = "Structure" })
	hi (0, "CmpItemKindEnumMember", { link = "Structure" })
	hi (0, "CmpItemKindEvent", { link = "Exception" })
	hi (0, "CmpItemKindField", { link = "Structure" })
	hi (0, "CmpItemKindFile", { link = "Tag" })
	hi (0, "CmpItemKindFolder", { link = "Directory" })
	hi (0, "CmpItemKindFunction", { link = "Function" })
	hi (0, "CmpItemKindInterface", { link = "Structure" })
	hi (0, "CmpItemKindKeyword", { link = "Keyword" })
	hi (0, "CmpItemKindMethod", { link = "Function" })
	hi (0, "CmpItemKindModule", { link = "Structure" })
	hi (0, "CmpItemKindOperator", { link = "Operator" })
	hi (0, "CmpItemKindProperty", { link = "Structure" })
	hi (0, "CmpItemKindReference", { link = "Tag" })
	hi (0, "CmpItemKindSnippet", { link = "Special" })
	hi (0, "CmpItemKindStruct", { link = "Structure" })
	hi (0, "CmpItemKindText", { link = "Normal" })
	hi (0, "CmpItemKindTypeParameter", { link = "Type" })
	hi (0, "CmpItemKindUnit", { link = "Special" })
	hi (0, "CmpItemKindValue", { link = "Identifier" })
	hi (0, "CmpItemKindVariable", { link = "Delimiter" })
	hi (0, "CmpItemMenu", { fg = "#c6c6cd" })
	hi (0, "CocBold", { bold = true })
	hi (0, "CocCodeLens", { link = "LspCodeLens" })
	hi (0, "CocCursorTransparent", { blend = 100, strikethrough = true })
	hi (0, "CocDisabled", { fg = "#87878e" })
	hi (0, "CocFadeOut", { fg = "#87878e" })
	hi (0, "CocInlayHint", { ctermfg = 151, fg = "#aad2bf" })
	hi (0, "CocItalic", { italic = true })
	hi (0, "CocLink", { sp = "#15aabf", underline = true })
	hi (0, "CocListBgBlack", { bg = "#14161b", ctermbg = 0 })
	hi (0, "CocListBgBlue", { bg = "#a2d0d9", ctermbg = 12 })
	hi (0, "CocListBgCyan", { bg = "#aad2bf", ctermbg = 14 })
	hi (0, "CocListBgGreen", { bg = "#c2cca8", ctermbg = 10 })
	hi (0, "CocListBgGrey", { bg = "#14161b", ctermbg = 248 })
	hi (0, "CocListBgMagenta", { bg = "#cbc0e3", ctermbg = 13 })
	hi (0, "CocListBgRed", { bg = "#e0bace", ctermbg = 9 })
	hi (0, "CocListBgWhite", { bg = "#c6c6cd", ctermbg = 15 })
	hi (0, "CocListBgYellow", { bg = "#dbc3a3", ctermbg = 11 })
	hi (0, "CocListBlackBlack", { bg = "#14161b", fg = "#14161b" })
	hi (0, "CocListBlackBlue", { bg = "#a2d0d9", fg = "#14161b" })
	hi (0, "CocListBlackCyan", { bg = "#aad2bf", fg = "#14161b" })
	hi (0, "CocListBlackGreen", { bg = "#c2cca8", fg = "#14161b" })
	hi (0, "CocListBlackGrey", { bg = "#14161b", fg = "#14161b" })
	hi (0, "CocListBlackMagenta", { bg = "#cbc0e3", fg = "#14161b" })
	hi (0, "CocListBlackRed", { bg = "#e0bace", fg = "#14161b" })
	hi (0, "CocListBlackWhite", { bg = "#c6c6cd", fg = "#14161b" })
	hi (0, "CocListBlackYellow", { bg = "#dbc3a3", fg = "#14161b" })
	hi (0, "CocListBlueBlack", { bg = "#14161b", fg = "#a2d0d9" })
	hi (0, "CocListBlueBlue", { bg = "#a2d0d9", fg = "#a2d0d9" })
	hi (0, "CocListBlueCyan", { bg = "#aad2bf", fg = "#a2d0d9" })
	hi (0, "CocListBlueGreen", { bg = "#c2cca8", fg = "#a2d0d9" })
	hi (0, "CocListBlueGrey", { bg = "#14161b", fg = "#a2d0d9" })
	hi (0, "CocListBlueMagenta", { bg = "#cbc0e3", fg = "#a2d0d9" })
	hi (0, "CocListBlueRed", { bg = "#e0bace", fg = "#a2d0d9" })
	hi (0, "CocListBlueWhite", { bg = "#c6c6cd", fg = "#a2d0d9" })
	hi (0, "CocListBlueYellow", { bg = "#dbc3a3", fg = "#a2d0d9" })
	hi (0, "CocListCyanBlack", { bg = "#14161b", fg = "#aad2bf" })
	hi (0, "CocListCyanBlue", { bg = "#a2d0d9", fg = "#aad2bf" })
	hi (0, "CocListCyanCyan", { bg = "#aad2bf", fg = "#aad2bf" })
	hi (0, "CocListCyanGreen", { bg = "#c2cca8", fg = "#aad2bf" })
	hi (0, "CocListCyanGrey", { bg = "#14161b", fg = "#aad2bf" })
	hi (0, "CocListCyanMagenta", { bg = "#cbc0e3", fg = "#aad2bf" })
	hi (0, "CocListCyanRed", { bg = "#e0bace", fg = "#aad2bf" })
	hi (0, "CocListCyanWhite", { bg = "#c6c6cd", fg = "#aad2bf" })
	hi (0, "CocListCyanYellow", { bg = "#dbc3a3", fg = "#aad2bf" })
	hi (0, "CocListFgBlack", { ctermfg = 0, fg = "#14161b" })
	hi (0, "CocListFgBlue", { ctermfg = 12, fg = "#a2d0d9" })
	hi (0, "CocListFgCyan", { ctermfg = 14, fg = "#aad2bf" })
	hi (0, "CocListFgGreen", { ctermfg = 10, fg = "#c2cca8" })
	hi (0, "CocListFgGrey", { ctermfg = 248, fg = "#14161b" })
	hi (0, "CocListFgMagenta", { ctermfg = 13, fg = "#cbc0e3" })
	hi (0, "CocListFgRed", { ctermfg = 9, fg = "#e0bace" })
	hi (0, "CocListFgWhite", { ctermfg = 15, fg = "#c6c6cd" })
	hi (0, "CocListFgYellow", { ctermfg = 11, fg = "#dbc3a3" })
	hi (0, "CocListGreenBlack", { bg = "#14161b", fg = "#c2cca8" })
	hi (0, "CocListGreenBlue", { bg = "#a2d0d9", fg = "#c2cca8" })
	hi (0, "CocListGreenCyan", { bg = "#aad2bf", fg = "#c2cca8" })
	hi (0, "CocListGreenGreen", { bg = "#c2cca8", fg = "#c2cca8" })
	hi (0, "CocListGreenGrey", { bg = "#14161b", fg = "#c2cca8" })
	hi (0, "CocListGreenMagenta", { bg = "#cbc0e3", fg = "#c2cca8" })
	hi (0, "CocListGreenRed", { bg = "#e0bace", fg = "#c2cca8" })
	hi (0, "CocListGreenWhite", { bg = "#c6c6cd", fg = "#c2cca8" })
	hi (0, "CocListGreenYellow", { bg = "#dbc3a3", fg = "#c2cca8" })
	hi (0, "CocListGreyBlack", { bg = "#14161b", fg = "#14161b" })
	hi (0, "CocListGreyBlue", { bg = "#a2d0d9", fg = "#14161b" })
	hi (0, "CocListGreyCyan", { bg = "#aad2bf", fg = "#14161b" })
	hi (0, "CocListGreyGreen", { bg = "#c2cca8", fg = "#14161b" })
	hi (0, "CocListGreyGrey", { bg = "#14161b", fg = "#14161b" })
	hi (0, "CocListGreyMagenta", { bg = "#cbc0e3", fg = "#14161b" })
	hi (0, "CocListGreyRed", { bg = "#e0bace", fg = "#14161b" })
	hi (0, "CocListGreyWhite", { bg = "#c6c6cd", fg = "#14161b" })
	hi (0, "CocListGreyYellow", { bg = "#dbc3a3", fg = "#14161b" })
	hi (0, "CocListMagentaBlack", { bg = "#14161b", fg = "#cbc0e3" })
	hi (0, "CocListMagentaBlue", { bg = "#a2d0d9", fg = "#cbc0e3" })
	hi (0, "CocListMagentaCyan", { bg = "#aad2bf", fg = "#cbc0e3" })
	hi (0, "CocListMagentaGreen", { bg = "#c2cca8", fg = "#cbc0e3" })
	hi (0, "CocListMagentaGrey", { bg = "#14161b", fg = "#cbc0e3" })
	hi (0, "CocListMagentaMagenta", { bg = "#cbc0e3", fg = "#cbc0e3" })
	hi (0, "CocListMagentaRed", { bg = "#e0bace", fg = "#cbc0e3" })
	hi (0, "CocListMagentaWhite", { bg = "#c6c6cd", fg = "#cbc0e3" })
	hi (0, "CocListMagentaYellow", { bg = "#dbc3a3", fg = "#cbc0e3" })
	hi (0, "CocListRedBlack", { bg = "#14161b", fg = "#e0bace" })
	hi (0, "CocListRedBlue", { bg = "#a2d0d9", fg = "#e0bace" })
	hi (0, "CocListRedCyan", { bg = "#aad2bf", fg = "#e0bace" })
	hi (0, "CocListRedGreen", { bg = "#c2cca8", fg = "#e0bace" })
	hi (0, "CocListRedGrey", { bg = "#14161b", fg = "#e0bace" })
	hi (0, "CocListRedMagenta", { bg = "#cbc0e3", fg = "#e0bace" })
	hi (0, "CocListRedRed", { bg = "#e0bace", fg = "#e0bace" })
	hi (0, "CocListRedWhite", { bg = "#c6c6cd", fg = "#e0bace" })
	hi (0, "CocListRedYellow", { bg = "#dbc3a3", fg = "#e0bace" })
	hi (0, "CocListWhiteBlack", { bg = "#14161b", fg = "#c6c6cd" })
	hi (0, "CocListWhiteBlue", { bg = "#a2d0d9", fg = "#c6c6cd" })
	hi (0, "CocListWhiteCyan", { bg = "#aad2bf", fg = "#c6c6cd" })
	hi (0, "CocListWhiteGreen", { bg = "#c2cca8", fg = "#c6c6cd" })
	hi (0, "CocListWhiteGrey", { bg = "#14161b", fg = "#c6c6cd" })
	hi (0, "CocListWhiteMagenta", { bg = "#cbc0e3", fg = "#c6c6cd" })
	hi (0, "CocListWhiteRed", { bg = "#e0bace", fg = "#c6c6cd" })
	hi (0, "CocListWhiteWhite", { bg = "#c6c6cd", fg = "#c6c6cd" })
	hi (0, "CocListWhiteYellow", { bg = "#dbc3a3", fg = "#c6c6cd" })
	hi (0, "CocListYellowBlack", { bg = "#14161b", fg = "#dbc3a3" })
	hi (0, "CocListYellowBlue", { bg = "#a2d0d9", fg = "#dbc3a3" })
	hi (0, "CocListYellowCyan", { bg = "#aad2bf", fg = "#dbc3a3" })
	hi (0, "CocListYellowGreen", { bg = "#c2cca8", fg = "#dbc3a3" })
	hi (0, "CocListYellowGrey", { bg = "#14161b", fg = "#dbc3a3" })
	hi (0, "CocListYellowMagenta", { bg = "#cbc0e3", fg = "#dbc3a3" })
	hi (0, "CocListYellowRed", { bg = "#e0bace", fg = "#dbc3a3" })
	hi (0, "CocListYellowWhite", { bg = "#c6c6cd", fg = "#dbc3a3" })
	hi (0, "CocListYellowYellow", { bg = "#dbc3a3", fg = "#dbc3a3" })
	hi (0, "CocMarkdownLink", { fg = "#b1c9e8" })
	hi (0, "CocMenuSel", { bg = "#4b4e54" })
	hi (0, "CocNotificationProgress", { link = "CocMarkdownLink" })
	hi (0, "CocPumVirtualText", { link = "CocMarkdownLink" })
	hi (0, "CocSearch", { fg = "#b1c9e8" })
	hi (0, "CocSelectedText", { fg = "#dbc3a3" })
	hi (0, "CocStrikeThrough", { strikethrough = true })
	hi (0, "CocSymbolArray", { ctermfg = 223, fg = "#a2d0d9" })
	hi (0, "CocSymbolBoolean", { ctermfg = 223, fg = "#cbc0e3" })
	hi (0, "CocSymbolClass", { ctermfg = 223, fg = "#aad2bf" })
	hi (0, "CocSymbolColor", { ctermfg = 223, fg = "#cbc0e3" })
	hi (0, "CocSymbolConstant", { ctermfg = 223, fg = "#cbc0e3" })
	hi (0, "CocSymbolConstructor", { ctermfg = 223, fg = "#aad2bf" })
	hi (0, "CocSymbolEnum", { ctermfg = 223, fg = "#c6c6cd" })
	hi (0, "CocSymbolEnumMember", { ctermfg = 223, fg = "#dbc3a3" })
	hi (0, "CocSymbolEvent", { ctermfg = 223, fg = "#cbc0e3" })
	hi (0, "CocSymbolField", { ctermfg = 223, fg = "#dbc3a3" })
	hi (0, "CocSymbolFile", { ctermfg = 223, fg = "#c6c6cd" })
	hi (0, "CocSymbolFolder", { ctermfg = 223, fg = "#a2d0d9" })
	hi (0, "CocSymbolFunction", { ctermfg = 223, fg = "#a2d0d9" })
	hi (0, "CocSymbolInterface", { ctermfg = 223, fg = "#c6c6cd" })
	hi (0, "CocSymbolKey", { ctermfg = 223, fg = "#dbc3a3" })
	hi (0, "CocSymbolKeyword", { ctermfg = 223, fg = "#c6c6cd" })
	hi (0, "CocSymbolMethod", { ctermfg = 223, fg = "#a2d0d9" })
	hi (0, "CocSymbolModule", { ctermfg = 223, fg = "#dbc3a3" })
	hi (0, "CocSymbolNamespace", { ctermfg = 223, fg = "#dbc3a3" })
	hi (0, "CocSymbolNull", { ctermfg = 223, fg = "#c6c6cd" })
	hi (0, "CocSymbolNumber", { ctermfg = 223, fg = "#cbc0e3" })
	hi (0, "CocSymbolObject", { ctermfg = 223, fg = "#a2d0d9" })
	hi (0, "CocSymbolOperator", { ctermfg = 223, fg = "#c6c6cd" })
	hi (0, "CocSymbolPackage", { ctermfg = 223, fg = "#c6c6cd" })
	hi (0, "CocSymbolProperty", { ctermfg = 223, fg = "#dbc3a3" })
	hi (0, "CocSymbolReference", { ctermfg = 223, fg = "#dbc3a3" })
	hi (0, "CocSymbolSnippet", { ctermfg = 223, fg = "#a2d0d9" })
	hi (0, "CocSymbolString", { ctermfg = 223, fg = "#c2cca8" })
	hi (0, "CocSymbolStruct", { ctermfg = 223, fg = "#c6c6cd" })
	hi (0, "CocSymbolText", { ctermfg = 223, fg = "#a2d0d9" })
	hi (0, "CocSymbolTypeParameter", { ctermfg = 223, fg = "#b1c9e8" })
	hi (0, "CocSymbolUnit", { ctermfg = 223, fg = "#a2d0d9" })
	hi (0, "CocSymbolValue", { ctermfg = 223, fg = "#a2d0d9" })
	hi (0, "CocSymbolVariable", { ctermfg = 223, fg = "#aad2bf" })
	hi (0, "CocUnderline", { sp = "#ebdbb2", underline = true })
	hi (0, "CocVirtualText", { ctermfg = 12, fg = "#504945" })
	hi (0, "ColorColumn", { bg = "#4b4e54" })
	hi (0, "Comment", { fg = "#87878e", italic = true })
	hi (0, "Conceal", { fg = "#a2d0d9" })
	hi (0, "Constant", { fg = "#cbc0e3" })
	hi (0, "CurSearch", { bg = "#dbc3a3", fg = "#14161b" })
	hi (0, "Cursor", { bg = "#c6c6cd", fg = "#14161b" })
	hi (0, "CursorColumn", { bg = "#2f3237" })
	hi (0, "CursorLine", { bg = "#2f3237" })
	hi (0, "CursorLineFold", { fg = "#4b4e54" })
	hi (0, "CursorLineNr", { bold = true, fg = "#b9c6e8" })
	hi (0, "CursorLineSign", { fg = "#4b4e54" })
	hi (0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#c2cca8" })
	hi (0, "DapUIBreakpointsDisabledLine", { fg = "#87878e" })
	hi (0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
	hi (0, "DapUIBreakpointsPath", { link = "Directory" })
	hi (0, "DapUIDecoration", { link = "Title" })
	hi (0, "DapUIFloatBorder", { link = "SpecialChar" })
	hi (0, "DapUILineNumber", { link = "Title" })
	hi (0, "DapUIModifiedValue", { bold = true, fg = "#e6bbb4" })
	hi (0, "DapUIScope", { link = "Title" })
	hi (0, "DapUISource", { link = "Directory" })
	hi (0, "DapUIStoppedThread", { link = "Title" })
	hi (0, "DapUIThread", { link = "String" })
	hi (0, "DapUIType", { link = "Type" })
	hi (0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
	hi (0, "DapUIWatchesError", { link = "DiagnosticError" })
	hi (0, "DapUIWatchesValue", { link = "String" })
	hi (0, "DashboardCenter", { link = "Delimiter" })
	hi (0, "DashboardFooter", { fg = "#87878e" })
	hi (0, "DashboardHeader", { link = "Title" })
	hi (0, "DashboardShortCut", { link = "WarningMsg" })
	hi (0, "Definitions", { fg = "#c2cca8" })
	hi (0, "DefinitionsIcon", { fg = "#a2d0d9" })
	hi (0, "Delimiter", { fg = "#e6bbb4" })
	hi (0, "DiagnosticDeprecated", { sp = "#e0bace", strikethrough = true })
	hi (0, "DiagnosticError", { fg = "#e0bace" })
	hi (0, "DiagnosticFloatingError", { fg = "#e0bace" })
	hi (0, "DiagnosticFloatingHint", { fg = "#aad2bf" })
	hi (0, "DiagnosticFloatingInfo", { fg = "#b1c9e8" })
	hi (0, "DiagnosticFloatingOk", { fg = "#c2cca8" })
	hi (0, "DiagnosticFloatingWarn", { fg = "#dbc3a3" })
	hi (0, "DiagnosticHint", { fg = "#aad2bf" })
	hi (0, "DiagnosticInfo", { fg = "#b1c9e8" })
	hi (0, "DiagnosticOk", { fg = "#c2cca8" })
	hi (0, "DiagnosticUnderlineError", { sp = "#e0bace", underline = true })
	hi (0, "DiagnosticUnderlineHint", { sp = "#aad2bf", underline = true })
	hi (0, "DiagnosticUnderlineInfo", { sp = "#b1c9e8", underline = true })
	hi (0, "DiagnosticUnderlineOk", { sp = "#c2cca8", underline = true })
	hi (0, "DiagnosticUnderlineWarn", { sp = "#dbc3a3", underline = true })
	hi (0, "DiagnosticUnnecessary", { fg = "#87878e" })
	hi (0, "DiagnosticWarn", { fg = "#dbc3a3" })
	hi (0, "DiffAdd", { bg = "#151b00" })
	hi (0, "DiffChange", { bg = "#002316" })
	hi (0, "DiffDelete", { bg = "#250b1b" })
	hi (0, "DiffText", { bg = "#291800" })
	hi (0, "Directory", { fg = "#a2d0d9" })
	hi (0, "EndOfBuffer", { fg = "#4b4e54" })
	hi (0, "Error", { bg = "#250b1b" })
	hi (0, "ErrorMsg", { fg = "#e0bace" })
	hi (0, "FinderParam", { fg = "#dbc3a3" })
	hi (0, "FinderSpinner", { fg = "#c2cca8" })
	hi (0, "FinderSpinnerBorder", { fg = "#b9c6e8" })
	hi (0, "FinderSpinnerTitle", { link = "Title" })
	hi (0, "FinderVirtText", { fg = "#e6bbb4" })
	hi (0, "Float", { link = "Constant" })
	hi (0, "FloatBorder", { fg = "#b9c6e8" })
	hi (0, "FloatTitle", { bold = true, fg = "#b9c6e8" })
	hi (0, "FoldColumn", { fg = "#4b4e54" })
	hi (0, "Folded", { bg = "#0b0d12", fg = "#87878e" })
	hi (0, "Function", { fg = "#a2d0d9" })
	hi (0, "GitSignsAdd", { fg = "#c2cca8" })
	hi (0, "GitSignsAddInline", { link = "GitSignsAdd" })
	hi (0, "GitSignsAddLn", { link = "GitSignsAdd" })
	hi (0, "GitSignsChange", { fg = "#dbc3a3" })
	hi (0, "GitSignsChangeInline", { link = "GitSignsChange" })
	hi (0, "GitSignsChangeLn", { link = "GitSignsChange" })
	hi (0, "GitSignsDelete", { fg = "#e0bace" })
	hi (0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
	hi (0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
	hi (0, "GitSignsUntracked", { fg = "#a2d0d9" })
	hi (0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
	hi (0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
	hi (0, "HopNextKey", { bold = true, fg = "#c2cca8", nocombine = true })
	hi (0, "HopNextKey1", { bold = true, fg = "#e6bbb4", nocombine = true })
	hi (0, "HopNextKey2", { bold = true, fg = "#a7a7ad", nocombine = true })
	hi (0, "HopPreview", { bold = true, fg = "#dbc3a3", nocombine = true })
	hi (0, "HopUnmatched", { fg = "#4b4e54" })
	hi (0, "HydraAmaranth", { fg = "#cbc0e3" })
	hi (0, "HydraBlue", { fg = "#a2d0d9" })
	hi (0, "HydraHint", { link = "NormalFloat" })
	hi (0, "HydraPink", { fg = "#e6bbb4" })
	hi (0, "HydraRed", { fg = "#e0bace" })
	hi (0, "HydraTeal", { fg = "#aad2bf" })
	hi (0, "Identifier", { fg = "#dbc3a3" })
	hi (0, "Ignore", {})
	hi (0, "IncSearch", { bg = "#dbc3a3", fg = "#14161b" })
	hi (0, "IndentBlanklineChar", { fg = "#4b4e54", nocombine = true })
	hi (0, "IndentBlanklineContextChar", { fg = "#b9c6e8", nocombine = true })
	hi (0, "IndentBlanklineContextStart", { nocombine = true, sp = "#b9c6e8", underline = true })
	hi (0, "IndentBlanklineIndent1", { fg = "#b1c9e8", nocombine = true })
	hi (0, "IndentBlanklineIndent2", { fg = "#aad2bf", nocombine = true })
	hi (0, "IndentBlanklineIndent3", { fg = "#dbc3a3", nocombine = true })
	hi (0, "IndentBlanklineIndent4", { fg = "#e0bace", nocombine = true })
	hi (0, "IndentBlanklineIndent5", { fg = "#a2d0d9", nocombine = true })
	hi (0, "IndentBlanklineIndent6", { fg = "#c2cca8", nocombine = true })
	hi (0, "IndentBlanklineIndent7", { fg = "#e6bbb4", nocombine = true })
	hi (0, "IndentBlanklineIndent8", { fg = "#cbc0e3", nocombine = true })
	hi (0, "Italic", { italic = true })
	hi (0, "LSOutlinePreviewBorder", { fg = "#b9c6e8" })
	hi (0, "LazyBold", { bold = true })
	hi (0, "LazyButton", { bg = "#2f3237" })
	hi (0, "LazyButtonActive", { bg = "#4b4e54" })
	hi (0, "LazyDimmed", { fg = "#87878e" })
	hi (0, "LazyH1", { bg = "#4b4e54", bold = true, fg = "#b9c6e8" })
	hi (0, "LazyItalic", { italic = true })
	hi (0, "LeapBackdrop", { fg = "#87878e" })
	hi (0, "LeapLabel", { bold = true, fg = "#dbc3a3", nocombine = true })
	hi (0, "LeapLabelSelected", { bold = true, fg = "#aad2bf", nocombine = true })
	hi (0, "LeapMatch", { bold = true, fg = "#c2cca8", nocombine = true, underline = true })
	hi (0, "LineNr", { fg = "#4b4e54" })
	hi (0, "LspCodeLens", { fg = "#87878e" })
	hi (0, "LspCodeLensSeparator", { fg = "#87878e" })
	hi (0, "LspReferenceText", { bg = "#4b4e54" })
	hi (0, "LspSagaAutoPreview", { fg = "#b1c9e8" })
	hi (0, "LspSagaBorderTitle", { link = "FloatTitle" })
	hi (0, "LspSagaCodeActionBorder", { fg = "#b9c6e8" })
	hi (0, "LspSagaCodeActionContent", { fg = "#c6c6cd" })
	hi (0, "LspSagaCodeActionTitle", { bold = true, fg = "#a2d0d9" })
	hi (0, "LspSagaDefPreviewBorder", { fg = "#b9c6e8" })
	hi (0, "LspSagaDiagnosticBorder", { fg = "#b9c6e8" })
	hi (0, "LspSagaDiagnosticHeader", { link = "Title" })
	hi (0, "LspSagaDiagnosticSource", { fg = "#e6bbb4" })
	hi (0, "LspSagaFinderSelection", { fg = "#aad2bf" })
	hi (0, "LspSagaHoverBorder", { fg = "#b9c6e8" })
	hi (0, "LspSagaLspFinderBorder", { fg = "#b9c6e8" })
	hi (0, "LspSagaRenameBorder", { fg = "#b9c6e8" })
	hi (0, "LspSagaSignatureHelpBorder", { fg = "#b9c6e8" })
	hi (0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
	hi (0, "MasonError", { fg = "#e0bace" })
	hi (0, "MasonHeader", { bg = "#a2d0d9", bold = true, fg = "#14161b" })
	hi (0, "MasonHeaderSecondary", { bg = "#b1c9e8", bold = true, fg = "#14161b" })
	hi (0, "MasonHeading", { link = "Bold" })
	hi (0, "MasonHighlight", { fg = "#b9c6e8" })
	hi (0, "MasonHighlightBlock", { bg = "#b9c6e8", fg = "#14161b" })
	hi (0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
	hi (0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
	hi (0, "MasonHighlightBlockSecondary", { bg = "#a2d0d9", fg = "#14161b" })
	hi (0, "MasonHighlightSecondary", { fg = "#a2d0d9" })
	hi (0, "MasonLink", { link = "MasonHighlight" })
	hi (0, "MasonMuted", { fg = "#87878e" })
	hi (0, "MasonMutedBlock", { bg = "#4b4e54", fg = "#14161b" })
	hi (0, "MasonMutedBlockBold", { bg = "#4b4e54", bold = true, fg = "#14161b" })
	hi (0, "MatchParen", { bg = "#4b4e54", bold = true })
	hi (0, "MiniAnimateCursor", { nocombine = true, reverse = true })
	hi (0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
	hi (0, "MiniClueBorder", { link = "FloatBorder" })
	hi (0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
	hi (0, "MiniClueDescSingle", { link = "NormalFloat" })
	hi (0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
	hi (0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
	hi (0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
	hi (0, "MiniClueTitle", { link = "FloatTitle" })
	hi (0, "MiniCompletionActiveParameter", { bg = "#4b4e54" })
	hi (0, "MiniCursorword", { underline = true })
	hi (0, "MiniCursorwordCurrent", { underline = true })
	hi (0, "MiniDepsChangeAdded", { link = "diffAdded" })
	hi (0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
	hi (0, "MiniDepsHint", { link = "DiagnosticHint" })
	hi (0, "MiniDepsInfo", { link = "DiagnosticInfo" })
	hi (0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
	hi (0, "MiniDepsPlaceholder", { fg = "#87878e" })
	hi (0, "MiniDepsTitle", { link = "Title" })
	hi (0, "MiniDepsTitleError", { link = "DiffDelete" })
	hi (0, "MiniDepsTitleSame", { link = "DiffText" })
	hi (0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
	hi (0, "MiniDiffOverAdd", { link = "DiffAdd" })
	hi (0, "MiniDiffOverChange", { link = "DiffText" })
	hi (0, "MiniDiffOverContext", { link = "DiffChange" })
	hi (0, "MiniDiffOverDelete", { link = "DiffDelete" })
	hi (0, "MiniDiffSignAdd", { link = "diffAdded" })
	hi (0, "MiniDiffSignChange", { link = "diffChanged" })
	hi (0, "MiniDiffSignDelete", { link = "diffRemoved" })
	hi (0, "MiniFilesBorder", { link = "FloatBorder" })
	hi (0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
	hi (0, "MiniFilesCursorLine", { link = "CursorLine" })
	hi (0, "MiniFilesDirectory", { link = "Directory" })
	hi (0, "MiniFilesFile", { fg = "#c6c6cd" })
	hi (0, "MiniFilesNormal", { link = "NormalFloat" })
	hi (0, "MiniFilesTitle", { link = "FloatTitle" })
	hi (0, "MiniFilesTitleFocused", { bold = true, fg = "#c6c6cd" })
	hi (0, "MiniHipatternsFixme", { bg = "#e0bace", bold = true, fg = "#14161b", italic = true })
	hi (0, "MiniHipatternsHack", { bg = "#dbc3a3", bold = true, fg = "#14161b", italic = true })
	hi (0, "MiniHipatternsNote", { bg = "#aad2bf", bold = true, fg = "#14161b", italic = true })
	hi (0, "MiniHipatternsTodo", { bg = "#b1c9e8", bold = true, fg = "#14161b", italic = true })
	hi (0, "MiniIconsAzure", { fg = "#a2d0d9" })
	hi (0, "MiniIconsBlue", { fg = "#b1c9e8" })
	hi (0, "MiniIconsCyan", { fg = "#aad2bf" })
	hi (0, "MiniIconsGreen", { fg = "#c2cca8" })
	hi (0, "MiniIconsGrey", { fg = "#d8d8df" })
	hi (0, "MiniIconsOrange", { fg = "#e6bbb4" })
	hi (0, "MiniIconsPurple", { fg = "#cbc0e3" })
	hi (0, "MiniIconsRed", { fg = "#e0bace" })
	hi (0, "MiniIconsYellow", { fg = "#dbc3a3" })
	hi (0, "MiniIndentscopeSymbol", { fg = "#b9c6e8" })
	hi (0, "MiniIndentscopeSymbolOff", { fg = "#e0bace" })
	hi (0, "MiniJump", { sp = "#b9c6e8", undercurl = true })
	hi (0, "MiniJump2dDim", { fg = "#4b4e54" })
	hi (0, "MiniJump2dSpot", { bg = "#030407", bold = true, fg = "#ebebf3", nocombine = true })
	hi (0, "MiniJump2dSpotAhead", { bg = "#030407", fg = "#d8d8df", nocombine = true })
	hi (0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
	hi (0, "MiniMapNormal", { bg = "#0b0d12", fg = "#87878e" })
	hi (0, "MiniMapSymbolCount", { fg = "#87878e" })
	hi (0, "MiniMapSymbolLine", { fg = "#b9c6e8" })
	hi (0, "MiniMapSymbolView", { fg = "#b9c6e8" })
	hi (0, "MiniNotifyBorder", { link = "FloatBorder" })
	hi (0, "MiniNotifyNormal", { link = "NormalFloat" })
	hi (0, "MiniNotifyTitle", { link = "FloatTitle" })
	hi (0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
	hi (0, "MiniPickBorder", { link = "FloatBorder" })
	hi (0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
	hi (0, "MiniPickBorderText", { link = "FloatTitle" })
	hi (0, "MiniPickCursor", { blend = 100, nocombine = true })
	hi (0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
	hi (0, "MiniPickIconDirectory", { link = "Directory" })
	hi (0, "MiniPickIconFile", { link = "MiniPickNormal" })
	hi (0, "MiniPickMatchCurrent", { link = "CursorLine" })
	hi (0, "MiniPickMatchMarked", { link = "Visual" })
	hi (0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
	hi (0, "MiniPickNormal", { link = "NormalFloat" })
	hi (0, "MiniPickPreviewLine", { link = "CursorLine" })
	hi (0, "MiniPickPreviewRegion", { link = "IncSearch" })
	hi (0, "MiniPickPrompt", { link = "DiagnosticFloatingInfo" })
	hi (0, "MiniStarterCurrent", { link = "MiniStarterItem" })
	hi (0, "MiniStarterFooter", { fg = "#87878e" })
	hi (0, "MiniStarterHeader", { bold = true, fg = "#b9c6e8" })
	hi (0, "MiniStarterInactive", { fg = "#87878e" })
	hi (0, "MiniStarterItemBullet", { fg = "#87878e" })
	hi (0, "MiniStarterItemPrefix", { bold = true, fg = "#dbc3a3" })
	hi (0, "MiniStarterQuery", { bold = true, fg = "#c2cca8" })
	hi (0, "MiniStarterSection", { fg = "#cbc0e3" })
	hi (0, "MiniStatuslineDevinfo", { bg = "#2f3237", fg = "#a7a7ad" })
	hi (0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
	hi (0, "MiniStatuslineFilename", { bg = "#14161b", fg = "#a7a7ad" })
	hi (0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
	hi (0, "MiniStatuslineModeCommand", { bg = "#dbc3a3", bold = true, fg = "#14161b" })
	hi (0, "MiniStatuslineModeInsert", { bg = "#a2d0d9", bold = true, fg = "#14161b" })
	hi (0, "MiniStatuslineModeNormal", { bg = "#c6c6cd", bold = true, fg = "#14161b" })
	hi (0, "MiniStatuslineModeOther", { bg = "#aad2bf", bold = true, fg = "#14161b" })
	hi (0, "MiniStatuslineModeReplace", { bg = "#e0bace", bold = true, fg = "#14161b" })
	hi (0, "MiniStatuslineModeVisual", { bg = "#c2cca8", bold = true, fg = "#14161b" })
	hi (0, "MiniSurround", { link = "IncSearch" })
	hi (0, "MiniTablineCurrent", { bg = "#14161b", bold = true, fg = "#b9c6e8" })
	hi (0, "MiniTablineFill", { link = "MiniTablineHidden" })
	hi (0, "MiniTablineHidden", { bg = "#0b0d12", fg = "#a7a7ad" })
	hi (0, "MiniTablineModifiedCurrent", { bg = "#b9c6e8", bold = true, fg = "#14161b" })
	hi (0, "MiniTablineModifiedHidden", { bg = "#a7a7ad", fg = "#0b0d12" })
	hi (0, "MiniTablineModifiedVisible", { bg = "#a7a7ad", bold = true, fg = "#0b0d12" })
	hi (0, "MiniTablineTabpagesection", { bg = "#c2cca8", bold = true, fg = "#14161b" })
	hi (0, "MiniTablineVisible", { bg = "#0b0d12", bold = true, fg = "#a7a7ad" })
	hi (0, "MiniTestEmphasis", { bold = true })
	hi (0, "MiniTestFail", { bold = true, fg = "#e0bace" })
	hi (0, "MiniTestPass", { bold = true, fg = "#c2cca8" })
	hi (0, "MiniTrailspace", { bg = "#250b1b" })
	hi (0, "ModeMsg", { fg = "#c2cca8" })
	hi (0, "MoreMsg", { fg = "#a2d0d9" })
	hi (0, "MsgArea", { link = "Normal" })
	hi (0, "MsgSeparator", { bg = "#4b4e54", fg = "#87878e" })
	hi (0, "NeoTreeDimText", { fg = "#4b4e54" })
	hi (0, "NeoTreeDotfile", { fg = "#a7a7ad" })
	hi (0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
	hi (0, "NeoTreeFadeText2", { fg = "#4b4e54" })
	hi (0, "NeoTreeGitAdded", { fg = "#c2cca8" })
	hi (0, "NeoTreeGitConflict", { bold = true, fg = "#e6bbb4" })
	hi (0, "NeoTreeGitDeleted", { fg = "#e0bace" })
	hi (0, "NeoTreeGitModified", { fg = "#dbc3a3" })
	hi (0, "NeoTreeGitUnstaged", { fg = "#cbc0e3" })
	hi (0, "NeoTreeGitUntracked", { fg = "#aad2bf" })
	hi (0, "NeoTreeMessage", { bg = "#2f3237", fg = "#c6c6cd" })
	hi (0, "NeoTreeModified", { fg = "#d8d8df" })
	hi (0, "NeoTreeRootName", { bold = true, fg = "#b9c6e8" })
	hi (0, "NeoTreeTabInactive", { fg = "#87878e" })
	hi (0, "NeoTreeTabSeparatorActive", { bg = "#4b4e54", fg = "#87878e" })
	hi (0, "NeoTreeTabSeparatorInactive", { bg = "#2f3237", fg = "#2f3237" })
	hi (0, "NeogitCommitViewHeader", { link = "Special" })
	hi (0, "NeogitDiffAdd", { link = "DiffAdd" })
	hi (0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
	hi (0, "NeogitDiffDelete", { link = "DiffDelete" })
	hi (0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
	hi (0, "NeogitFold", { link = "FoldColumn" })
	hi (0, "NeogitHunkHeader", { fg = "#b9c6e8" })
	hi (0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#b9c6e8" })
	hi (0, "NeogitNotificationError", { link = "DiagnosticError" })
	hi (0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
	hi (0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
	hi (0, "NoiceCmdlinePopupBorder", { fg = "#a2d0d9" })
	hi (0, "NoiceConfirmBorder", { fg = "#dbc3a3" })
	hi (0, "NonText", { fg = "#4b4e54" })
	hi (0, "Normal", { bg = "#14161b", fg = "#c6c6cd" })
	hi (0, "NormalFloat", { fg = "#c6c6cd" })
	hi (0, "NormalNC", { link = "Normal" })
	hi (0, "NotifyDEBUGBorder", { fg = "#c2cca8" })
	hi (0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
	hi (0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
	hi (0, "NotifyERRORBorder", { fg = "#e0bace" })
	hi (0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
	hi (0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
	hi (0, "NotifyINFOBorder", { fg = "#b1c9e8" })
	hi (0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
	hi (0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
	hi (0, "NotifyTRACEBorder", { fg = "#aad2bf" })
	hi (0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
	hi (0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
	hi (0, "NotifyWARNBorder", { fg = "#dbc3a3" })
	hi (0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
	hi (0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
	hi (0, "NvimTreeExecFile", { bold = true, fg = "#c2cca8" })
	hi (0, "NvimTreeFolderIcon", { fg = "#87878e" })
	hi (0, "NvimTreeGitDeleted", { fg = "#e0bace" })
	hi (0, "NvimTreeGitDirty", { fg = "#dbc3a3" })
	hi (0, "NvimTreeGitMerge", { fg = "#e6bbb4" })
	hi (0, "NvimTreeGitNew", { fg = "#aad2bf" })
	hi (0, "NvimTreeGitRenamed", { fg = "#cbc0e3" })
	hi (0, "NvimTreeGitStaged", { fg = "#c2cca8" })
	hi (0, "NvimTreeImageFile", { fg = "#e6bbb4" })
	hi (0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
	hi (0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
	hi (0, "NvimTreeRootFolder", { bold = true, fg = "#b9c6e8" })
	hi (0, "NvimTreeSpecialFile", { fg = "#b9c6e8", underline = true })
	hi (0, "NvimTreeSymlink", { bold = true, fg = "#b1c9e8" })
	hi (0, "NvimTreeWindowPicker", { bg = "#4b4e54", bold = true, fg = "#c6c6cd" })
	hi (0, "Operator", { fg = "#c6c6cd" })
	hi (0, "OutlineDetail", { fg = "#4b4e54" })
	hi (0, "OutlineFoldPrefix", { fg = "#dbc3a3" })
	hi (0, "OutlineIndentEvn", { fg = "#87878e" })
	hi (0, "OutlineIndentOdd", { fg = "#c6c6cd" })
	hi (0, "Pmenu", { bg = "#2f3237", fg = "#c6c6cd" })
	hi (0, "PmenuMatch", { bg = "#2f3237", bold = true, fg = "#c6c6cd" })
	hi (0, "PmenuMatchSel", { blend = 0, bold = true, reverse = true })
	hi (0, "PmenuSel", { blend = 0, reverse = true })
	hi (0, "PmenuThumb", { bg = "#4b4e54" })
	hi (0, "PounceAccept", { bg = "#dbc3a3", bold = true, fg = "#14161b", nocombine = true })
	hi (0, "PounceAcceptBest", { bg = "#c2cca8", bold = true, fg = "#14161b", nocombine = true })
	hi (0, "PounceGap", { bg = "#4b4e54", bold = true, fg = "#14161b", nocombine = true })
	hi (0, "PounceMatch", { bg = "#c6c6cd", bold = true, fg = "#14161b", nocombine = true })
	hi (0, "PreProc", { fg = "#b1c9e8" })
	hi (0, "Question", { fg = "#a2d0d9" })
	hi (0, "QuickFixLine", { bold = true })
	hi (0, "RainbowDelimiterBlue", { fg = "#a2d0d9" })
	hi (0, "RainbowDelimiterCyan", { fg = "#aad2bf" })
	hi (0, "RainbowDelimiterGreen", { fg = "#c2cca8" })
	hi (0, "RainbowDelimiterOrange", { fg = "#e6bbb4" })
	hi (0, "RainbowDelimiterRed", { fg = "#e0bace" })
	hi (0, "RainbowDelimiterViolet", { fg = "#cbc0e3" })
	hi (0, "RainbowDelimiterYellow", { fg = "#dbc3a3" })
	hi (0, "References", { fg = "#c2cca8" })
	hi (0, "ReferencesIcon", { fg = "#a2d0d9" })
	hi (0, "Removed", { fg = "#e0bace" })
	hi (0, "Search", { bg = "#b9c6e8", fg = "#14161b" })
	hi (0, "SignColumn", { fg = "#4b4e54" })
	hi (0, "Sneak", { bg = "#e6bbb4", fg = "#14161b" })
	hi (0, "SneakLabel", { bg = "#e6bbb4", bold = true, fg = "#14161b" })
	hi (0, "SneakScope", { bg = "#ebebf3", fg = "#14161b" })
	hi (0, "Special", { fg = "#aad2bf" })
	hi (0, "SpecialKey", { fg = "#4b4e54" })
	hi (0, "SpellBad", { sp = "#e0bace", undercurl = true })
	hi (0, "SpellCap", { sp = "#aad2bf", undercurl = true })
	hi (0, "SpellLocal", { sp = "#dbc3a3", undercurl = true })
	hi (0, "SpellRare", { sp = "#b1c9e8", undercurl = true })
	hi (0, "Statement", { bold = true, fg = "#c6c6cd" })
	hi (0, "StatusLine", { bg = "#14161b", fg = "#a7a7ad" })
	hi (0, "StatusLineNC", { bg = "#0b0d12", fg = "#a7a7ad" })
	hi (0, "String", { fg = "#c2cca8" })
	hi (0, "Substitute", { bg = "#b1c9e8", fg = "#14161b" })
	hi (0, "TabLine", { bg = "#0b0d12", fg = "#a7a7ad" })
	hi (0, "TabLineSel", { bg = "#0b0d12", fg = "#b9c6e8" })
	hi (0, "TargetFileName", { fg = "#c6c6cd" })
	hi (0, "TelescopeBorder", { fg = "#b9c6e8" })
	hi (0, "TelescopeMatching", { bold = true })
	hi (0, "TelescopeMultiSelection", { bg = "#4b4e54" })
	hi (0, "TelescopeSelection", { bg = "#2f3237" })
	hi (0, "TermCursorNC", { reverse = true })
	hi (0, "Title", { fg = "#b9c6e8" })
	hi (0, "Todo", { bg = "#14161b", bold = true, fg = "#b9c6e8", italic = true })
	hi (0, "TroubleCount", { bold = true, fg = "#b9c6e8" })
	hi (0, "TroubleFoldIcon", { bold = true, fg = "#b9c6e8" })
	hi (0, "TroubleIndent", { fg = "#4b4e54" })
	hi (0, "TroubleLocation", { fg = "#a7a7ad" })
	hi (0, "TroubleSignError", { link = "DiagnosticError" })
	hi (0, "TroubleSignHint", { link = "DiagnosticHint" })
	hi (0, "TroubleSignInformation", { link = "DiagnosticInfo" })
	hi (0, "TroubleSignOther", { link = "DiagnosticInfo" })
	hi (0, "TroubleSignWarning", { link = "DiagnosticWarn" })
	hi (0, "TroubleText", { fg = "#c6c6cd" })
	hi (0, "TroubleTextError", { link = "TroubleText" })
	hi (0, "TroubleTextHint", { link = "TroubleText" })
	hi (0, "TroubleTextInformation", { link = "TroubleText" })
	hi (0, "TroubleTextWarning", { link = "TroubleText" })
	hi (0, "Type", { fg = "#c6c6cd" })
	hi (0, "VertSplit", { fg = "#b9c6e8" })
	hi (0, "Visual", { bg = "#4b4e54" })
	hi (0, "VisualNOS", { bg = "#2f3237" })
	hi (0, "WarningMsg", { fg = "#dbc3a3" })
	hi (0, "WhichKey", { fg = "#aad2bf" })
	hi (0, "WhichKeyBorder", { link = "FloatBorder" })
	hi (0, "WhichKeyDesc", { fg = "#c6c6cd" })
	hi (0, "WhichKeyFloat", { bg = "#0b0d12", fg = "#c6c6cd" })
	hi (0, "WhichKeyGroup", { fg = "#e0bace" })
	hi (0, "WhichKeyIconAzure", { link = "MiniIconsAzure" })
	hi (0, "WhichKeyIconBlue", { link = "MiniIconsBlue" })
	hi (0, "WhichKeyIconCyan", { link = "MiniIconsCyan" })
	hi (0, "WhichKeyIconGreen", { link = "MiniIconsGreen" })
	hi (0, "WhichKeyIconGrey", { link = "MiniIconsGrey" })
	hi (0, "WhichKeyIconOrange", { link = "MiniIconsOrange" })
	hi (0, "WhichKeyIconPurple", { link = "MiniIconsPurple" })
	hi (0, "WhichKeyIconRed", { link = "MiniIconsRed" })
	hi (0, "WhichKeyIconYellow", { link = "MiniIconsYellow" })
	hi (0, "WhichKeySeparator", { fg = "#c2cca8" })
	hi (0, "WhichKeyValue", { fg = "#87878e" })
	hi (0, "Whitespace", { fg = "#4b4e54" })
	hi (0, "WinBar", { link = "StatusLine" })
	hi (0, "WinBarNC", { link = "StatusLineNC" })
	hi (0, "WinSeparator", { fg = "#b9c6e8" })
	hi (0, "diffAdded", { fg = "#c2cca8" })
	hi (0, "diffChanged", { fg = "#aad2bf" })
	hi (0, "diffFile", { fg = "#dbc3a3" })
	hi (0, "diffLine", { fg = "#b1c9e8" })
	hi (0, "diffRemoved", { fg = "#e0bace" })
	hi (0, "gitcommitBranch", { bold = true, fg = "#e6bbb4" })
	hi (0, "gitcommitComment", { link = "Comment" })
	hi (0, "gitcommitDiscarded", { fg = "#87878e" })
	hi (0, "gitcommitDiscardedFile", { bold = true, fg = "#dbc3a3" })
	hi (0, "gitcommitDiscardedType", { fg = "#a2d0d9" })
	hi (0, "gitcommitHeader", { link = "Title" })
	hi (0, "gitcommitOverflow", { fg = "#dbc3a3" })
	hi (0, "gitcommitSelected", { fg = "#87878e" })
	hi (0, "gitcommitSelectedFile", { bold = true, fg = "#c2cca8" })
	hi (0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
	hi (0, "gitcommitSummary", { fg = "#c2cca8" })
	hi (0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
	hi (0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
	hi (0, "gitcommitUntracked", { fg = "#87878e" })
	hi (0, "gitcommitUntrackedFile", { fg = "#aad2bf" })
	hi (0, "lCursor", { bg = "#c6c6cd", fg = "#14161b" })

	-- Terminal colors
	local g = vim.g

	g.terminal_color_0 = "#14161b"
	g.terminal_color_1 = "#e0bace"
	g.terminal_color_2 = "#c2cca8"
	g.terminal_color_3 = "#dbc3a3"
	g.terminal_color_4 = "#a2d0d9"
	g.terminal_color_5 = "#cbc0e3"
	g.terminal_color_6 = "#aad2bf"
	g.terminal_color_7 = "#c6c6cd"
	g.terminal_color_8 = "#14161b"
	g.terminal_color_9 = "#e0bace"
	g.terminal_color_10 = "#c2cca8"
	g.terminal_color_11 = "#dbc3a3"
	g.terminal_color_12 = "#a2d0d9"
	g.terminal_color_13 = "#cbc0e3"
	g.terminal_color_14 = "#aad2bf"
	g.terminal_color_15 = "#c6c6cd"
end

if vim.o.background == "light" then
	hi (0, "@character.special", { link = "SpecialChar" })
	hi (0, "@comment.documentation", { link = "@comment" })
	hi (0, "@comment.error", { fg = "#65003d", italic = true })
	hi (0, "@comment.note", { fg = "#007086", italic = true })
	hi (0, "@comment.todo", { bg = "#e0e2ea", bold = true, fg = "#1f1a77", italic = true })
	hi (0, "@comment.warning", { fg = "#7a5800", italic = true })
	hi (0, "@conditional", { link = "Conditional" })
	hi (0, "@constant.builtin", { link = "Special" })
	hi (0, "@constant.macro", { link = "Macro" })
	hi (0, "@debug", { link = "Debug" })
	hi (0, "@define", { link = "Define" })
	hi (0, "@diff.delta", { link = "diffChanged" })
	hi (0, "@diff.minus", { link = "diffRemoved" })
	hi (0, "@diff.plus", { link = "diffAdded" })
	hi (0, "@exception", { link = "Exception" })
	hi (0, "@field", { link = "Identifier" })
	hi (0, "@float", { link = "Float" })
	hi (0, "@function.builtin", { link = "Special" })
	hi (0, "@function.call", { link = "Function" })
	hi (0, "@function.macro", { link = "Macro" })
	hi (0, "@function.method", { link = "@method" })
	hi (0, "@function.method.call", { link = "@method.call" })
	hi (0, "@include", { link = "Include" })
	hi (0, "@keyword.conditional", { link = "@keyword" })
	hi (0, "@keyword.conditional.ternary", { link = "Keyword" })
	hi (0, "@keyword.coroutine", { link = "@keyword" })
	hi (0, "@keyword.debug", { bold = true, fg = "#00775f" })
	hi (0, "@keyword.directive", { bold = true, fg = "#002278" })
	hi (0, "@keyword.directive.define", { link = "@keyword.directive" })
	hi (0, "@keyword.exception", { link = "@keyword" })
	hi (0, "@keyword.function", { link = "@keyword" })
	hi (0, "@keyword.import", { bold = true, fg = "#002278" })
	hi (0, "@keyword.operator", { link = "@keyword" })
	hi (0, "@keyword.repeat", { link = "@keyword" })
	hi (0, "@keyword.return", { bold = true, fg = "#721e00" })
	hi (0, "@keyword.storage", { bold = true, fg = "#2e2f29" })
	hi (0, "@lsp.mod.defaultLibrary", { link = "Special" })
	hi (0, "@lsp.mod.deprecated", { fg = "#65003d" })
	hi (0, "@lsp.type.class", { link = "@structure" })
	hi (0, "@lsp.type.decorator", { link = "@function" })
	hi (0, "@lsp.type.enum", { link = "@type" })
	hi (0, "@lsp.type.enumMember", { link = "@constant" })
	hi (0, "@lsp.type.function", { link = "@function" })
	hi (0, "@lsp.type.interface", { link = "@type" })
	hi (0, "@lsp.type.macro", { link = "@macro" })
	hi (0, "@lsp.type.method", { link = "@method" })
	hi (0, "@lsp.type.namespace", { link = "@namespace" })
	hi (0, "@lsp.type.parameter", { link = "@parameter" })
	hi (0, "@lsp.type.property", { link = "@property" })
	hi (0, "@lsp.type.struct", { link = "@structure" })
	hi (0, "@lsp.type.type", { link = "@type" })
	hi (0, "@lsp.type.typeParameter", { link = "@type.definition" })
	hi (0, "@lsp.type.variable", { link = "@variable" })
	hi (0, "@macro", { link = "Macro" })
	hi (0, "@markup.environment", { link = "@module" })
	hi (0, "@markup.heading", { link = "@text.title" })
	hi (0, "@markup.italic", { link = "@text.emphasis" })
	hi (0, "@markup.link", { link = "@text.reference" })
	hi (0, "@markup.link.label", { link = "@markup.link" })
	hi (0, "@markup.link.url", { fg = "#2e2f29", underline = true })
	hi (0, "@markup.list", { link = "@punctuation.special" })
	hi (0, "@markup.list.checked", { link = "DiagnosticOk" })
	hi (0, "@markup.list.unchecked", { link = "DiagnosticWarn" })
	hi (0, "@markup.math", { link = "@string.special" })
	hi (0, "@markup.quote", { link = "@string.special" })
	hi (0, "@markup.raw", { link = "@text.literal" })
	hi (0, "@markup.raw.block", { link = "@markup.raw" })
	hi (0, "@markup.strikethrough", { link = "@text.strike" })
	hi (0, "@markup.strong", { link = "@text.strong" })
	hi (0, "@markup.underline", { link = "@text.underline" })
	hi (0, "@method", { link = "Function" })
	hi (0, "@method.call", { link = "Function" })
	hi (0, "@module", { link = "@namespace" })
	hi (0, "@module.builtin", { link = "@variable.builtin" })
	hi (0, "@namespace", { link = "Identifier" })
	hi (0, "@none", { link = "Normal" })
	hi (0, "@number.float", { link = "@float" })
	hi (0, "@parameter", { fg = "#002278" })
	hi (0, "@preproc", { link = "PreProc" })
	hi (0, "@punctuation.bracket", { link = "@punctuation" })
	hi (0, "@punctuation.delimiter", { link = "@punctuation" })
	hi (0, "@punctuation.special", { link = "Special" })
	hi (0, "@repeat", { link = "Repeat" })
	hi (0, "@storageclass", { link = "StorageClass" })
	hi (0, "@string.documentation", { link = "@string" })
	hi (0, "@string.escape", { link = "SpecialChar" })
	hi (0, "@string.regexp", { link = "SpecialChar" })
	hi (0, "@string.special", { link = "SpecialChar" })
	hi (0, "@string.special.path", { link = "Directory" })
	hi (0, "@string.special.symbol", { link = "@constant" })
	hi (0, "@string.special.url", { link = "@markup.link.url" })
	hi (0, "@string.special.vimdoc", { link = "@constant" })
	hi (0, "@structure", { link = "Structure" })
	hi (0, "@symbol", { link = "Keyword" })
	hi (0, "@tag.attribute", { link = "@tag" })
	hi (0, "@tag.delimiter", { link = "@punctuation" })
	hi (0, "@text.danger", { link = "ErrorMsg" })
	hi (0, "@text.emphasis", { italic = true })
	hi (0, "@text.literal", { link = "Special" })
	hi (0, "@text.note", { link = "MoreMsg" })
	hi (0, "@text.reference", { link = "Identifier" })
	hi (0, "@text.strike", { strikethrough = true })
	hi (0, "@text.strong", { bold = true })
	hi (0, "@text.title", { link = "Title" })
	hi (0, "@text.todo", { link = "Todo" })
	hi (0, "@text.underline", { link = "Underlined" })
	hi (0, "@text.uri", { link = "Underlined" })
	hi (0, "@text.warning", { link = "WarningMsg" })
	hi (0, "@type.builtin", { link = "Special" })
	hi (0, "@type.definition", { link = "Typedef" })
	hi (0, "@type.qualifier", { link = "StorageClass" })
	hi (0, "@variable", { fg = "#2e2f29" })
	hi (0, "@variable.builtin", { link = "Special" })
	hi (0, "@variable.member", { link = "@field" })
	hi (0, "@variable.parameter", { link = "@parameter" })
	hi (0, "Added", { fg = "#415e00" })
	hi (0, "Beacon", { bg = "#0d0e09" })
	hi (0, "Bold", { bold = true })
	hi (0, "BqfPreviewFloat", { link = "NormalFloat" })
	hi (0, "BqfPreviewTitle", { link = "FloatTitle" })
	hi (0, "BqfSign", { fg = "#00775f" })
	hi (0, "BufferCurrent", { bg = "#e0e2ea", bold = true, fg = "#1f1a77" })
	hi (0, "BufferCurrentIcon", { bg = "#e0e2ea" })
	hi (0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
	hi (0, "BufferCurrentMod", { bg = "#c0c2ca", bold = true, fg = "#1f1a77" })
	hi (0, "BufferCurrentSign", { link = "BufferCurrent" })
	hi (0, "BufferCurrentTarget", { bg = "#a0a2a9", bold = true, fg = "#1f1a77" })
	hi (0, "BufferInactive", { bg = "#e9ebf3", fg = "#2e2f29" })
	hi (0, "BufferInactiveIcon", { bg = "#e9ebf3" })
	hi (0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
	hi (0, "BufferInactiveMod", { bg = "#c0c2ca", fg = "#2e2f29" })
	hi (0, "BufferInactiveSign", { link = "BufferInactive" })
	hi (0, "BufferInactiveTarget", { bg = "#a0a2a9", fg = "#2e2f29" })
	hi (0, "BufferLineBuffer", { fg = "#666761" })
	hi (0, "BufferLineBufferSelected", { bold = true, fg = "#2e2f29" })
	hi (0, "BufferLineBufferVisible", { fg = "#2e2f29" })
	hi (0, "BufferLineCloseButton", { link = "BufferLineBackground" })
	hi (0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
	hi (0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
	hi (0, "BufferLineFill", { link = "Normal" })
	hi (0, "BufferLineTab", { bg = "#415e00", fg = "#e0e2ea" })
	hi (0, "BufferLineTabSelected", { bg = "#415e00", bold = true, fg = "#e0e2ea" })
	hi (0, "BufferOffset", { link = "Normal" })
	hi (0, "BufferTabpageFill", { link = "Normal" })
	hi (0, "BufferTabpages", { bg = "#415e00", bold = true, fg = "#e0e2ea" })
	hi (0, "BufferVisible", { bg = "#e0e2ea", bold = true, fg = "#2e2f29" })
	hi (0, "BufferVisibleIcon", { bg = "#e0e2ea" })
	hi (0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
	hi (0, "BufferVisibleMod", { bg = "#c0c2ca", bold = true, fg = "#2e2f29" })
	hi (0, "BufferVisibleSign", { link = "BufferVisible" })
	hi (0, "BufferVisibleTarget", { bg = "#a0a2a9", bold = true, fg = "#2e2f29" })
	hi (0, "Changed", { fg = "#00775f" })
	hi (0, "CmpItemAbbr", { fg = "#2e2f29" })
	hi (0, "CmpItemAbbrDeprecated", { fg = "#666761", strikethrough = true })
	hi (0, "CmpItemAbbrMatch", { bold = true })
	hi (0, "CmpItemAbbrMatchFuzzy", { bold = true })
	hi (0, "CmpItemKind", { fg = "#2e2f29" })
	hi (0, "CmpItemKindClass", { link = "Type" })
	hi (0, "CmpItemKindColor", { link = "Special" })
	hi (0, "CmpItemKindConstant", { link = "Constant" })
	hi (0, "CmpItemKindConstructor", { link = "Type" })
	hi (0, "CmpItemKindEnum", { link = "Structure" })
	hi (0, "CmpItemKindEnumMember", { link = "Structure" })
	hi (0, "CmpItemKindEvent", { link = "Exception" })
	hi (0, "CmpItemKindField", { link = "Structure" })
	hi (0, "CmpItemKindFile", { link = "Tag" })
	hi (0, "CmpItemKindFolder", { link = "Directory" })
	hi (0, "CmpItemKindFunction", { link = "Function" })
	hi (0, "CmpItemKindInterface", { link = "Structure" })
	hi (0, "CmpItemKindKeyword", { link = "Keyword" })
	hi (0, "CmpItemKindMethod", { link = "Function" })
	hi (0, "CmpItemKindModule", { link = "Structure" })
	hi (0, "CmpItemKindOperator", { link = "Operator" })
	hi (0, "CmpItemKindProperty", { link = "Structure" })
	hi (0, "CmpItemKindReference", { link = "Tag" })
	hi (0, "CmpItemKindSnippet", { link = "Special" })
	hi (0, "CmpItemKindStruct", { link = "Structure" })
	hi (0, "CmpItemKindText", { link = "Normal" })
	hi (0, "CmpItemKindTypeParameter", { link = "Type" })
	hi (0, "CmpItemKindUnit", { link = "Special" })
	hi (0, "CmpItemKindValue", { link = "Identifier" })
	hi (0, "CmpItemKindVariable", { link = "Delimiter" })
	hi (0, "CmpItemMenu", { fg = "#2e2f29" })
	hi (0, "CocCodeLens", { link = "LspCodeLens" })
	hi (0, "CocCursorTransparent", { blend = 100, strikethrough = true })
	hi (0, "CocDisabled", { fg = "#666761" })
	hi (0, "CocFadeOut", { fg = "#666761" })
	hi (0, "CocInlayHint", { ctermfg = 29, fg = "#00775f" })
	hi (0, "CocMarkdownLink", { fg = "#002278" })
	hi (0, "CocMenuSel", { bg = "#a0a2a9" })
	hi (0, "CocNotificationProgress", { link = "CocMarkdownLink" })
	hi (0, "CocPumVirtualText", { link = "CocMarkdownLink" })
	hi (0, "CocSearch", { fg = "#002278" })
	hi (0, "CocSelectedText", { fg = "#7a5800" })
	hi (0, "CocSymbolArray", { ctermfg = 223, fg = "#007086" })
	hi (0, "CocSymbolBoolean", { ctermfg = 223, fg = "#430467" })
	hi (0, "CocSymbolClass", { ctermfg = 223, fg = "#00775f" })
	hi (0, "CocSymbolColor", { ctermfg = 223, fg = "#430467" })
	hi (0, "CocSymbolConstant", { ctermfg = 223, fg = "#430467" })
	hi (0, "CocSymbolConstructor", { ctermfg = 223, fg = "#00775f" })
	hi (0, "CocSymbolEnum", { ctermfg = 223, fg = "#2e2f29" })
	hi (0, "CocSymbolEnumMember", { ctermfg = 223, fg = "#7a5800" })
	hi (0, "CocSymbolEvent", { ctermfg = 223, fg = "#430467" })
	hi (0, "CocSymbolField", { ctermfg = 223, fg = "#7a5800" })
	hi (0, "CocSymbolFile", { ctermfg = 223, fg = "#2e2f29" })
	hi (0, "CocSymbolFolder", { ctermfg = 223, fg = "#007086" })
	hi (0, "CocSymbolFunction", { ctermfg = 223, fg = "#007086" })
	hi (0, "CocSymbolInterface", { ctermfg = 223, fg = "#2e2f29" })
	hi (0, "CocSymbolKey", { ctermfg = 223, fg = "#7a5800" })
	hi (0, "CocSymbolKeyword", { ctermfg = 223, fg = "#2e2f29" })
	hi (0, "CocSymbolMethod", { ctermfg = 223, fg = "#007086" })
	hi (0, "CocSymbolModule", { ctermfg = 223, fg = "#7a5800" })
	hi (0, "CocSymbolNamespace", { ctermfg = 223, fg = "#7a5800" })
	hi (0, "CocSymbolNull", { ctermfg = 223, fg = "#2e2f29" })
	hi (0, "CocSymbolNumber", { ctermfg = 223, fg = "#430467" })
	hi (0, "CocSymbolObject", { ctermfg = 223, fg = "#007086" })
	hi (0, "CocSymbolOperator", { ctermfg = 223, fg = "#2e2f29" })
	hi (0, "CocSymbolPackage", { ctermfg = 223, fg = "#2e2f29" })
	hi (0, "CocSymbolProperty", { ctermfg = 223, fg = "#7a5800" })
	hi (0, "CocSymbolReference", { ctermfg = 223, fg = "#7a5800" })
	hi (0, "CocSymbolSnippet", { ctermfg = 223, fg = "#007086" })
	hi (0, "CocSymbolString", { ctermfg = 223, fg = "#415e00" })
	hi (0, "CocSymbolStruct", { ctermfg = 223, fg = "#2e2f29" })
	hi (0, "CocSymbolText", { ctermfg = 223, fg = "#007086" })
	hi (0, "CocSymbolTypeParameter", { ctermfg = 223, fg = "#002278" })
	hi (0, "CocSymbolUnit", { ctermfg = 223, fg = "#007086" })
	hi (0, "CocSymbolValue", { ctermfg = 223, fg = "#007086" })
	hi (0, "CocSymbolVariable", { ctermfg = 223, fg = "#00775f" })
	hi (0, "ColorColumn", { bg = "#a0a2a9" })
	hi (0, "Comment", { fg = "#666761", italic = true })
	hi (0, "Conceal", { fg = "#007086" })
	hi (0, "Constant", { fg = "#430467" })
	hi (0, "CurSearch", { bg = "#7a5800", fg = "#e0e2ea" })
	hi (0, "Cursor", { bg = "#2e2f29", fg = "#e0e2ea" })
	hi (0, "CursorColumn", { bg = "#c0c2ca" })
	hi (0, "CursorLine", { bg = "#c0c2ca" })
	hi (0, "CursorLineFold", { fg = "#a0a2a9" })
	hi (0, "CursorLineNr", { bold = true, fg = "#1f1a77" })
	hi (0, "CursorLineSign", { fg = "#a0a2a9" })
	hi (0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#415e00" })
	hi (0, "DapUIBreakpointsDisabledLine", { fg = "#666761" })
	hi (0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
	hi (0, "DapUIBreakpointsPath", { link = "Directory" })
	hi (0, "DapUIDecoration", { link = "Title" })
	hi (0, "DapUIFloatBorder", { link = "SpecialChar" })
	hi (0, "DapUILineNumber", { link = "Title" })
	hi (0, "DapUIModifiedValue", { bold = true, fg = "#721e00" })
	hi (0, "DapUIScope", { link = "Title" })
	hi (0, "DapUISource", { link = "Directory" })
	hi (0, "DapUIStoppedThread", { link = "Title" })
	hi (0, "DapUIThread", { link = "String" })
	hi (0, "DapUIType", { link = "Type" })
	hi (0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
	hi (0, "DapUIWatchesError", { link = "DiagnosticError" })
	hi (0, "DapUIWatchesValue", { link = "String" })
	hi (0, "DashboardCenter", { link = "Delimiter" })
	hi (0, "DashboardFooter", { fg = "#666761" })
	hi (0, "DashboardHeader", { link = "Title" })
	hi (0, "DashboardShortCut", { link = "WarningMsg" })
	hi (0, "Definitions", { fg = "#415e00" })
	hi (0, "DefinitionsIcon", { fg = "#007086" })
	hi (0, "Delimiter", { fg = "#721e00" })
	hi (0, "DiagnosticDeprecated", { sp = "#65003d", strikethrough = true })
	hi (0, "DiagnosticError", { fg = "#65003d" })
	hi (0, "DiagnosticFloatingError", { fg = "#65003d" })
	hi (0, "DiagnosticFloatingHint", { fg = "#00775f" })
	hi (0, "DiagnosticFloatingInfo", { fg = "#002278" })
	hi (0, "DiagnosticFloatingOk", { fg = "#415e00" })
	hi (0, "DiagnosticFloatingWarn", { fg = "#7a5800" })
	hi (0, "DiagnosticHint", { fg = "#00775f" })
	hi (0, "DiagnosticInfo", { fg = "#002278" })
	hi (0, "DiagnosticOk", { fg = "#415e00" })
	hi (0, "DiagnosticUnderlineError", { sp = "#65003d", underline = true })
	hi (0, "DiagnosticUnderlineHint", { sp = "#00775f", underline = true })
	hi (0, "DiagnosticUnderlineInfo", { sp = "#002278", underline = true })
	hi (0, "DiagnosticUnderlineOk", { sp = "#415e00", underline = true })
	hi (0, "DiagnosticUnderlineWarn", { sp = "#7a5800", underline = true })
	hi (0, "DiagnosticUnnecessary", { fg = "#666761" })
	hi (0, "DiagnosticWarn", { fg = "#7a5800" })
	hi (0, "DiffAdd", { bg = "#c7f584" })
	hi (0, "DiffChange", { bg = "#6dffd8" })
	hi (0, "DiffDelete", { bg = "#ffafd7" })
	hi (0, "DiffText", { bg = "#ffd584" })
	hi (0, "Directory", { fg = "#007086" })
	hi (0, "EndOfBuffer", { fg = "#a0a2a9" })
	hi (0, "Error", { bg = "#ffafd7" })
	hi (0, "ErrorMsg", { fg = "#65003d" })
	hi (0, "FinderParam", { fg = "#7a5800" })
	hi (0, "FinderSpinner", { fg = "#415e00" })
	hi (0, "FinderSpinnerBorder", { fg = "#1f1a77" })
	hi (0, "FinderSpinnerTitle", { link = "Title" })
	hi (0, "FinderVirtText", { fg = "#721e00" })
	hi (0, "Float", { link = "Constant" })
	hi (0, "FloatBorder", { fg = "#1f1a77" })
	hi (0, "FloatTitle", { bold = true, fg = "#1f1a77" })
	hi (0, "FoldColumn", { fg = "#a0a2a9" })
	hi (0, "Folded", { bg = "#e9ebf3", fg = "#666761" })
	hi (0, "Function", { fg = "#007086" })
	hi (0, "GitSignsAdd", { fg = "#415e00" })
	hi (0, "GitSignsAddInline", { link = "GitSignsAdd" })
	hi (0, "GitSignsAddLn", { link = "GitSignsAdd" })
	hi (0, "GitSignsChange", { fg = "#7a5800" })
	hi (0, "GitSignsChangeInline", { link = "GitSignsChange" })
	hi (0, "GitSignsChangeLn", { link = "GitSignsChange" })
	hi (0, "GitSignsDelete", { fg = "#65003d" })
	hi (0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
	hi (0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
	hi (0, "GitSignsUntracked", { fg = "#007086" })
	hi (0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
	hi (0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
	hi (0, "HopNextKey", { bold = true, fg = "#415e00", nocombine = true })
	hi (0, "HopNextKey1", { bold = true, fg = "#721e00", nocombine = true })
	hi (0, "HopNextKey2", { bold = true, fg = "#494a44", nocombine = true })
	hi (0, "HopPreview", { bold = true, fg = "#7a5800", nocombine = true })
	hi (0, "HopUnmatched", { fg = "#a0a2a9" })
	hi (0, "HydraAmaranth", { fg = "#430467" })
	hi (0, "HydraBlue", { fg = "#007086" })
	hi (0, "HydraHint", { link = "NormalFloat" })
	hi (0, "HydraPink", { fg = "#721e00" })
	hi (0, "HydraRed", { fg = "#65003d" })
	hi (0, "HydraTeal", { fg = "#00775f" })
	hi (0, "Identifier", { fg = "#7a5800" })
	hi (0, "Ignore", {})
	hi (0, "IncSearch", { bg = "#7a5800", fg = "#e0e2ea" })
	hi (0, "IndentBlanklineChar", { fg = "#a0a2a9", nocombine = true })
	hi (0, "IndentBlanklineContextChar", { fg = "#1f1a77", nocombine = true })
	hi (0, "IndentBlanklineContextStart", { nocombine = true, sp = "#1f1a77", underline = true })
	hi (0, "IndentBlanklineIndent1", { fg = "#002278", nocombine = true })
	hi (0, "IndentBlanklineIndent2", { fg = "#00775f", nocombine = true })
	hi (0, "IndentBlanklineIndent3", { fg = "#7a5800", nocombine = true })
	hi (0, "IndentBlanklineIndent4", { fg = "#65003d", nocombine = true })
	hi (0, "IndentBlanklineIndent5", { fg = "#007086", nocombine = true })
	hi (0, "IndentBlanklineIndent6", { fg = "#415e00", nocombine = true })
	hi (0, "IndentBlanklineIndent7", { fg = "#721e00", nocombine = true })
	hi (0, "IndentBlanklineIndent8", { fg = "#430467", nocombine = true })
	hi (0, "Italic", { italic = true })
	hi (0, "LSOutlinePreviewBorder", { fg = "#1f1a77" })
	hi (0, "LazyBold", { bold = true })
	hi (0, "LazyButton", { bg = "#c0c2ca" })
	hi (0, "LazyButtonActive", { bg = "#a0a2a9" })
	hi (0, "LazyDimmed", { fg = "#666761" })
	hi (0, "LazyH1", { bg = "#a0a2a9", bold = true, fg = "#1f1a77" })
	hi (0, "LazyItalic", { italic = true })
	hi (0, "LeapBackdrop", { fg = "#666761" })
	hi (0, "LeapLabel", { bold = true, fg = "#7a5800", nocombine = true })
	hi (0, "LeapLabelSelected", { bold = true, fg = "#00775f", nocombine = true })
	hi (0, "LeapMatch", { bold = true, fg = "#415e00", nocombine = true, underline = true })
	hi (0, "LineNr", { fg = "#a0a2a9" })
	hi (0, "LspCodeLens", { fg = "#666761" })
	hi (0, "LspCodeLensSeparator", { fg = "#666761" })
	hi (0, "LspReferenceText", { bg = "#a0a2a9" })
	hi (0, "LspSagaAutoPreview", { fg = "#002278" })
	hi (0, "LspSagaBorderTitle", { link = "FloatTitle" })
	hi (0, "LspSagaCodeActionBorder", { fg = "#1f1a77" })
	hi (0, "LspSagaCodeActionContent", { fg = "#2e2f29" })
	hi (0, "LspSagaCodeActionTitle", { bold = true, fg = "#007086" })
	hi (0, "LspSagaDefPreviewBorder", { fg = "#1f1a77" })
	hi (0, "LspSagaDiagnosticBorder", { fg = "#1f1a77" })
	hi (0, "LspSagaDiagnosticHeader", { link = "Title" })
	hi (0, "LspSagaDiagnosticSource", { fg = "#721e00" })
	hi (0, "LspSagaFinderSelection", { fg = "#00775f" })
	hi (0, "LspSagaHoverBorder", { fg = "#1f1a77" })
	hi (0, "LspSagaLspFinderBorder", { fg = "#1f1a77" })
	hi (0, "LspSagaRenameBorder", { fg = "#1f1a77" })
	hi (0, "LspSagaSignatureHelpBorder", { fg = "#1f1a77" })
	hi (0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
	hi (0, "MasonError", { fg = "#65003d" })
	hi (0, "MasonHeader", { bg = "#007086", bold = true, fg = "#e0e2ea" })
	hi (0, "MasonHeaderSecondary", { bg = "#002278", bold = true, fg = "#e0e2ea" })
	hi (0, "MasonHeading", { link = "Bold" })
	hi (0, "MasonHighlight", { fg = "#1f1a77" })
	hi (0, "MasonHighlightBlock", { bg = "#1f1a77", fg = "#e0e2ea" })
	hi (0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
	hi (0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
	hi (0, "MasonHighlightBlockSecondary", { bg = "#007086", fg = "#e0e2ea" })
	hi (0, "MasonHighlightSecondary", { fg = "#007086" })
	hi (0, "MasonLink", { link = "MasonHighlight" })
	hi (0, "MasonMuted", { fg = "#666761" })
	hi (0, "MasonMutedBlock", { bg = "#a0a2a9", fg = "#e0e2ea" })
	hi (0, "MasonMutedBlockBold", { bg = "#a0a2a9", bold = true, fg = "#e0e2ea" })
	hi (0, "MatchParen", { bg = "#a0a2a9", bold = true })
	hi (0, "MiniAnimateCursor", { nocombine = true, reverse = true })
	hi (0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
	hi (0, "MiniClueBorder", { link = "FloatBorder" })
	hi (0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
	hi (0, "MiniClueDescSingle", { link = "NormalFloat" })
	hi (0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
	hi (0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
	hi (0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
	hi (0, "MiniClueTitle", { link = "FloatTitle" })
	hi (0, "MiniCompletionActiveParameter", { bg = "#a0a2a9" })
	hi (0, "MiniCursorword", { underline = true })
	hi (0, "MiniCursorwordCurrent", { underline = true })
	hi (0, "MiniDepsChangeAdded", { link = "diffAdded" })
	hi (0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
	hi (0, "MiniDepsHint", { link = "DiagnosticHint" })
	hi (0, "MiniDepsInfo", { link = "DiagnosticInfo" })
	hi (0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
	hi (0, "MiniDepsPlaceholder", { fg = "#666761" })
	hi (0, "MiniDepsTitle", { link = "Title" })
	hi (0, "MiniDepsTitleError", { link = "DiffDelete" })
	hi (0, "MiniDepsTitleSame", { link = "DiffText" })
	hi (0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
	hi (0, "MiniDiffOverAdd", { link = "DiffAdd" })
	hi (0, "MiniDiffOverChange", { link = "DiffText" })
	hi (0, "MiniDiffOverContext", { link = "DiffChange" })
	hi (0, "MiniDiffOverDelete", { link = "DiffDelete" })
	hi (0, "MiniDiffSignAdd", { link = "diffAdded" })
	hi (0, "MiniDiffSignChange", { link = "diffChanged" })
	hi (0, "MiniDiffSignDelete", { link = "diffRemoved" })
	hi (0, "MiniFilesBorder", { link = "FloatBorder" })
	hi (0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
	hi (0, "MiniFilesCursorLine", { link = "CursorLine" })
	hi (0, "MiniFilesDirectory", { link = "Directory" })
	hi (0, "MiniFilesFile", { fg = "#2e2f29" })
	hi (0, "MiniFilesNormal", { link = "NormalFloat" })
	hi (0, "MiniFilesTitle", { link = "FloatTitle" })
	hi (0, "MiniFilesTitleFocused", { bold = true, fg = "#2e2f29" })
	hi (0, "MiniHipatternsFixme", { bg = "#65003d", bold = true, fg = "#e0e2ea", italic = true })
	hi (0, "MiniHipatternsHack", { bg = "#7a5800", bold = true, fg = "#e0e2ea", italic = true })
	hi (0, "MiniHipatternsNote", { bg = "#00775f", bold = true, fg = "#e0e2ea", italic = true })
	hi (0, "MiniHipatternsTodo", { bg = "#002278", bold = true, fg = "#e0e2ea", italic = true })
	hi (0, "MiniIconsAzure", { fg = "#007086" })
	hi (0, "MiniIconsBlue", { fg = "#002278" })
	hi (0, "MiniIconsCyan", { fg = "#00775f" })
	hi (0, "MiniIconsGreen", { fg = "#415e00" })
	hi (0, "MiniIconsGrey", { fg = "#1e1f1a" })
	hi (0, "MiniIconsOrange", { fg = "#721e00" })
	hi (0, "MiniIconsPurple", { fg = "#430467" })
	hi (0, "MiniIconsRed", { fg = "#65003d" })
	hi (0, "MiniIconsYellow", { fg = "#7a5800" })
	hi (0, "MiniIndentscopeSymbol", { fg = "#1f1a77" })
	hi (0, "MiniIndentscopeSymbolOff", { fg = "#65003d" })
	hi (0, "MiniJump", { sp = "#1f1a77", undercurl = true })
	hi (0, "MiniJump2dDim", { fg = "#a0a2a9" })
	hi (0, "MiniJump2dSpot", { bg = "#f3f5fd", bold = true, fg = "#0d0e09", nocombine = true })
	hi (0, "MiniJump2dSpotAhead", { bg = "#f3f5fd", fg = "#1e1f1a", nocombine = true })
	hi (0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
	hi (0, "MiniMapNormal", { bg = "#e9ebf3", fg = "#666761" })
	hi (0, "MiniMapSymbolCount", { fg = "#666761" })
	hi (0, "MiniMapSymbolLine", { fg = "#1f1a77" })
	hi (0, "MiniMapSymbolView", { fg = "#1f1a77" })
	hi (0, "MiniNotifyBorder", { link = "FloatBorder" })
	hi (0, "MiniNotifyNormal", { link = "NormalFloat" })
	hi (0, "MiniNotifyTitle", { link = "FloatTitle" })
	hi (0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
	hi (0, "MiniPickBorder", { link = "FloatBorder" })
	hi (0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
	hi (0, "MiniPickBorderText", { link = "FloatTitle" })
	hi (0, "MiniPickCursor", { blend = 100, nocombine = true })
	hi (0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
	hi (0, "MiniPickIconDirectory", { link = "Directory" })
	hi (0, "MiniPickIconFile", { link = "MiniPickNormal" })
	hi (0, "MiniPickMatchCurrent", { link = "CursorLine" })
	hi (0, "MiniPickMatchMarked", { link = "Visual" })
	hi (0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
	hi (0, "MiniPickNormal", { link = "NormalFloat" })
	hi (0, "MiniPickPreviewLine", { link = "CursorLine" })
	hi (0, "MiniPickPreviewRegion", { link = "IncSearch" })
	hi (0, "MiniPickPrompt", { link = "DiagnosticFloatingInfo" })
	hi (0, "MiniStarterCurrent", { link = "MiniStarterItem" })
	hi (0, "MiniStarterFooter", { fg = "#666761" })
	hi (0, "MiniStarterHeader", { bold = true, fg = "#1f1a77" })
	hi (0, "MiniStarterInactive", { fg = "#666761" })
	hi (0, "MiniStarterItemBullet", { fg = "#666761" })
	hi (0, "MiniStarterItemPrefix", { bold = true, fg = "#7a5800" })
	hi (0, "MiniStarterQuery", { bold = true, fg = "#415e00" })
	hi (0, "MiniStarterSection", { fg = "#430467" })
	hi (0, "MiniStatuslineDevinfo", { bg = "#c0c2ca", fg = "#494a44" })
	hi (0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
	hi (0, "MiniStatuslineFilename", { bg = "#e0e2ea", fg = "#494a44" })
	hi (0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
	hi (0, "MiniStatuslineModeCommand", { bg = "#7a5800", bold = true, fg = "#e0e2ea" })
	hi (0, "MiniStatuslineModeInsert", { bg = "#007086", bold = true, fg = "#e0e2ea" })
	hi (0, "MiniStatuslineModeNormal", { bg = "#2e2f29", bold = true, fg = "#e0e2ea" })
	hi (0, "MiniStatuslineModeOther", { bg = "#00775f", bold = true, fg = "#e0e2ea" })
	hi (0, "MiniStatuslineModeReplace", { bg = "#65003d", bold = true, fg = "#e0e2ea" })
	hi (0, "MiniStatuslineModeVisual", { bg = "#415e00", bold = true, fg = "#e0e2ea" })
	hi (0, "MiniSurround", { link = "IncSearch" })
	hi (0, "MiniTablineCurrent", { bg = "#e0e2ea", bold = true, fg = "#1f1a77" })
	hi (0, "MiniTablineFill", { link = "MiniTablineHidden" })
	hi (0, "MiniTablineHidden", { bg = "#e9ebf3", fg = "#494a44" })
	hi (0, "MiniTablineModifiedCurrent", { bg = "#1f1a77", bold = true, fg = "#e0e2ea" })
	hi (0, "MiniTablineModifiedHidden", { bg = "#494a44", fg = "#e9ebf3" })
	hi (0, "MiniTablineModifiedVisible", { bg = "#494a44", bold = true, fg = "#e9ebf3" })
	hi (0, "MiniTablineTabpagesection", { bg = "#415e00", bold = true, fg = "#e0e2ea" })
	hi (0, "MiniTablineVisible", { bg = "#e9ebf3", bold = true, fg = "#494a44" })
	hi (0, "MiniTestEmphasis", { bold = true })
	hi (0, "MiniTestFail", { bold = true, fg = "#65003d" })
	hi (0, "MiniTestPass", { bold = true, fg = "#415e00" })
	hi (0, "MiniTrailspace", { bg = "#ffafd7" })
	hi (0, "ModeMsg", { fg = "#415e00" })
	hi (0, "MoreMsg", { fg = "#007086" })
	hi (0, "MsgArea", { link = "Normal" })
	hi (0, "MsgSeparator", { bg = "#a0a2a9", fg = "#666761" })
	hi (0, "NeoTreeDimText", { fg = "#a0a2a9" })
	hi (0, "NeoTreeDotfile", { fg = "#494a44" })
	hi (0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
	hi (0, "NeoTreeFadeText2", { fg = "#a0a2a9" })
	hi (0, "NeoTreeGitAdded", { fg = "#415e00" })
	hi (0, "NeoTreeGitConflict", { bold = true, fg = "#721e00" })
	hi (0, "NeoTreeGitDeleted", { fg = "#65003d" })
	hi (0, "NeoTreeGitModified", { fg = "#7a5800" })
	hi (0, "NeoTreeGitUnstaged", { fg = "#430467" })
	hi (0, "NeoTreeGitUntracked", { fg = "#00775f" })
	hi (0, "NeoTreeMessage", { bg = "#c0c2ca", fg = "#2e2f29" })
	hi (0, "NeoTreeModified", { fg = "#1e1f1a" })
	hi (0, "NeoTreeRootName", { bold = true, fg = "#1f1a77" })
	hi (0, "NeoTreeTabInactive", { fg = "#666761" })
	hi (0, "NeoTreeTabSeparatorActive", { bg = "#a0a2a9", fg = "#666761" })
	hi (0, "NeoTreeTabSeparatorInactive", { bg = "#c0c2ca", fg = "#c0c2ca" })
	hi (0, "NeogitCommitViewHeader", { link = "Special" })
	hi (0, "NeogitDiffAdd", { link = "DiffAdd" })
	hi (0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
	hi (0, "NeogitDiffDelete", { link = "DiffDelete" })
	hi (0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
	hi (0, "NeogitFold", { link = "FoldColumn" })
	hi (0, "NeogitHunkHeader", { fg = "#1f1a77" })
	hi (0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#1f1a77" })
	hi (0, "NeogitNotificationError", { link = "DiagnosticError" })
	hi (0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
	hi (0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
	hi (0, "NoiceCmdlinePopupBorder", { fg = "#007086" })
	hi (0, "NoiceConfirmBorder", { fg = "#7a5800" })
	hi (0, "NonText", { fg = "#a0a2a9" })
	hi (0, "Normal", { bg = "#e0e2ea", fg = "#2e2f29" })
	hi (0, "NormalFloat", { fg = "#2e2f29" })
	hi (0, "NormalNC", { link = "Normal" })
	hi (0, "NotifyDEBUGBorder", { fg = "#415e00" })
	hi (0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
	hi (0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
	hi (0, "NotifyERRORBorder", { fg = "#65003d" })
	hi (0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
	hi (0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
	hi (0, "NotifyINFOBorder", { fg = "#002278" })
	hi (0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
	hi (0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
	hi (0, "NotifyTRACEBorder", { fg = "#00775f" })
	hi (0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
	hi (0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
	hi (0, "NotifyWARNBorder", { fg = "#7a5800" })
	hi (0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
	hi (0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
	hi (0, "NvimTreeExecFile", { bold = true, fg = "#415e00" })
	hi (0, "NvimTreeFolderIcon", { fg = "#666761" })
	hi (0, "NvimTreeGitDeleted", { fg = "#65003d" })
	hi (0, "NvimTreeGitDirty", { fg = "#7a5800" })
	hi (0, "NvimTreeGitMerge", { fg = "#721e00" })
	hi (0, "NvimTreeGitNew", { fg = "#00775f" })
	hi (0, "NvimTreeGitRenamed", { fg = "#430467" })
	hi (0, "NvimTreeGitStaged", { fg = "#415e00" })
	hi (0, "NvimTreeImageFile", { fg = "#721e00" })
	hi (0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
	hi (0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
	hi (0, "NvimTreeRootFolder", { bold = true, fg = "#1f1a77" })
	hi (0, "NvimTreeSpecialFile", { fg = "#1f1a77", underline = true })
	hi (0, "NvimTreeSymlink", { bold = true, fg = "#002278" })
	hi (0, "NvimTreeWindowPicker", { bg = "#a0a2a9", bold = true, fg = "#2e2f29" })
	hi (0, "Operator", { fg = "#2e2f29" })
	hi (0, "OutlineDetail", { fg = "#a0a2a9" })
	hi (0, "OutlineFoldPrefix", { fg = "#7a5800" })
	hi (0, "OutlineIndentEvn", { fg = "#666761" })
	hi (0, "OutlineIndentOdd", { fg = "#2e2f29" })
	hi (0, "Pmenu", { bg = "#c0c2ca", fg = "#2e2f29" })
	hi (0, "PmenuMatch", { bg = "#c0c2ca", bold = true, fg = "#2e2f29" })
	hi (0, "PmenuMatchSel", { blend = 0, bold = true, reverse = true })
	hi (0, "PmenuSel", { blend = 0, reverse = true })
	hi (0, "PmenuThumb", { bg = "#a0a2a9" })
	hi (0, "PounceAccept", { bg = "#7a5800", bold = true, fg = "#e0e2ea", nocombine = true })
	hi (0, "PounceAcceptBest", { bg = "#415e00", bold = true, fg = "#e0e2ea", nocombine = true })
	hi (0, "PounceGap", { bg = "#a0a2a9", bold = true, fg = "#e0e2ea", nocombine = true })
	hi (0, "PounceMatch", { bg = "#2e2f29", bold = true, fg = "#e0e2ea", nocombine = true })
	hi (0, "PreProc", { fg = "#002278" })
	hi (0, "Question", { fg = "#007086" })
	hi (0, "QuickFixLine", { bold = true })
	hi (0, "RainbowDelimiterBlue", { fg = "#007086" })
	hi (0, "RainbowDelimiterCyan", { fg = "#00775f" })
	hi (0, "RainbowDelimiterGreen", { fg = "#415e00" })
	hi (0, "RainbowDelimiterOrange", { fg = "#721e00" })
	hi (0, "RainbowDelimiterRed", { fg = "#65003d" })
	hi (0, "RainbowDelimiterViolet", { fg = "#430467" })
	hi (0, "RainbowDelimiterYellow", { fg = "#7a5800" })
	hi (0, "References", { fg = "#415e00" })
	hi (0, "ReferencesIcon", { fg = "#007086" })
	hi (0, "Removed", { fg = "#65003d" })
	hi (0, "Search", { bg = "#1f1a77", fg = "#e0e2ea" })
	hi (0, "SignColumn", { fg = "#a0a2a9" })
	hi (0, "Sneak", { bg = "#721e00", fg = "#e0e2ea" })
	hi (0, "SneakLabel", { bg = "#721e00", bold = true, fg = "#e0e2ea" })
	hi (0, "SneakScope", { bg = "#0d0e09", fg = "#e0e2ea" })
	hi (0, "Special", { fg = "#00775f" })
	hi (0, "SpecialKey", { fg = "#a0a2a9" })
	hi (0, "SpellBad", { sp = "#65003d", undercurl = true })
	hi (0, "SpellCap", { sp = "#00775f", undercurl = true })
	hi (0, "SpellLocal", { sp = "#7a5800", undercurl = true })
	hi (0, "SpellRare", { sp = "#002278", undercurl = true })
	hi (0, "Statement", { bold = true, fg = "#2e2f29" })
	hi (0, "StatusLine", { bg = "#e0e2ea", fg = "#494a44" })
	hi (0, "StatusLineNC", { bg = "#e9ebf3", fg = "#494a44" })
	hi (0, "String", { fg = "#415e00" })
	hi (0, "Substitute", { bg = "#002278", fg = "#e0e2ea" })
	hi (0, "TabLine", { bg = "#e9ebf3", fg = "#494a44" })
	hi (0, "TabLineSel", { bg = "#e9ebf3", fg = "#1f1a77" })
	hi (0, "TargetFileName", { fg = "#2e2f29" })
	hi (0, "TelescopeBorder", { fg = "#1f1a77" })
	hi (0, "TelescopeMatching", { bold = true })
	hi (0, "TelescopeMultiSelection", { bg = "#a0a2a9" })
	hi (0, "TelescopeSelection", { bg = "#c0c2ca" })
	hi (0, "TermCursorNC", { reverse = true })
	hi (0, "Title", { fg = "#1f1a77" })
	hi (0, "Todo", { bg = "#e0e2ea", bold = true, fg = "#1f1a77", italic = true })
	hi (0, "TroubleCount", { bold = true, fg = "#1f1a77" })
	hi (0, "TroubleFoldIcon", { bold = true, fg = "#1f1a77" })
	hi (0, "TroubleIndent", { fg = "#a0a2a9" })
	hi (0, "TroubleLocation", { fg = "#494a44" })
	hi (0, "TroubleSignError", { link = "DiagnosticError" })
	hi (0, "TroubleSignHint", { link = "DiagnosticHint" })
	hi (0, "TroubleSignInformation", { link = "DiagnosticInfo" })
	hi (0, "TroubleSignOther", { link = "DiagnosticInfo" })
	hi (0, "TroubleSignWarning", { link = "DiagnosticWarn" })
	hi (0, "TroubleText", { fg = "#2e2f29" })
	hi (0, "TroubleTextError", { link = "TroubleText" })
	hi (0, "TroubleTextHint", { link = "TroubleText" })
	hi (0, "TroubleTextInformation", { link = "TroubleText" })
	hi (0, "TroubleTextWarning", { link = "TroubleText" })
	hi (0, "Type", { fg = "#2e2f29" })
	hi (0, "VertSplit", { fg = "#1f1a77" })
	hi (0, "Visual", { bg = "#a0a2a9" })
	hi (0, "VisualNOS", { bg = "#c0c2ca" })
	hi (0, "WarningMsg", { fg = "#7a5800" })
	hi (0, "WhichKey", { fg = "#00775f" })
	hi (0, "WhichKeyBorder", { link = "FloatBorder" })
	hi (0, "WhichKeyDesc", { fg = "#2e2f29" })
	hi (0, "WhichKeyFloat", { bg = "#e9ebf3", fg = "#2e2f29" })
	hi (0, "WhichKeyGroup", { fg = "#65003d" })
	hi (0, "WhichKeySeparator", { fg = "#415e00" })
	hi (0, "WhichKeyValue", { fg = "#666761" })
	hi (0, "Whitespace", { fg = "#a0a2a9" })
	hi (0, "WinBar", { link = "StatusLine" })
	hi (0, "WinBarNC", { link = "StatusLineNC" })
	hi (0, "WinSeparator", { fg = "#1f1a77" })
	hi (0, "diffAdded", { fg = "#415e00" })
	hi (0, "diffChanged", { fg = "#00775f" })
	hi (0, "diffFile", { fg = "#7a5800" })
	hi (0, "diffLine", { fg = "#002278" })
	hi (0, "diffRemoved", { fg = "#65003d" })
	hi (0, "gitcommitBranch", { bold = true, fg = "#721e00" })
	hi (0, "gitcommitComment", { link = "Comment" })
	hi (0, "gitcommitDiscarded", { fg = "#666761" })
	hi (0, "gitcommitDiscardedFile", { bold = true, fg = "#7a5800" })
	hi (0, "gitcommitDiscardedType", { fg = "#007086" })
	hi (0, "gitcommitHeader", { link = "Title" })
	hi (0, "gitcommitOverflow", { fg = "#7a5800" })
	hi (0, "gitcommitSelected", { fg = "#666761" })
	hi (0, "gitcommitSelectedFile", { bold = true, fg = "#415e00" })
	hi (0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
	hi (0, "gitcommitSummary", { fg = "#415e00" })
	hi (0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
	hi (0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
	hi (0, "gitcommitUntracked", { fg = "#666761" })
	hi (0, "gitcommitUntrackedFile", { fg = "#00775f" })
	hi (0, "lCursor", { bg = "#2e2f29", fg = "#e0e2ea" })

	-- Terminal colors
	local g = vim.g

	g.terminal_color_0 = "#e0e2ea"
	g.terminal_color_1 = "#65003d"
	g.terminal_color_2 = "#415e00"
	g.terminal_color_3 = "#7a5800"
	g.terminal_color_4 = "#007086"
	g.terminal_color_5 = "#430467"
	g.terminal_color_6 = "#00775f"
	g.terminal_color_7 = "#2e2f29"
	g.terminal_color_8 = "#e0e2ea"
	g.terminal_color_9 = "#65003d"
	g.terminal_color_10 = "#415e00"
	g.terminal_color_11 = "#7a5800"
	g.terminal_color_12 = "#007086"
	g.terminal_color_13 = "#430467"
	g.terminal_color_14 = "#00775f"
	g.terminal_color_15 = "#2e2f29"
end
