if vim.g.colors_name ~= nil then
  vim.cmd.highlight [[clear]]
end

vim.g.colors_name = "noir"

if vim.o.background == [[dark]] then
  -- Highlight groups
  local hi = vim.api.nvim_set_hl

  hi(0, "@character.special", { link = "SpecialChar" })
  hi(0, "@constant.builtin", { link = "Special" })
  hi(0, "@constant.macro", { link = "Macro" })
  hi(0, "@function.builtin", { link = "Special" })
  hi(0, "@function.call", { link = "Function" })
  hi(0, "@function.macro", { link = "Macro" })
  hi(0, "@keyword.return", { bold = true, fg = "#c7c7c7" })
  hi(0, "@lsp.mod.defaultLibrary", { link = "Special" })
  hi(0, "@lsp.mod.deprecated", { fg = "#c6c6c6" })
  hi(0, "@lsp.type.class", { link = "Structure" })
  hi(0, "@lsp.type.comment", { link = "Comment" })
  hi(0, "@lsp.type.decorator", { link = "@function" })
  hi(0, "@lsp.type.enum", { link = "@type" })
  hi(0, "@lsp.type.enumMember", { link = "@constant" })
  hi(0, "@lsp.type.function", { link = "@function" })
  hi(0, "@lsp.type.interface", { link = "@lsp.type" })
  hi(0, "@lsp.type.macro", { link = "Macro" })
  hi(0, "@lsp.type.method", { link = "@method" })
  hi(0, "@lsp.type.namespace", { link = "@namespace" })
  hi(0, "@lsp.type.parameter", { link = "@parameter" })
  hi(0, "@lsp.type.property", { link = "@property" })
  hi(0, "@lsp.type.struct", { link = "@structure" })
  hi(0, "@lsp.type.type", { link = "@type" })
  hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
  hi(0, "@lsp.type.variable", {})
  hi(0, "@method.call", { link = "Function" })
  hi(0, "@parameter", { fg = "#c7c7c7" })
  hi(0, "@string.escape", { link = "SpecialChar" })
  hi(0, "@string.special", { link = "SpecialChar" })
  hi(0, "@structure", { link = "Structure" })
  hi(0, "@symbol", { link = "Keyword" })
  hi(0, "@text.danger", { link = "ErrorMsg" })
  hi(0, "@text.emphasis", { italic = true })
  hi(0, "@text.literal", { link = "Comment" })
  hi(0, "@text.note", { link = "MoreMsg" })
  hi(0, "@text.reference", { link = "Identifier" })
  hi(0, "@text.strike", { strikethrough = true })
  hi(0, "@text.strong", { bold = true })
  hi(0, "@text.title", { link = "Title" })
  hi(0, "@text.todo", { link = "Todo" })
  hi(0, "@text.underline", { link = "Underlined" })
  hi(0, "@text.uri", { link = "Underlined" })
  hi(0, "@text.warning", { link = "WarningMsg" })
  hi(0, "@type.builtin", { link = "Special" })
  hi(0, "@type.definition", { link = "Typedef" })
  hi(0, "@variable", { fg = "#c6c6c6" })
  hi(0, "@variable.builtin", { link = "Special" })
  hi(0, "Beacon", { bg = "#ececec" })
  hi(0, "Bold", { bold = true })
  hi(0, "BufferCurrent", { bg = "#222222", bold = true, fg = "#c7c7c7" })
  hi(0, "BufferCurrentIcon", { bg = "#222222" })
  hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
  hi(0, "BufferCurrentMod", { bg = "#3c3c3c", bold = true, fg = "#c7c7c7" })
  hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
  hi(0, "BufferCurrentTarget", { bg = "#565656", bold = true, fg = "#c7c7c7" })
  hi(0, "BufferInactive", { bg = "#161616", fg = "#c6c6c6" })
  hi(0, "BufferInactiveIcon", { bg = "#161616" })
  hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
  hi(0, "BufferInactiveMod", { bg = "#3c3c3c", fg = "#c6c6c6" })
  hi(0, "BufferInactiveSign", { link = "BufferInactive" })
  hi(0, "BufferInactiveTarget", { bg = "#565656", fg = "#c6c6c6" })
  hi(0, "BufferLineBuffer", { fg = "#8c8c8c" })
  hi(0, "BufferLineBufferSelected", { bold = true, fg = "#c6c6c6" })
  hi(0, "BufferLineBufferVisible", { fg = "#c6c6c6" })
  hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
  hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
  hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
  hi(0, "BufferLineFill", { link = "Normal" })
  hi(0, "BufferLineTab", { bg = "#c6c6c6", fg = "#222222" })
  hi(0, "BufferLineTabSelected", { bg = "#c6c6c6", bold = true, fg = "#222222" })
  hi(0, "BufferOffset", { link = "Normal" })
  hi(0, "BufferTabpageFill", { link = "Normal" })
  hi(0, "BufferTabpages", { bg = "#c6c6c6", bold = true, fg = "#222222" })
  hi(0, "BufferVisible", { bg = "#222222", bold = true, fg = "#c6c6c6" })
  hi(0, "BufferVisibleIcon", { bg = "#222222" })
  hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
  hi(0, "BufferVisibleMod", { bg = "#3c3c3c", bold = true, fg = "#c6c6c6" })
  hi(0, "BufferVisibleSign", { link = "BufferVisible" })
  hi(0, "BufferVisibleTarget", { bg = "#565656", bold = true, fg = "#c6c6c6" })
  hi(0, "CmpItemAbbr", { fg = "#c6c6c6" })
  hi(0, "CmpItemAbbrDeprecated", { link = "Comment" })
  hi(0, "CmpItemAbbrMatch", { bold = true })
  hi(0, "CmpItemAbbrMatchFuzzy", { bold = true })
  hi(0, "CmpItemKind", { fg = "#c6c6c6" })
  hi(0, "CmpItemKindClass", { link = "Type" })
  hi(0, "CmpItemKindColor", { link = "Special" })
  hi(0, "CmpItemKindConstant", { link = "Constant" })
  hi(0, "CmpItemKindConstructor", { link = "Type" })
  hi(0, "CmpItemKindEnum", { link = "Structure" })
  hi(0, "CmpItemKindEnumMember", { link = "Structure" })
  hi(0, "CmpItemKindEvent", { link = "Exception" })
  hi(0, "CmpItemKindField", { link = "Structure" })
  hi(0, "CmpItemKindFile", { link = "Tag" })
  hi(0, "CmpItemKindFolder", { link = "Directory" })
  hi(0, "CmpItemKindFunction", { link = "Function" })
  hi(0, "CmpItemKindInterface", { link = "Structure" })
  hi(0, "CmpItemKindKeyword", { link = "Keyword" })
  hi(0, "CmpItemKindMethod", { link = "Function" })
  hi(0, "CmpItemKindModule", { link = "Structure" })
  hi(0, "CmpItemKindOperator", { link = "Operator" })
  hi(0, "CmpItemKindProperty", { link = "Structure" })
  hi(0, "CmpItemKindReference", { link = "Tag" })
  hi(0, "CmpItemKindSnippet", { link = "Special" })
  hi(0, "CmpItemKindStruct", { link = "Structure" })
  hi(0, "CmpItemKindText", { link = "Normal" })
  hi(0, "CmpItemKindTypeParameter", { link = "Type" })
  hi(0, "CmpItemKindUnit", { link = "Special" })
  hi(0, "CmpItemKindValue", { link = "Identifier" })
  hi(0, "CmpItemKindVariable", { link = "Delimiter" })
  hi(0, "CmpItemMenu", { fg = "#c6c6c6" })
  hi(0, "CocCodeLens", { link = "LspCodeLens" })
  hi(0, "CocDisabled", { link = "Comment" })
  hi(0, "CocErrorFloat", { link = "DiagnosticFloatingError" })
  hi(0, "CocErrorHighlight", { link = "DiagnosticError" })
  hi(0, "CocErrorSign", { link = "DiagnosticSignError" })
  hi(0, "CocHintFloat", { link = "DiagnosticFloatingHint" })
  hi(0, "CocHintHighlight", { link = "DiagnosticHint" })
  hi(0, "CocHintSign", { link = "DiagnosticSignHint" })
  hi(0, "CocInfoFloat", { link = "DiagnosticFloatingInfo" })
  hi(0, "CocInfoHighlight", { link = "DiagnosticInfo" })
  hi(0, "CocInfoSign", { link = "DiagnosticSignInfo" })
  hi(0, "CocMarkdownLink", { fg = "#c7c7c7" })
  hi(0, "CocMenuSel", { bg = "#565656" })
  hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
  hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
  hi(0, "CocSearch", { fg = "#c7c7c7" })
  hi(0, "CocSelectedText", { fg = "#c7c7c7" })
  hi(0, "CocWarningFloat", { link = "DiagnosticFloatingWarn" })
  hi(0, "CocWarningHighlight", { link = "DiagnosticWarn" })
  hi(0, "CocWarningSign", { link = "DiagnosticSignWarn" })
  hi(0, "ColorColumn", { bg = "#565656" })
  hi(0, "Comment", { fg = "#8c8c8c" })
  hi(0, "Conceal", { fg = "#c7c7c7" })
  hi(0, "Constant", { fg = "#c7c7c7" })
  hi(0, "CurSearch", { bg = "#c7c7c7", fg = "#222222" })
  hi(0, "Cursor", { bg = "#c6c6c6", fg = "#222222" })
  hi(0, "CursorColumn", { bg = "#3c3c3c" })
  hi(0, "CursorIM", { link = "Cursor" })
  hi(0, "CursorLine", { bg = "#3c3c3c" })
  hi(0, "CursorLineFold", { fg = "#565656" })
  hi(0, "CursorLineNr", { bold = true, fg = "#c7c7c7" })
  hi(0, "CursorLineSign", { fg = "#565656" })
  hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#c6c6c6" })
  hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
  hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
  hi(0, "DapUIBreakpointsPath", { link = "Directory" })
  hi(0, "DapUIDecoration", { link = "Title" })
  hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
  hi(0, "DapUILineNumber", { link = "Title" })
  hi(0, "DapUIModifiedValue", { bold = true, fg = "#c7c7c7" })
  hi(0, "DapUIScope", { link = "Title" })
  hi(0, "DapUISource", { link = "Directory" })
  hi(0, "DapUIStoppedThread", { link = "Title" })
  hi(0, "DapUIThread", { link = "String" })
  hi(0, "DapUIType", { link = "Type" })
  hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
  hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
  hi(0, "DapUIWatchesValue", { link = "String" })
  hi(0, "DashboardCenter", { link = "Delimiter" })
  hi(0, "DashboardFooter", { link = "Comment" })
  hi(0, "DashboardHeader", { link = "Title" })
  hi(0, "DashboardShortCut", { link = "WarningMsg" })
  hi(0, "Definitions", { fg = "#c6c6c6" })
  hi(0, "DefinitionsIcon", { fg = "#c7c7c7" })
  hi(0, "Delimiter", { fg = "#c7c7c7" })
  hi(0, "DiagnosticDeprecated", { sp = "#c6c6c6", strikethrough = true })
  hi(0, "DiagnosticError", { fg = "#c6c6c6" })
  hi(0, "DiagnosticFloatingError", { bg = "#161616", fg = "#c6c6c6" })
  hi(0, "DiagnosticFloatingHint", { bg = "#161616", fg = "#c7c7c7" })
  hi(0, "DiagnosticFloatingInfo", { bg = "#161616", fg = "#c7c7c7" })
  hi(0, "DiagnosticFloatingOk", { bg = "#161616", fg = "#c6c6c6" })
  hi(0, "DiagnosticFloatingWarn", { bg = "#161616", fg = "#c7c7c7" })
  hi(0, "DiagnosticHint", { fg = "#c7c7c7" })
  hi(0, "DiagnosticInfo", { fg = "#c7c7c7" })
  hi(0, "DiagnosticOk", { fg = "#c6c6c6" })
  hi(0, "DiagnosticUnderlineError", { sp = "#ecb3d6", undercurl = true })
  hi(0, "DiagnosticUnderlineHint", { sp = "#98d7b6", undercurl = true })
  hi(0, "DiagnosticUnderlineInfo", { sp = "#a1cbfa", undercurl = true })
  hi(0, "DiagnosticUnderlineOk", { sp = "#c3ce92", underline = true })
  hi(0, "DiagnosticUnderlineWarn", { sp = "#e8bf8d", undercurl = true })
  hi(0, "DiagnosticWarn", { fg = "#c7c7c7" })
  hi(0, "DiffAdd", { fg = "#c6c6c6" })
  hi(0, "DiffAdded", { link = "DiffAdd" })
  hi(0, "DiffChange", { fg = "#c7c7c7" })
  hi(0, "DiffDelete", { fg = "#c6c6c6" })
  hi(0, "DiffFile", { bg = "#323232" })
  hi(0, "DiffLine", { bg = "#282828" })
  hi(0, "DiffNewFile", { link = "DiffAdded" })
  hi(0, "DiffRemoved", { link = "DiffFile" })
  hi(0, "DiffText", { bg = "#565656" })
  hi(0, "Directory", { fg = "#c7c7c7" })
  hi(0, "EndOfBuffer", { fg = "#565656" })
  hi(0, "Error", { bg = "#222222" })
  hi(0, "ErrorMsg", { fg = "#c6c6c6" })
  hi(0, "FinderParam", { fg = "#c7c7c7" })
  hi(0, "FinderSpinner", { fg = "#c6c6c6" })
  hi(0, "FinderSpinnerBorder", { fg = "#c7c7c7" })
  hi(0, "FinderSpinnerTitle", { link = "Title" })
  hi(0, "FinderVirtText", { fg = "#c7c7c7" })
  hi(0, "Float", { link = "Constant" })
  hi(0, "FloatBorder", { bg = "#161616", fg = "#c7c7c7" })
  hi(0, "FloatTitle", { bg = "#161616", bold = true, fg = "#c7c7c7" })
  hi(0, "FoldColumn", { fg = "#565656" })
  hi(0, "Folded", { bg = "#3c3c3c", fg = "#8c8c8c" })
  hi(0, "Function", { fg = "#c7c7c7", bold = true })
  hi(0, "GitSignsAdd", { fg = "#c6c6c6" })
  hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
  hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
  hi(0, "GitSignsChange", { fg = "#c7c7c7" })
  hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
  hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
  hi(0, "GitSignsDelete", { fg = "#c6c6c6" })
  hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
  hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
  hi(0, "GitSignsStagedAdd", { fg = "#636363" })
  hi(0, "GitSignsStagedAddLn", { fg = "#636363" })
  hi(0, "GitSignsStagedAddNr", { fg = "#636363" })
  hi(0, "GitSignsStagedChange", { fg = "#646464" })
  hi(0, "GitSignsStagedChangeLn", { fg = "#646464" })
  hi(0, "GitSignsStagedChangeNr", { fg = "#646464" })
  hi(0, "GitSignsStagedChangedelete", { fg = "#646464" })
  hi(0, "GitSignsStagedChangedeleteLn", { fg = "#646464" })
  hi(0, "GitSignsStagedChangedeleteNr", { fg = "#646464" })
  hi(0, "GitSignsStagedDelete", { fg = "#636363" })
  hi(0, "GitSignsStagedDeleteLn", { fg = "#636363" })
  hi(0, "GitSignsStagedDeleteNr", { fg = "#636363" })
  hi(0, "GitSignsStagedTopdelete", { fg = "#636363" })
  hi(0, "GitSignsStagedTopdeleteNr", { fg = "#636363" })
  hi(0, "GitSignsUntracked", { fg = "#c7c7c7" })
  hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
  hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
  hi(0, "HopNextKey", { bold = true, fg = "#c6c6c6", nocombine = true })
  hi(0, "HopNextKey1", { bold = true, fg = "#c7c7c7", nocombine = true })
  hi(0, "HopNextKey2", { bold = true, fg = "#aaaaaa", nocombine = true })
  hi(0, "HopPreview", { bold = true, fg = "#c7c7c7", nocombine = true })
  hi(0, "HopUnmatched", { fg = "#565656" })
  hi(0, "HydraAmaranth", { fg = "#c7c7c7" })
  hi(0, "HydraBlue", { fg = "#c7c7c7" })
  hi(0, "HydraHint", { link = "NormalFloat" })
  hi(0, "HydraPink", { fg = "#c7c7c7" })
  hi(0, "HydraRed", { fg = "#c6c6c6" })
  hi(0, "HydraTeal", { fg = "#c7c7c7" })
  hi(0, "Identifier", { fg = "#c7c7c7" })
  hi(0, "Ignore", {})
  hi(0, "IncSearch", { bg = "#c7c7c7", fg = "#222222" })
  hi(0, "IndentBlanklineChar", { fg = "#565656", nocombine = true })
  hi(0, "IndentBlanklineContextChar", { fg = "#c7c7c7", nocombine = true })
  hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#f5b1bf", underline = true })
  hi(0, "IndentBlanklineIndent1", { fg = "#c7c7c7", nocombine = true })
  hi(0, "IndentBlanklineIndent2", { fg = "#c7c7c7", nocombine = true })
  hi(0, "IndentBlanklineIndent3", { fg = "#c7c7c7", nocombine = true })
  hi(0, "IndentBlanklineIndent4", { fg = "#c6c6c6", nocombine = true })
  hi(0, "IndentBlanklineIndent5", { fg = "#c7c7c7", nocombine = true })
  hi(0, "IndentBlanklineIndent6", { fg = "#c6c6c6", nocombine = true })
  hi(0, "IndentBlanklineIndent7", { fg = "#c7c7c7", nocombine = true })
  hi(0, "IndentBlanklineIndent8", { fg = "#c7c7c7", nocombine = true })
  hi(0, "Italic", { italic = true })
  hi(0, "LSOutlinePreviewBorder", { fg = "#c7c7c7" })
  hi(0, "LazyButton", { bg = "#3c3c3c" })
  hi(0, "LazyButtonActive", { bg = "#565656" })
  hi(0, "LazyDimmed", { link = "Comment" })
  hi(0, "LazyH1", { bg = "#565656", bold = true, fg = "#c7c7c7" })
  hi(0, "LeapBackdrop", { link = "Comment" })
  hi(0, "LeapLabelPrimary", { bold = true, fg = "#c7c7c7", nocombine = true })
  hi(0, "LeapLabelSecondary", { bold = true, fg = "#c6c6c6", nocombine = true })
  hi(0, "LeapLabelSelected", { bold = true, fg = "#c7c7c7", nocombine = true })
  hi(0, "LeapMatch", { bold = true, fg = "#c6c6c6", nocombine = true })
  hi(0, "LineNr", { fg = "#565656" })
  hi(0, "LspCodeLens", { link = "Comment" })
  hi(0, "LspCodeLensSeparator", { link = "Comment" })
  hi(0, "LspReferenceRead", { link = "LspReferenceText" })
  hi(0, "LspReferenceText", { bg = "#565656" })
  hi(0, "LspReferenceWrite", { link = "LspReferenceText" })
  hi(0, "LspSagaAutoPreview", { fg = "#c7c7c7" })
  hi(0, "LspSagaBorderTitle", { link = "FloatTitle" })
  hi(0, "LspSagaCodeActionBorder", { fg = "#c7c7c7" })
  hi(0, "LspSagaCodeActionContent", { fg = "#c6c6c6" })
  hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#c7c7c7" })
  hi(0, "LspSagaDefPreviewBorder", { fg = "#c7c7c7" })
  hi(0, "LspSagaDiagnosticBorder", { fg = "#c7c7c7" })
  hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
  hi(0, "LspSagaDiagnosticSource", { fg = "#c7c7c7" })
  hi(0, "LspSagaFinderSelection", { fg = "#c7c7c7" })
  hi(0, "LspSagaHoverBorder", { fg = "#c7c7c7" })
  hi(0, "LspSagaLspFinderBorder", { fg = "#c7c7c7" })
  hi(0, "LspSagaRenameBorder", { fg = "#c7c7c7" })
  hi(0, "LspSagaSignatureHelpBorder", { fg = "#c7c7c7" })
  hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
  hi(0, "MasonError", { fg = "#c6c6c6" })
  hi(0, "MasonHeader", { bg = "#c7c7c7", bold = true, fg = "#222222" })
  hi(0, "MasonHeaderSecondary", { bg = "#c7c7c7", bold = true, fg = "#222222" })
  hi(0, "MasonHeading", { link = "Bold" })
  hi(0, "MasonHighlight", { fg = "#c7c7c7" })
  hi(0, "MasonHighlightBlock", { bg = "#c7c7c7", fg = "#222222" })
  hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
  hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
  hi(0, "MasonHighlightBlockSecondary", { bg = "#c7c7c7", fg = "#222222" })
  hi(0, "MasonHighlightSecondary", { fg = "#c7c7c7" })
  hi(0, "MasonLink", { link = "MasonHighlight" })
  hi(0, "MasonMuted", { link = "Comment" })
  hi(0, "MasonMutedBlock", { bg = "#565656", fg = "#222222" })
  hi(0, "MasonMutedBlockBold", { bg = "#565656", bold = true, fg = "#222222" })
  hi(0, "MatchParen", { bg = "#565656", bold = true })
  hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
  hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
  hi(0, "MiniClueBorder", { link = "FloatBorder" })
  hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
  hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
  hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
  hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
  hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
  hi(0, "MiniClueTitle", { link = "FloatTitle" })
  hi(0, "MiniCompletionActiveParameter", { bg = "#565656" })
  hi(0, "MiniCursorword", { underline = true })
  hi(0, "MiniCursorwordCurrent", { underline = true })
  hi(0, "MiniFilesBorder", { link = "FloatBorder" })
  hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
  hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
  hi(0, "MiniFilesDirectory", { link = "Directory" })
  hi(0, "MiniFilesFile", { fg = "#c6c6c6" })
  hi(0, "MiniFilesNormal", { link = "NormalFloat" })
  hi(0, "MiniFilesTitle", { link = "FloatTitle" })
  hi(0, "MiniFilesTitleFocused", { bg = "#161616", bold = true, fg = "#c6c6c6" })
  hi(0, "MiniHipatternsFixme", { bg = "#c6c6c6", bold = true, fg = "#222222" })
  hi(0, "MiniHipatternsHack", { bg = "#c7c7c7", bold = true, fg = "#222222" })
  hi(0, "MiniHipatternsNote", { bg = "#c7c7c7", bold = true, fg = "#222222" })
  hi(0, "MiniHipatternsTodo", { bg = "#c7c7c7", bold = true, fg = "#222222" })
  hi(0, "MiniIndentscopeSymbol", { fg = "#c7c7c7" })
  hi(0, "MiniIndentscopeSymbolOff", { fg = "#c6c6c6" })
  hi(0, "MiniJump", { sp = "#f5b1bf", undercurl = true })
  hi(0, "MiniJump2dDim", { fg = "#565656" })
  hi(0, "MiniJump2dSpot", { bg = "#080808", bold = true, fg = "#ececec", nocombine = true })
  hi(0, "MiniJump2dSpotAhead", { bg = "#080808", fg = "#d9d9d9", nocombine = true })
  hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
  hi(0, "MiniMapNormal", { bg = "#161616", fg = "#8c8c8c" })
  hi(0, "MiniMapSymbolCount", { fg = "#8c8c8c" })
  hi(0, "MiniMapSymbolLine", { fg = "#c7c7c7" })
  hi(0, "MiniMapSymbolView", { fg = "#c7c7c7" })
  hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
  hi(0, "MiniPickBorder", { link = "FloatBorder" })
  hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
  hi(0, "MiniPickBorderText", { link = "FloatTitle" })
  hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
  hi(0, "MiniPickIconDirectory", { link = "Directory" })
  hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
  hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
  hi(0, "MiniPickMatchMarked", { link = "Visual" })
  hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
  hi(0, "MiniPickNormal", { link = "NormalFloat" })
  hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
  hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
  hi(0, "MiniPickPrompt", { link = "DiagnosticFloatingInfo" })
  hi(0, "MiniStarterCurrent", { link = "MiniStarterItem" })
  hi(0, "MiniStarterFooter", { link = "Comment" })
  hi(0, "MiniStarterHeader", { bold = true, fg = "#c7c7c7" })
  hi(0, "MiniStarterInactive", { link = "Comment" })
  hi(0, "MiniStarterItemBullet", { fg = "#8c8c8c" })
  hi(0, "MiniStarterItemPrefix", { bold = true, fg = "#c7c7c7" })
  hi(0, "MiniStarterQuery", { bold = true, fg = "#c6c6c6" })
  hi(0, "MiniStarterSection", { fg = "#c7c7c7" })
  hi(0, "MiniStatuslineDevinfo", { bg = "#3c3c3c", fg = "#aaaaaa" })
  hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
  hi(0, "MiniStatuslineFilename", { bg = "#222222", fg = "#aaaaaa" })
  hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
  hi(0, "MiniStatuslineModeCommand", { bg = "#c7c7c7", bold = true, fg = "#222222" })
  hi(0, "MiniStatuslineModeInsert", { bg = "#c7c7c7", bold = true, fg = "#222222" })
  hi(0, "MiniStatuslineModeNormal", { bg = "#c6c6c6", bold = true, fg = "#222222" })
  hi(0, "MiniStatuslineModeOther", { bg = "#c7c7c7", bold = true, fg = "#222222" })
  hi(0, "MiniStatuslineModeReplace", { bg = "#c6c6c6", bold = true, fg = "#222222" })
  hi(0, "MiniStatuslineModeVisual", { bg = "#c6c6c6", bold = true, fg = "#222222" })
  hi(0, "MiniSurround", { link = "IncSearch" })
  hi(0, "MiniTablineCurrent", { bg = "#222222", bold = true, fg = "#c7c7c7" })
  hi(0, "MiniTablineFill", { link = "MiniTablineHidden" })
  hi(0, "MiniTablineHidden", { bg = "#161616", fg = "#aaaaaa" })
  hi(0, "MiniTablineModifiedCurrent", { bg = "#c7c7c7", bold = true, fg = "#222222" })
  hi(0, "MiniTablineModifiedHidden", { bg = "#aaaaaa", fg = "#161616" })
  hi(0, "MiniTablineModifiedVisible", { bg = "#aaaaaa", bold = true, fg = "#161616" })
  hi(0, "MiniTablineTabpagesection", { bg = "#c6c6c6", bold = true, fg = "#222222" })
  hi(0, "MiniTablineVisible", { bg = "#161616", bold = true, fg = "#aaaaaa" })
  hi(0, "MiniTestEmphasis", { bold = true })
  hi(0, "MiniTestFail", { bold = true, fg = "#c6c6c6" })
  hi(0, "MiniTestPass", { bold = true, fg = "#c6c6c6" })
  hi(0, "MiniTrailspace", { bg = "#222222" })
  hi(0, "ModeMsg", { fg = "#c6c6c6" })
  hi(0, "MoreMsg", { fg = "#c7c7c7" })
  hi(0, "MsgArea", { link = "Normal" })
  hi(0, "MsgSeparator", { bg = "#565656", fg = "#8c8c8c" })
  hi(0, "NeoTreeDimText", { fg = "#565656" })
  hi(0, "NeoTreeDotfile", { fg = "#aaaaaa" })
  hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
  hi(0, "NeoTreeFadeText2", { fg = "#565656" })
  hi(0, "NeoTreeGitAdded", { fg = "#c6c6c6" })
  hi(0, "NeoTreeGitConflict", { bold = true, fg = "#c7c7c7" })
  hi(0, "NeoTreeGitDeleted", { fg = "#c6c6c6" })
  hi(0, "NeoTreeGitModified", { fg = "#c7c7c7" })
  hi(0, "NeoTreeGitUnstaged", { fg = "#c7c7c7" })
  hi(0, "NeoTreeGitUntracked", { fg = "#c7c7c7" })
  hi(0, "NeoTreeMessage", { bg = "#3c3c3c", fg = "#c6c6c6" })
  hi(0, "NeoTreeModified", { fg = "#d9d9d9" })
  hi(0, "NeoTreeRootName", { bold = true, fg = "#c7c7c7" })
  hi(0, "NeoTreeTabInactive", { fg = "#8c8c8c" })
  hi(0, "NeoTreeTabSeparatorActive", { bg = "#565656", fg = "#8c8c8c" })
  hi(0, "NeoTreeTabSeparatorInactive", { bg = "#3c3c3c", fg = "#3c3c3c" })
  hi(0, "NeogitCommitViewHeader", { link = "Special" })
  hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
  hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
  hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
  hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
  hi(0, "NeogitFold", { link = "FoldColumn" })
  hi(0, "NeogitHunkHeader", { fg = "#c7c7c7" })
  hi(0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#c7c7c7" })
  hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
  hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
  hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
  hi(0, "NoiceCmdlinePopupBorder", { fg = "#c7c7c7" })
  hi(0, "NoiceConfirmBorder", { fg = "#c7c7c7" })
  hi(0, "NoiceFormatProgressDone", { bg = "#c7c7c7", fg = "#222222" })
  hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
  hi(0, "NonText", { fg = "#565656" })
  hi(0, "Normal", { bg = "#222222", fg = "#c6c6c6" })
  hi(0, "NormalFloat", { bg = "#161616", fg = "#c6c6c6" })
  hi(0, "NormalNC", { link = "Normal" })
  hi(0, "NotifyDEBUGBorder", { fg = "#c6c6c6" })
  hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
  hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
  hi(0, "NotifyERRORBorder", { fg = "#c6c6c6" })
  hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
  hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
  hi(0, "NotifyINFOBorder", { fg = "#c7c7c7" })
  hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
  hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
  hi(0, "NotifyTRACEBorder", { fg = "#c7c7c7" })
  hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
  hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
  hi(0, "NotifyWARNBorder", { fg = "#c7c7c7" })
  hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
  hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
  hi(0, "NvimInternalError", { bg = "#888888", ctermbg = 9, ctermfg = 9, fg = "#888888" })
  hi(0, "NvimTreeExecFile", { bold = true, fg = "#c6c6c6" })
  hi(0, "NvimTreeFolderIcon", { fg = "#8c8c8c" })
  hi(0, "NvimTreeGitDeleted", { fg = "#c6c6c6" })
  hi(0, "NvimTreeGitDirty", { fg = "#c7c7c7" })
  hi(0, "NvimTreeGitMerge", { fg = "#c7c7c7" })
  hi(0, "NvimTreeGitNew", { fg = "#c7c7c7" })
  hi(0, "NvimTreeGitRenamed", { fg = "#c7c7c7" })
  hi(0, "NvimTreeGitStaged", { fg = "#c6c6c6" })
  hi(0, "NvimTreeImageFile", { fg = "#c7c7c7" })
  hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
  hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
  hi(0, "NvimTreeRootFolder", { bold = true, fg = "#c7c7c7" })
  hi(0, "NvimTreeSpecialFile", { fg = "#c7c7c7", underline = true })
  hi(0, "NvimTreeSymlink", { bold = true, fg = "#c7c7c7" })
  hi(0, "NvimTreeWindowPicker", { bg = "#565656", bold = true, fg = "#c6c6c6" })
  hi(0, "Operator", { fg = "#c6c6c6" })
  hi(0, "OutlineDetail", { fg = "#565656" })
  hi(0, "OutlineFoldPrefix", { fg = "#c7c7c7" })
  hi(0, "OutlineIndentEvn", { fg = "#8c8c8c" })
  hi(0, "OutlineIndentOdd", { fg = "#c6c6c6" })
  hi(0, "Pmenu", { bg = "#3c3c3c", fg = "#c6c6c6" })
  hi(0, "PmenuSbar", { link = "Pmenu" })
  hi(0, "PmenuSel", { bg = "#c6c6c6", blend = 0, fg = "#222222" })
  hi(0, "PmenuThumb", { bg = "#565656" })
  hi(0, "PounceAccept", { bg = "#c7c7c7", bold = true, fg = "#222222", nocombine = true })
  hi(0, "PounceAcceptBest", { bg = "#c6c6c6", bold = true, fg = "#222222", nocombine = true })
  hi(0, "PounceGap", { bg = "#565656", bold = true, fg = "#222222", nocombine = true })
  hi(0, "PounceMatch", { bg = "#c6c6c6", bold = true, fg = "#222222", nocombine = true })
  hi(0, "PreProc", { fg = "#c7c7c7" })
  hi(0, "Question", { fg = "#c7c7c7" })
  hi(0, "QuickFixLine", { bg = "#3c3c3c" })
  hi(0, "RainbowDelimiterBlue", { fg = "#c7c7c7" })
  hi(0, "RainbowDelimiterCyan", { fg = "#c7c7c7" })
  hi(0, "RainbowDelimiterGreen", { fg = "#c6c6c6" })
  hi(0, "RainbowDelimiterOrange", { fg = "#c7c7c7" })
  hi(0, "RainbowDelimiterRed", { fg = "#c6c6c6" })
  hi(0, "RainbowDelimiterViolet", { fg = "#c7c7c7" })
  hi(0, "RainbowDelimiterYellow", { fg = "#c7c7c7" })
  hi(0, "RedrawDebugClear", { bg = "#f4f4f4", ctermbg = 11 })
  hi(0, "RedrawDebugComposed", { bg = "#696969", ctermbg = 10 })
  hi(0, "RedrawDebugRecompose", { bg = "#888888", ctermbg = 9 })
  hi(0, "References", { fg = "#c6c6c6" })
  hi(0, "ReferencesIcon", { fg = "#c7c7c7" })
  hi(0, "Search", { bg = "#c7c7c7", fg = "#222222" })
  hi(0, "SignColumn", { fg = "#565656" })
  hi(0, "Sneak", { bg = "#c7c7c7", fg = "#222222" })
  hi(0, "SneakLabel", { bg = "#c7c7c7", bold = true, fg = "#222222" })
  hi(0, "SneakScope", { bg = "#ececec", fg = "#222222" })
  hi(0, "Special", { fg = "#c7c7c7" })
  hi(0, "SpecialKey", { fg = "#565656" })
  hi(0, "SpellBad", { sp = "#ecb3d6", undercurl = true })
  hi(0, "SpellCap", { sp = "#98d7b6", undercurl = true })
  hi(0, "SpellLocal", { sp = "#e8bf8d", undercurl = true })
  hi(0, "SpellRare", { sp = "#a1cbfa", undercurl = true })
  hi(0, "Statement", { bold = true })
  hi(0, "StatusLine", { bg = "#222222", fg = "#aaaaaa" })
  hi(0, "StatusLineNC", { bg = "#161616", fg = "#aaaaaa" })
  hi(0, "String", { fg = "#c6c6c6" })
  hi(0, "Substitute", { bg = "#c7c7c7", fg = "#222222" })
  hi(0, "TabLine", { bg = "#161616", fg = "#aaaaaa" })
  hi(0, "TabLineFill", { link = "TabLine" })
  hi(0, "TabLineSel", { bg = "#161616", fg = "#c7c7c7" })
  hi(0, "TargetFileName", { fg = "#c6c6c6" })
  hi(0, "TelescopeBorder", { fg = "#c7c7c7" })
  hi(0, "TelescopeMatching", { bold = true })
  hi(0, "TelescopeMultiSelection", { bg = "#565656" })
  hi(0, "TelescopeSelection", { bg = "#3c3c3c" })
  hi(0, "TermCursorNC", { reverse = true })
  hi(0, "Title", { fg = "#c7c7c7" })
  hi(0, "Todo", { bg = "#222222", bold = true, fg = "#c7c7c7" })
  hi(0, "TroubleCount", { bold = true, fg = "#c7c7c7" })
  hi(0, "TroubleFoldIcon", { bold = true, fg = "#c7c7c7" })
  hi(0, "TroubleIndent", { fg = "#565656" })
  hi(0, "TroubleLocation", { fg = "#aaaaaa" })
  hi(0, "TroubleSignError", { link = "DiagnosticError" })
  hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
  hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
  hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
  hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
  hi(0, "TroubleText", { fg = "#c6c6c6" })
  hi(0, "TroubleTextError", { link = "TroubleText" })
  hi(0, "TroubleTextHint", { link = "TroubleText" })
  hi(0, "TroubleTextInformation", { link = "TroubleText" })
  hi(0, "TroubleTextWarning", { link = "TroubleText" })
  hi(0, "Type", { fg = "#c6c6c6" })
  hi(0, "UfoFoldedBg", { bg = "#3c3c3c" })
  hi(0, "UfoFoldedFg", { fg = "#c6c6c6" })
  hi(0, "Underlined", { underline = true })
  hi(0, "VertSplit", { fg = "#c7c7c7" })
  hi(0, "Visual", { bg = "#565656" })
  hi(0, "VisualNOS", { bg = "#3c3c3c" })
  hi(0, "WarningMsg", { fg = "#c7c7c7" })
  hi(0, "WhichKey", { fg = "#c7c7c7" })
  hi(0, "WhichKeyBorder", { link = "FloatBorder" })
  hi(0, "WhichKeyDesc", { fg = "#c6c6c6" })
  hi(0, "WhichKeyFloat", { bg = "#161616", fg = "#c6c6c6" })
  hi(0, "WhichKeyGroup", { fg = "#c6c6c6" })
  hi(0, "WhichKeySeparator", { fg = "#c6c6c6" })
  hi(0, "WhichKeyValue", { link = "Comment" })
  hi(0, "Whitespace", { fg = "#565656" })
  hi(0, "WildMenu", { link = "PmenuSel" })
  hi(0, "WinBar", { link = "StatusLine" })
  hi(0, "WinBarNC", { link = "StatusLineNC" })
  hi(0, "WinSeparator", { fg = "#c7c7c7" })
  hi(0, "gitcommitBranch", { bold = true, fg = "#c7c7c7" })
  hi(0, "gitcommitComment", { link = "Comment" })
  hi(0, "gitcommitDiscarded", { link = "Comment" })
  hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#c7c7c7" })
  hi(0, "gitcommitDiscardedType", { fg = "#c7c7c7" })
  hi(0, "gitcommitHeader", { link = "Title" })
  hi(0, "gitcommitOverflow", { fg = "#c7c7c7" })
  hi(0, "gitcommitSelected", { link = "Comment" })
  hi(0, "gitcommitSelectedFile", { bold = true, fg = "#c6c6c6" })
  hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
  hi(0, "gitcommitSummary", { fg = "#c6c6c6" })
  hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
  hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
  hi(0, "gitcommitUntracked", { link = "Comment" })
  hi(0, "gitcommitUntrackedFile", { fg = "#c7c7c7" })
  hi(0, "lCursor", { bg = "#c6c6c6", fg = "#222222" })

  -- Terminal colors
  local g = vim.g

  g.terminal_color_0 = "#222222"
  g.terminal_color_1 = "#c6c6c6"
  g.terminal_color_2 = "#c6c6c6"
  g.terminal_color_3 = "#c7c7c7"
  g.terminal_color_4 = "#c7c7c7"
  g.terminal_color_5 = "#c7c7c7"
  g.terminal_color_6 = "#c7c7c7"
  g.terminal_color_7 = "#c6c6c6"
  g.terminal_color_8 = "#222222"
  g.terminal_color_9 = "#c6c6c6"
  g.terminal_color_10 = "#c6c6c6"
  g.terminal_color_11 = "#c7c7c7"
  g.terminal_color_12 = "#c7c7c7"
  g.terminal_color_13 = "#c7c7c7"
  g.terminal_color_14 = "#c7c7c7"
  g.terminal_color_15 = "#c6c6c6"
end

if vim.o.background == [[light]] then
  -- Highlight groups
  local hi = vim.api.nvim_set_hl

  hi(0, "@character.special", { link = "SpecialChar" })
  hi(0, "@constant.builtin", { link = "Special" })
  hi(0, "@constant.macro", { link = "Macro" })
  hi(0, "@function.builtin", { link = "Special" })
  hi(0, "@function.call", { link = "Function" })
  hi(0, "@function.macro", { link = "Macro" })
  hi(0, "@keyword.return", { bold = true, fg = "#2e2e2e" })
  hi(0, "@lsp.mod.defaultLibrary", { link = "Special" })
  hi(0, "@lsp.mod.deprecated", { fg = "#2f2f2f" })
  hi(0, "@lsp.type.class", { link = "Structure" })
  hi(0, "@lsp.type.comment", { link = "Comment" })
  hi(0, "@lsp.type.decorator", { link = "@function" })
  hi(0, "@lsp.type.enum", { link = "@type" })
  hi(0, "@lsp.type.enumMember", { link = "@constant" })
  hi(0, "@lsp.type.function", { link = "@function" })
  hi(0, "@lsp.type.interface", { link = "@lsp.type" })
  hi(0, "@lsp.type.macro", { link = "Macro" })
  hi(0, "@lsp.type.method", { link = "@method" })
  hi(0, "@lsp.type.namespace", { link = "@namespace" })
  hi(0, "@lsp.type.parameter", { link = "@parameter" })
  hi(0, "@lsp.type.property", { link = "@property" })
  hi(0, "@lsp.type.struct", { link = "@structure" })
  hi(0, "@lsp.type.type", { link = "@type" })
  hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
  hi(0, "@lsp.type.variable", {})
  hi(0, "@method.call", { link = "Function" })
  hi(0, "@parameter", { fg = "#2e2e2e" })
  hi(0, "@string.escape", { link = "SpecialChar" })
  hi(0, "@string.special", { link = "SpecialChar" })
  hi(0, "@structure", { link = "Structure" })
  hi(0, "@symbol", { link = "Keyword" })
  hi(0, "@text.danger", { link = "ErrorMsg" })
  hi(0, "@text.emphasis", { italic = true })
  hi(0, "@text.literal", { link = "Comment" })
  hi(0, "@text.note", { link = "MoreMsg" })
  hi(0, "@text.reference", { link = "Identifier" })
  hi(0, "@text.strike", { strikethrough = true })
  hi(0, "@text.strong", { bold = true })
  hi(0, "@text.title", { link = "Title" })
  hi(0, "@text.todo", { link = "Todo" })
  hi(0, "@text.underline", { link = "Underlined" })
  hi(0, "@text.uri", { link = "Underlined" })
  hi(0, "@text.warning", { link = "WarningMsg" })
  hi(0, "@type.builtin", { link = "Special" })
  hi(0, "@type.definition", { link = "Typedef" })
  hi(0, "@variable", { fg = "#2f2f2f" })
  hi(0, "@variable.builtin", { link = "Special" })
  hi(0, "Beacon", { bg = "#0d0d0d" })
  hi(0, "Bold", { bold = true })
  hi(0, "BufferCurrent", { bg = "#d5d5d5", bold = true, fg = "#2e2e2e" })
  hi(0, "BufferCurrentIcon", { bg = "#d5d5d5" })
  hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
  hi(0, "BufferCurrentMod", { bg = "#b6b6b6", bold = true, fg = "#2e2e2e" })
  hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
  hi(0, "BufferCurrentTarget", { bg = "#999999", bold = true, fg = "#2e2e2e" })
  hi(0, "BufferInactive", { bg = "#e3e3e3", fg = "#2f2f2f" })
  hi(0, "BufferInactiveIcon", { bg = "#e3e3e3" })
  hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
  hi(0, "BufferInactiveMod", { bg = "#b6b6b6", fg = "#2f2f2f" })
  hi(0, "BufferInactiveSign", { link = "BufferInactive" })
  hi(0, "BufferInactiveTarget", { bg = "#999999", fg = "#2f2f2f" })
  hi(0, "BufferLineBuffer", { fg = "#626262" })
  hi(0, "BufferLineBufferSelected", { bold = true, fg = "#2f2f2f" })
  hi(0, "BufferLineBufferVisible", { fg = "#2f2f2f" })
  hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
  hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
  hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
  hi(0, "BufferLineFill", { link = "Normal" })
  hi(0, "BufferLineTab", { bg = "#2f2f2f", fg = "#d5d5d5" })
  hi(0, "BufferLineTabSelected", { bg = "#2f2f2f", bold = true, fg = "#d5d5d5" })
  hi(0, "BufferOffset", { link = "Normal" })
  hi(0, "BufferTabpageFill", { link = "Normal" })
  hi(0, "BufferTabpages", { bg = "#2f2f2f", bold = true, fg = "#d5d5d5" })
  hi(0, "BufferVisible", { bg = "#d5d5d5", bold = true, fg = "#2f2f2f" })
  hi(0, "BufferVisibleIcon", { bg = "#d5d5d5" })
  hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
  hi(0, "BufferVisibleMod", { bg = "#b6b6b6", bold = true, fg = "#2f2f2f" })
  hi(0, "BufferVisibleSign", { link = "BufferVisible" })
  hi(0, "BufferVisibleTarget", { bg = "#999999", bold = true, fg = "#2f2f2f" })
  hi(0, "CmpItemAbbr", { fg = "#2f2f2f" })
  hi(0, "CmpItemAbbrDeprecated", { link = "Comment" })
  hi(0, "CmpItemAbbrMatch", { bold = true })
  hi(0, "CmpItemAbbrMatchFuzzy", { bold = true })
  hi(0, "CmpItemKind", { fg = "#2f2f2f" })
  hi(0, "CmpItemKindClass", { link = "Type" })
  hi(0, "CmpItemKindColor", { link = "Special" })
  hi(0, "CmpItemKindConstant", { link = "Constant" })
  hi(0, "CmpItemKindConstructor", { link = "Type" })
  hi(0, "CmpItemKindEnum", { link = "Structure" })
  hi(0, "CmpItemKindEnumMember", { link = "Structure" })
  hi(0, "CmpItemKindEvent", { link = "Exception" })
  hi(0, "CmpItemKindField", { link = "Structure" })
  hi(0, "CmpItemKindFile", { link = "Tag" })
  hi(0, "CmpItemKindFolder", { link = "Directory" })
  hi(0, "CmpItemKindFunction", { link = "Function" })
  hi(0, "CmpItemKindInterface", { link = "Structure" })
  hi(0, "CmpItemKindKeyword", { link = "Keyword" })
  hi(0, "CmpItemKindMethod", { link = "Function" })
  hi(0, "CmpItemKindModule", { link = "Structure" })
  hi(0, "CmpItemKindOperator", { link = "Operator" })
  hi(0, "CmpItemKindProperty", { link = "Structure" })
  hi(0, "CmpItemKindReference", { link = "Tag" })
  hi(0, "CmpItemKindSnippet", { link = "Special" })
  hi(0, "CmpItemKindStruct", { link = "Structure" })
  hi(0, "CmpItemKindText", { link = "Normal" })
  hi(0, "CmpItemKindTypeParameter", { link = "Type" })
  hi(0, "CmpItemKindUnit", { link = "Special" })
  hi(0, "CmpItemKindValue", { link = "Identifier" })
  hi(0, "CmpItemKindVariable", { link = "Delimiter" })
  hi(0, "CmpItemMenu", { fg = "#2f2f2f" })
  hi(0, "CocCodeLens", { link = "LspCodeLens" })
  hi(0, "CocDisabled", { link = "Comment" })
  hi(0, "CocErrorFloat", { link = "DiagnosticFloatingError" })
  hi(0, "CocErrorHighlight", { link = "DiagnosticError" })
  hi(0, "CocErrorSign", { link = "DiagnosticSignError" })
  hi(0, "CocHintFloat", { link = "DiagnosticFloatingHint" })
  hi(0, "CocHintHighlight", { link = "DiagnosticHint" })
  hi(0, "CocHintSign", { link = "DiagnosticSignHint" })
  hi(0, "CocInfoFloat", { link = "DiagnosticFloatingInfo" })
  hi(0, "CocInfoHighlight", { link = "DiagnosticInfo" })
  hi(0, "CocInfoSign", { link = "DiagnosticSignInfo" })
  hi(0, "CocMarkdownLink", { fg = "#2e2e2e" })
  hi(0, "CocMenuSel", { bg = "#999999" })
  hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
  hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
  hi(0, "CocSearch", { fg = "#2e2e2e" })
  hi(0, "CocSelectedText", { fg = "#2e2e2e" })
  hi(0, "CocWarningFloat", { link = "DiagnosticFloatingWarn" })
  hi(0, "CocWarningHighlight", { link = "DiagnosticWarn" })
  hi(0, "CocWarningSign", { link = "DiagnosticSignWarn" })
  hi(0, "ColorColumn", { bg = "#999999" })
  hi(0, "Comment", { fg = "#626262" })
  hi(0, "Conceal", { fg = "#2e2e2e" })
  hi(0, "Constant", { fg = "#2e2e2e" })
  hi(0, "CurSearch", { bg = "#2e2e2e", fg = "#d5d5d5" })
  hi(0, "Cursor", { bg = "#2f2f2f", fg = "#d5d5d5" })
  hi(0, "CursorColumn", { bg = "#b6b6b6" })
  hi(0, "CursorIM", { link = "Cursor" })
  hi(0, "CursorLine", { bg = "#b6b6b6" })
  hi(0, "CursorLineFold", { fg = "#999999" })
  hi(0, "CursorLineNr", { bold = true, fg = "#2e2e2e" })
  hi(0, "CursorLineSign", { fg = "#999999" })
  hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#2f2f2f" })
  hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
  hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
  hi(0, "DapUIBreakpointsPath", { link = "Directory" })
  hi(0, "DapUIDecoration", { link = "Title" })
  hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
  hi(0, "DapUILineNumber", { link = "Title" })
  hi(0, "DapUIModifiedValue", { bold = true, fg = "#2e2e2e" })
  hi(0, "DapUIScope", { link = "Title" })
  hi(0, "DapUISource", { link = "Directory" })
  hi(0, "DapUIStoppedThread", { link = "Title" })
  hi(0, "DapUIThread", { link = "String" })
  hi(0, "DapUIType", { link = "Type" })
  hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
  hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
  hi(0, "DapUIWatchesValue", { link = "String" })
  hi(0, "DashboardCenter", { link = "Delimiter" })
  hi(0, "DashboardFooter", { link = "Comment" })
  hi(0, "DashboardHeader", { link = "Title" })
  hi(0, "DashboardShortCut", { link = "WarningMsg" })
  hi(0, "Definitions", { fg = "#2f2f2f" })
  hi(0, "DefinitionsIcon", { fg = "#2e2e2e" })
  hi(0, "Delimiter", { fg = "#2e2e2e" })
  hi(0, "DiagnosticDeprecated", { sp = "#2f2f2f", strikethrough = true })
  hi(0, "DiagnosticError", { fg = "#2f2f2f" })
  hi(0, "DiagnosticFloatingError", { bg = "#e3e3e3", fg = "#2f2f2f" })
  hi(0, "DiagnosticFloatingHint", { bg = "#e3e3e3", fg = "#2e2e2e" })
  hi(0, "DiagnosticFloatingInfo", { bg = "#e3e3e3", fg = "#2e2e2e" })
  hi(0, "DiagnosticFloatingOk", { bg = "#e3e3e3", fg = "#2f2f2f" })
  hi(0, "DiagnosticFloatingWarn", { bg = "#e3e3e3", fg = "#2e2e2e" })
  hi(0, "DiagnosticHint", { fg = "#2e2e2e" })
  hi(0, "DiagnosticInfo", { fg = "#2e2e2e" })
  hi(0, "DiagnosticOk", { fg = "#2f2f2f" })
  hi(0, "DiagnosticUnderlineError", { sp = "#481b39", undercurl = true })
  hi(0, "DiagnosticUnderlineHint", { sp = "#00432a", undercurl = true })
  hi(0, "DiagnosticUnderlineInfo", { sp = "#072f54", undercurl = true })
  hi(0, "DiagnosticUnderlineOk", { sp = "#343a00", underline = true })
  hi(0, "DiagnosticUnderlineWarn", { sp = "#503100", undercurl = true })
  hi(0, "DiagnosticWarn", { fg = "#2e2e2e" })
  hi(0, "DiffAdd", { fg = "#2f2f2f" })
  hi(0, "DiffAdded", { link = "DiffAdd" })
  hi(0, "DiffChange", { fg = "#2e2e2e" })
  hi(0, "DiffDelete", { fg = "#2f2f2f" })
  hi(0, "DiffFile", { bg = "#c2c2c2" })
  hi(0, "DiffLine", { bg = "#cecece" })
  hi(0, "DiffNewFile", { link = "DiffAdded" })
  hi(0, "DiffRemoved", { link = "DiffFile" })
  hi(0, "DiffText", { bg = "#999999" })
  hi(0, "Directory", { fg = "#2e2e2e" })
  hi(0, "EndOfBuffer", { fg = "#999999" })
  hi(0, "Error", { bg = "#d5d5d5" })
  hi(0, "ErrorMsg", { fg = "#2f2f2f" })
  hi(0, "FinderParam", { fg = "#2e2e2e" })
  hi(0, "FinderSpinner", { fg = "#2f2f2f" })
  hi(0, "FinderSpinnerBorder", { fg = "#2e2e2e" })
  hi(0, "FinderSpinnerTitle", { link = "Title" })
  hi(0, "FinderVirtText", { fg = "#2e2e2e" })
  hi(0, "Float", { link = "Constant" })
  hi(0, "FloatBorder", { bg = "#e3e3e3", fg = "#2e2e2e" })
  hi(0, "FloatShadow", { bg = "#ffffff", blend = 80 })
  hi(0, "FloatShadowThrough", { bg = "#ffffff", blend = 100 })
  hi(0, "FloatTitle", { bg = "#e3e3e3", bold = true, fg = "#2e2e2e" })
  hi(0, "FoldColumn", { fg = "#999999" })
  hi(0, "Folded", { bg = "#b6b6b6", fg = "#626262" })
  hi(0, "Function", { bold = true, fg = "#2e2e2e" })
  hi(0, "GitSignsAdd", { fg = "#2f2f2f" })
  hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
  hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
  hi(0, "GitSignsChange", { fg = "#2e2e2e" })
  hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
  hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
  hi(0, "GitSignsDelete", { fg = "#2f2f2f" })
  hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
  hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
  hi(0, "GitSignsStagedAdd", { fg = "#8b8b8b" })
  hi(0, "GitSignsStagedAddLn", { fg = "#8b8b8b" })
  hi(0, "GitSignsStagedAddNr", { fg = "#8b8b8b" })
  hi(0, "GitSignsStagedChange", { fg = "#8a8a8a" })
  hi(0, "GitSignsStagedChangeLn", { fg = "#8a8a8a" })
  hi(0, "GitSignsStagedChangeNr", { fg = "#8a8a8a" })
  hi(0, "GitSignsStagedChangedelete", { fg = "#8a8a8a" })
  hi(0, "GitSignsStagedChangedeleteLn", { fg = "#8a8a8a" })
  hi(0, "GitSignsStagedChangedeleteNr", { fg = "#8a8a8a" })
  hi(0, "GitSignsStagedDelete", { fg = "#8b8b8b" })
  hi(0, "GitSignsStagedDeleteLn", { fg = "#8b8b8b" })
  hi(0, "GitSignsStagedDeleteNr", { fg = "#8b8b8b" })
  hi(0, "GitSignsStagedTopdelete", { fg = "#8b8b8b" })
  hi(0, "GitSignsStagedTopdeleteNr", { fg = "#8b8b8b" })
  hi(0, "GitSignsUntracked", { fg = "#2e2e2e" })
  hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
  hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
  hi(0, "HopNextKey", { bold = true, fg = "#2f2f2f", nocombine = true })
  hi(0, "HopNextKey1", { bold = true, fg = "#2e2e2e", nocombine = true })
  hi(0, "HopNextKey2", { bold = true, fg = "#474747", nocombine = true })
  hi(0, "HopPreview", { bold = true, fg = "#2e2e2e", nocombine = true })
  hi(0, "HopUnmatched", { fg = "#999999" })
  hi(0, "HydraAmaranth", { fg = "#2e2e2e" })
  hi(0, "HydraBlue", { fg = "#2e2e2e" })
  hi(0, "HydraHint", { link = "NormalFloat" })
  hi(0, "HydraPink", { fg = "#2e2e2e" })
  hi(0, "HydraRed", { fg = "#2f2f2f" })
  hi(0, "HydraTeal", { fg = "#2e2e2e" })
  hi(0, "Identifier", { fg = "#2e2e2e" })
  hi(0, "Ignore", {})
  hi(0, "IncSearch", { bg = "#2e2e2e", fg = "#d5d5d5" })
  hi(0, "IndentBlanklineChar", { fg = "#999999", nocombine = true })
  hi(0, "IndentBlanklineContextChar", { fg = "#2e2e2e", nocombine = true })
  hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#4e1928", underline = true })
  hi(0, "IndentBlanklineIndent1", { fg = "#2e2e2e", nocombine = true })
  hi(0, "IndentBlanklineIndent2", { fg = "#2e2e2e", nocombine = true })
  hi(0, "IndentBlanklineIndent3", { fg = "#2e2e2e", nocombine = true })
  hi(0, "IndentBlanklineIndent4", { fg = "#2f2f2f", nocombine = true })
  hi(0, "IndentBlanklineIndent5", { fg = "#2e2e2e", nocombine = true })
  hi(0, "IndentBlanklineIndent6", { fg = "#2f2f2f", nocombine = true })
  hi(0, "IndentBlanklineIndent7", { fg = "#2e2e2e", nocombine = true })
  hi(0, "IndentBlanklineIndent8", { fg = "#2e2e2e", nocombine = true })
  hi(0, "Italic", { italic = true })
  hi(0, "LSOutlinePreviewBorder", { fg = "#2e2e2e" })
  hi(0, "LazyButton", { bg = "#b6b6b6" })
  hi(0, "LazyButtonActive", { bg = "#999999" })
  hi(0, "LazyDimmed", { link = "Comment" })
  hi(0, "LazyH1", { bg = "#999999", bold = true, fg = "#2e2e2e" })
  hi(0, "LeapBackdrop", { link = "Comment" })
  hi(0, "LeapLabelPrimary", { bold = true, fg = "#2e2e2e", nocombine = true })
  hi(0, "LeapLabelSecondary", { bold = true, fg = "#2f2f2f", nocombine = true })
  hi(0, "LeapLabelSelected", { bold = true, fg = "#2e2e2e", nocombine = true })
  hi(0, "LeapMatch", { bold = true, fg = "#2f2f2f", nocombine = true })
  hi(0, "LineNr", { fg = "#999999" })
  hi(0, "LspCodeLens", { link = "Comment" })
  hi(0, "LspCodeLensSeparator", { link = "Comment" })
  hi(0, "LspReferenceRead", { link = "LspReferenceText" })
  hi(0, "LspReferenceText", { bg = "#999999" })
  hi(0, "LspReferenceWrite", { link = "LspReferenceText" })
  hi(0, "LspSagaAutoPreview", { fg = "#2e2e2e" })
  hi(0, "LspSagaBorderTitle", { link = "FloatTitle" })
  hi(0, "LspSagaCodeActionBorder", { fg = "#2e2e2e" })
  hi(0, "LspSagaCodeActionContent", { fg = "#2f2f2f" })
  hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#2e2e2e" })
  hi(0, "LspSagaDefPreviewBorder", { fg = "#2e2e2e" })
  hi(0, "LspSagaDiagnosticBorder", { fg = "#2e2e2e" })
  hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
  hi(0, "LspSagaDiagnosticSource", { fg = "#2e2e2e" })
  hi(0, "LspSagaFinderSelection", { fg = "#2e2e2e" })
  hi(0, "LspSagaHoverBorder", { fg = "#2e2e2e" })
  hi(0, "LspSagaLspFinderBorder", { fg = "#2e2e2e" })
  hi(0, "LspSagaRenameBorder", { fg = "#2e2e2e" })
  hi(0, "LspSagaSignatureHelpBorder", { fg = "#2e2e2e" })
  hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
  hi(0, "MasonError", { fg = "#2f2f2f" })
  hi(0, "MasonHeader", { bg = "#2e2e2e", bold = true, fg = "#d5d5d5" })
  hi(0, "MasonHeaderSecondary", { bg = "#2e2e2e", bold = true, fg = "#d5d5d5" })
  hi(0, "MasonHeading", { link = "Bold" })
  hi(0, "MasonHighlight", { fg = "#2e2e2e" })
  hi(0, "MasonHighlightBlock", { bg = "#2e2e2e", fg = "#d5d5d5" })
  hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
  hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
  hi(0, "MasonHighlightBlockSecondary", { bg = "#2e2e2e", fg = "#d5d5d5" })
  hi(0, "MasonHighlightSecondary", { fg = "#2e2e2e" })
  hi(0, "MasonLink", { link = "MasonHighlight" })
  hi(0, "MasonMuted", { link = "Comment" })
  hi(0, "MasonMutedBlock", { bg = "#999999", fg = "#d5d5d5" })
  hi(0, "MasonMutedBlockBold", { bg = "#999999", bold = true, fg = "#d5d5d5" })
  hi(0, "MatchParen", { bg = "#999999", bold = true })
  hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
  hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
  hi(0, "MiniClueBorder", { link = "FloatBorder" })
  hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
  hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
  hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
  hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
  hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
  hi(0, "MiniClueTitle", { link = "FloatTitle" })
  hi(0, "MiniCompletionActiveParameter", { bg = "#999999" })
  hi(0, "MiniCursorword", { underline = true })
  hi(0, "MiniCursorwordCurrent", { underline = true })
  hi(0, "MiniFilesBorder", { link = "FloatBorder" })
  hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
  hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
  hi(0, "MiniFilesDirectory", { link = "Directory" })
  hi(0, "MiniFilesFile", { fg = "#2f2f2f" })
  hi(0, "MiniFilesNormal", { link = "NormalFloat" })
  hi(0, "MiniFilesTitle", { link = "FloatTitle" })
  hi(0, "MiniFilesTitleFocused", { bg = "#e3e3e3", bold = true, fg = "#2f2f2f" })
  hi(0, "MiniHipatternsFixme", { bg = "#2f2f2f", bold = true, fg = "#d5d5d5" })
  hi(0, "MiniHipatternsHack", { bg = "#2e2e2e", bold = true, fg = "#d5d5d5" })
  hi(0, "MiniHipatternsNote", { bg = "#2e2e2e", bold = true, fg = "#d5d5d5" })
  hi(0, "MiniHipatternsTodo", { bg = "#2e2e2e", bold = true, fg = "#d5d5d5" })
  hi(0, "MiniIndentscopeSymbol", { fg = "#2e2e2e" })
  hi(0, "MiniIndentscopeSymbolOff", { fg = "#2f2f2f" })
  hi(0, "MiniJump", { sp = "#4e1928", undercurl = true })
  hi(0, "MiniJump2dDim", { fg = "#999999" })
  hi(0, "MiniJump2dSpot", { bg = "#f1f1f1", bold = true, fg = "#0d0d0d", nocombine = true })
  hi(0, "MiniJump2dSpotAhead", { bg = "#f1f1f1", fg = "#1e1e1e", nocombine = true })
  hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
  hi(0, "MiniMapNormal", { bg = "#e3e3e3", fg = "#626262" })
  hi(0, "MiniMapSymbolCount", { fg = "#626262" })
  hi(0, "MiniMapSymbolLine", { fg = "#2e2e2e" })
  hi(0, "MiniMapSymbolView", { fg = "#2e2e2e" })
  hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
  hi(0, "MiniPickBorder", { link = "FloatBorder" })
  hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
  hi(0, "MiniPickBorderText", { link = "FloatTitle" })
  hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
  hi(0, "MiniPickIconDirectory", { link = "Directory" })
  hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
  hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
  hi(0, "MiniPickMatchMarked", { link = "Visual" })
  hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
  hi(0, "MiniPickNormal", { link = "NormalFloat" })
  hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
  hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
  hi(0, "MiniPickPrompt", { link = "DiagnosticFloatingInfo" })
  hi(0, "MiniStarterCurrent", { link = "MiniStarterItem" })
  hi(0, "MiniStarterFooter", { link = "Comment" })
  hi(0, "MiniStarterHeader", { bold = true, fg = "#2e2e2e" })
  hi(0, "MiniStarterInactive", { link = "Comment" })
  hi(0, "MiniStarterItemBullet", { fg = "#626262" })
  hi(0, "MiniStarterItemPrefix", { bold = true, fg = "#2e2e2e" })
  hi(0, "MiniStarterQuery", { bold = true, fg = "#2f2f2f" })
  hi(0, "MiniStarterSection", { fg = "#2e2e2e" })
  hi(0, "MiniStatuslineDevinfo", { bg = "#b6b6b6", fg = "#474747" })
  hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
  hi(0, "MiniStatuslineFilename", { bg = "#d5d5d5", fg = "#474747" })
  hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
  hi(0, "MiniStatuslineModeCommand", { bg = "#2e2e2e", bold = true, fg = "#d5d5d5" })
  hi(0, "MiniStatuslineModeInsert", { bg = "#2e2e2e", bold = true, fg = "#d5d5d5" })
  hi(0, "MiniStatuslineModeNormal", { bg = "#2f2f2f", bold = true, fg = "#d5d5d5" })
  hi(0, "MiniStatuslineModeOther", { bg = "#2e2e2e", bold = true, fg = "#d5d5d5" })
  hi(0, "MiniStatuslineModeReplace", { bg = "#2f2f2f", bold = true, fg = "#d5d5d5" })
  hi(0, "MiniStatuslineModeVisual", { bg = "#2f2f2f", bold = true, fg = "#d5d5d5" })
  hi(0, "MiniSurround", { link = "IncSearch" })
  hi(0, "MiniTablineCurrent", { bg = "#d5d5d5", bold = true, fg = "#2e2e2e" })
  hi(0, "MiniTablineFill", { link = "MiniTablineHidden" })
  hi(0, "MiniTablineHidden", { bg = "#e3e3e3", fg = "#474747" })
  hi(0, "MiniTablineModifiedCurrent", { bg = "#2e2e2e", bold = true, fg = "#d5d5d5" })
  hi(0, "MiniTablineModifiedHidden", { bg = "#474747", fg = "#e3e3e3" })
  hi(0, "MiniTablineModifiedVisible", { bg = "#474747", bold = true, fg = "#e3e3e3" })
  hi(0, "MiniTablineTabpagesection", { bg = "#2f2f2f", bold = true, fg = "#d5d5d5" })
  hi(0, "MiniTablineVisible", { bg = "#e3e3e3", bold = true, fg = "#474747" })
  hi(0, "MiniTestEmphasis", { bold = true })
  hi(0, "MiniTestFail", { bold = true, fg = "#2f2f2f" })
  hi(0, "MiniTestPass", { bold = true, fg = "#2f2f2f" })
  hi(0, "MiniTrailspace", { bg = "#d5d5d5" })
  hi(0, "ModeMsg", { fg = "#2f2f2f" })
  hi(0, "MoreMsg", { fg = "#2e2e2e" })
  hi(0, "MsgArea", { link = "Normal" })
  hi(0, "MsgSeparator", { bg = "#999999", fg = "#626262" })
  hi(0, "NeoTreeDimText", { fg = "#999999" })
  hi(0, "NeoTreeDotfile", { fg = "#474747" })
  hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
  hi(0, "NeoTreeFadeText2", { fg = "#999999" })
  hi(0, "NeoTreeGitAdded", { fg = "#2f2f2f" })
  hi(0, "NeoTreeGitConflict", { bold = true, fg = "#2e2e2e" })
  hi(0, "NeoTreeGitDeleted", { fg = "#2f2f2f" })
  hi(0, "NeoTreeGitModified", { fg = "#2e2e2e" })
  hi(0, "NeoTreeGitUnstaged", { fg = "#2e2e2e" })
  hi(0, "NeoTreeGitUntracked", { fg = "#2e2e2e" })
  hi(0, "NeoTreeMessage", { bg = "#b6b6b6", fg = "#2f2f2f" })
  hi(0, "NeoTreeModified", { fg = "#1e1e1e" })
  hi(0, "NeoTreeRootName", { bold = true, fg = "#2e2e2e" })
  hi(0, "NeoTreeTabInactive", { fg = "#626262" })
  hi(0, "NeoTreeTabSeparatorActive", { bg = "#999999", fg = "#626262" })
  hi(0, "NeoTreeTabSeparatorInactive", { bg = "#b6b6b6", fg = "#b6b6b6" })
  hi(0, "NeogitCommitViewHeader", { link = "Special" })
  hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
  hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
  hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
  hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
  hi(0, "NeogitFold", { link = "FoldColumn" })
  hi(0, "NeogitHunkHeader", { fg = "#2e2e2e" })
  hi(0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#2e2e2e" })
  hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
  hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
  hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
  hi(0, "NoiceCmdlinePopupBorder", { fg = "#2e2e2e" })
  hi(0, "NoiceConfirmBorder", { fg = "#2e2e2e" })
  hi(0, "NoiceFormatProgressDone", { bg = "#2e2e2e", fg = "#d5d5d5" })
  hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
  hi(0, "NonText", { fg = "#999999" })
  hi(0, "Normal", { bg = "#d5d5d5", fg = "#2f2f2f" })
  hi(0, "NormalFloat", { bg = "#e3e3e3", fg = "#2f2f2f" })
  hi(0, "NormalNC", { link = "Normal" })
  hi(0, "NotifyDEBUGBorder", { fg = "#2f2f2f" })
  hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
  hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
  hi(0, "NotifyERRORBorder", { fg = "#2f2f2f" })
  hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
  hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
  hi(0, "NotifyINFOBorder", { fg = "#2e2e2e" })
  hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
  hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
  hi(0, "NotifyTRACEBorder", { fg = "#2e2e2e" })
  hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
  hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
  hi(0, "NotifyWARNBorder", { fg = "#2e2e2e" })
  hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
  hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
  hi(0, "NvimInternalError", { bg = "#666666", ctermbg = 9, ctermfg = 9, fg = "#666666" })
  hi(0, "NvimTreeExecFile", { bold = true, fg = "#2f2f2f" })
  hi(0, "NvimTreeFolderIcon", { fg = "#626262" })
  hi(0, "NvimTreeGitDeleted", { fg = "#2f2f2f" })
  hi(0, "NvimTreeGitDirty", { fg = "#2e2e2e" })
  hi(0, "NvimTreeGitMerge", { fg = "#2e2e2e" })
  hi(0, "NvimTreeGitNew", { fg = "#2e2e2e" })
  hi(0, "NvimTreeGitRenamed", { fg = "#2e2e2e" })
  hi(0, "NvimTreeGitStaged", { fg = "#2f2f2f" })
  hi(0, "NvimTreeImageFile", { fg = "#2e2e2e" })
  hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
  hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
  hi(0, "NvimTreeRootFolder", { bold = true, fg = "#2e2e2e" })
  hi(0, "NvimTreeSpecialFile", { fg = "#2e2e2e", underline = true })
  hi(0, "NvimTreeSymlink", { bold = true, fg = "#2e2e2e" })
  hi(0, "NvimTreeWindowPicker", { bg = "#999999", bold = true, fg = "#2f2f2f" })
  hi(0, "Operator", { fg = "#2f2f2f" })
  hi(0, "OutlineDetail", { fg = "#999999" })
  hi(0, "OutlineFoldPrefix", { fg = "#2e2e2e" })
  hi(0, "OutlineIndentEvn", { fg = "#626262" })
  hi(0, "OutlineIndentOdd", { fg = "#2f2f2f" })
  hi(0, "Pmenu", { bg = "#b6b6b6", fg = "#2f2f2f" })
  hi(0, "PmenuSbar", { link = "Pmenu" })
  hi(0, "PmenuSel", { bg = "#2f2f2f", blend = 0, fg = "#d5d5d5" })
  hi(0, "PmenuThumb", { bg = "#999999" })
  hi(0, "PounceAccept", { bg = "#2e2e2e", bold = true, fg = "#d5d5d5", nocombine = true })
  hi(0, "PounceAcceptBest", { bg = "#2f2f2f", bold = true, fg = "#d5d5d5", nocombine = true })
  hi(0, "PounceGap", { bg = "#999999", bold = true, fg = "#d5d5d5", nocombine = true })
  hi(0, "PounceMatch", { bg = "#2f2f2f", bold = true, fg = "#d5d5d5", nocombine = true })
  hi(0, "PreProc", { fg = "#2e2e2e" })
  hi(0, "Question", { fg = "#2e2e2e" })
  hi(0, "QuickFixLine", { bg = "#b6b6b6" })
  hi(0, "RainbowDelimiterBlue", { fg = "#2e2e2e" })
  hi(0, "RainbowDelimiterCyan", { fg = "#2e2e2e" })
  hi(0, "RainbowDelimiterGreen", { fg = "#2f2f2f" })
  hi(0, "RainbowDelimiterOrange", { fg = "#2e2e2e" })
  hi(0, "RainbowDelimiterRed", { fg = "#2f2f2f" })
  hi(0, "RainbowDelimiterViolet", { fg = "#2e2e2e" })
  hi(0, "RainbowDelimiterYellow", { fg = "#2e2e2e" })
  hi(0, "RedrawDebugClear", { bg = "#050505", ctermbg = 11 })
  hi(0, "RedrawDebugComposed", { bg = "#858585", ctermbg = 10 })
  hi(0, "RedrawDebugRecompose", { bg = "#666666", ctermbg = 9 })
  hi(0, "References", { fg = "#2f2f2f" })
  hi(0, "ReferencesIcon", { fg = "#2e2e2e" })
  hi(0, "Search", { bg = "#2e2e2e", fg = "#d5d5d5" })
  hi(0, "SignColumn", { fg = "#999999" })
  hi(0, "Sneak", { bg = "#2e2e2e", fg = "#d5d5d5" })
  hi(0, "SneakLabel", { bg = "#2e2e2e", bold = true, fg = "#d5d5d5" })
  hi(0, "SneakScope", { bg = "#0d0d0d", fg = "#d5d5d5" })
  hi(0, "Special", { fg = "#2e2e2e" })
  hi(0, "SpecialKey", { fg = "#999999" })
  hi(0, "SpellBad", { sp = "#481b39", undercurl = true })
  hi(0, "SpellCap", { sp = "#00432a", undercurl = true })
  hi(0, "SpellLocal", { sp = "#503100", undercurl = true })
  hi(0, "SpellRare", { sp = "#072f54", undercurl = true })
  hi(0, "Statement", { bold = true })
  hi(0, "StatusLine", { bg = "#d5d5d5", fg = "#474747" })
  hi(0, "StatusLineNC", { bg = "#e3e3e3", fg = "#474747" })
  hi(0, "String", { fg = "#2f2f2f" })
  hi(0, "Substitute", { bg = "#2e2e2e", fg = "#d5d5d5" })
  hi(0, "TabLine", { bg = "#e3e3e3", fg = "#474747" })
  hi(0, "TabLineFill", { link = "TabLine" })
  hi(0, "TabLineSel", { bg = "#e3e3e3", fg = "#2e2e2e" })
  hi(0, "TargetFileName", { fg = "#2f2f2f" })
  hi(0, "TelescopeBorder", { fg = "#2e2e2e" })
  hi(0, "TelescopeMatching", { bold = true })
  hi(0, "TelescopeMultiSelection", { bg = "#999999" })
  hi(0, "TelescopeSelection", { bg = "#b6b6b6" })
  hi(0, "TermCursorNC", { reverse = true })
  hi(0, "Title", { fg = "#2e2e2e" })
  hi(0, "Todo", { bg = "#d5d5d5", bold = true, fg = "#2e2e2e" })
  hi(0, "TroubleCount", { bold = true, fg = "#2e2e2e" })
  hi(0, "TroubleFoldIcon", { bold = true, fg = "#2e2e2e" })
  hi(0, "TroubleIndent", { fg = "#999999" })
  hi(0, "TroubleLocation", { fg = "#474747" })
  hi(0, "TroubleSignError", { link = "DiagnosticError" })
  hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
  hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
  hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
  hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
  hi(0, "TroubleText", { fg = "#2f2f2f" })
  hi(0, "TroubleTextError", { link = "TroubleText" })
  hi(0, "TroubleTextHint", { link = "TroubleText" })
  hi(0, "TroubleTextInformation", { link = "TroubleText" })
  hi(0, "TroubleTextWarning", { link = "TroubleText" })
  hi(0, "Type", { fg = "#2f2f2f" })
  hi(0, "UfoFoldedBg", { bg = "#b6b6b6" })
  hi(0, "UfoFoldedFg", { fg = "#2f2f2f" })
  hi(0, "Underlined", { underline = true })
  hi(0, "VertSplit", { fg = "#2e2e2e" })
  hi(0, "Visual", { bg = "#999999" })
  hi(0, "VisualNOS", { bg = "#b6b6b6" })
  hi(0, "WarningMsg", { fg = "#2e2e2e" })
  hi(0, "WhichKey", { fg = "#2e2e2e" })
  hi(0, "WhichKeyBorder", { link = "FloatBorder" })
  hi(0, "WhichKeyDesc", { fg = "#2f2f2f" })
  hi(0, "WhichKeyFloat", { bg = "#e3e3e3", fg = "#2f2f2f" })
  hi(0, "WhichKeyGroup", { fg = "#2f2f2f" })
  hi(0, "WhichKeySeparator", { fg = "#2f2f2f" })
  hi(0, "WhichKeyValue", { link = "Comment" })
  hi(0, "Whitespace", { fg = "#999999" })
  hi(0, "WildMenu", { link = "PmenuSel" })
  hi(0, "WinBar", { link = "StatusLine" })
  hi(0, "WinBarNC", { link = "StatusLineNC" })
  hi(0, "WinSeparator", { fg = "#2e2e2e" })
  hi(0, "gitcommitBranch", { bold = true, fg = "#2e2e2e" })
  hi(0, "gitcommitComment", { link = "Comment" })
  hi(0, "gitcommitDiscarded", { link = "Comment" })
  hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#2e2e2e" })
  hi(0, "gitcommitDiscardedType", { fg = "#2e2e2e" })
  hi(0, "gitcommitHeader", { link = "Title" })
  hi(0, "gitcommitOverflow", { fg = "#2e2e2e" })
  hi(0, "gitcommitSelected", { link = "Comment" })
  hi(0, "gitcommitSelectedFile", { bold = true, fg = "#2f2f2f" })
  hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
  hi(0, "gitcommitSummary", { fg = "#2f2f2f" })
  hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
  hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
  hi(0, "gitcommitUntracked", { link = "Comment" })
  hi(0, "gitcommitUntrackedFile", { fg = "#2e2e2e" })
  hi(0, "lCursor", { bg = "#2f2f2f", fg = "#d5d5d5" })

  -- Terminal colors
  local g = vim.g

  g.terminal_color_0 = "#d5d5d5"
  g.terminal_color_1 = "#2f2f2f"
  g.terminal_color_2 = "#2f2f2f"
  g.terminal_color_3 = "#2e2e2e"
  g.terminal_color_4 = "#2e2e2e"
  g.terminal_color_5 = "#2e2e2e"
  g.terminal_color_6 = "#2e2e2e"
  g.terminal_color_7 = "#2f2f2f"
  g.terminal_color_8 = "#d5d5d5"
  g.terminal_color_9 = "#2f2f2f"
  g.terminal_color_10 = "#2f2f2f"
  g.terminal_color_11 = "#2e2e2e"
  g.terminal_color_12 = "#2e2e2e"
  g.terminal_color_13 = "#2e2e2e"
  g.terminal_color_14 = "#2e2e2e"
  g.terminal_color_15 = "#2f2f2f"
end
