-- TODO: Port mini modules

return {
  { name = [[mini.ai]],                          [[mini.ai]],                                                                                                       dev = true },
  { name = [[mini.align]],                       [[mini.align]],                                                                                                    dev = true },
  { name = [[mini.animate]],                     [[mini.animate]],                                                                                                  dev = true },
  { name = [[mini.base16]],                      [[mini.base16]],                                                                                                   dev = true },
  { name = [[mini.basics]],                      [[mini.basics]],                                                                                                   dev = true },
  { name = [[mini.bracketed]],                   [[mini.bracketed]],                                                                                                dev = true },
  { name = [[mini.bufremove]],                   [[mini.bufremove]],                                                                                                dev = true },
  { name = [[mini.clue]],                        [[mini.clue]],                                                                                                     dev = true },
  { name = [[mini.colors]],                      [[mini.colors]],                                                                                                   dev = true },
  { name = [[mini.comment]],                     [[mini.comment]],                                                                                                  dev = true },
  { name = [[mini.completion]],                  [[mini.completion]],                                                                                               dev = true },
  { name = [[mini.cursorword]],                  [[mini.cursorword]],                                                                                               dev = true },
  { name = [[mini.deps]],                        [[mini.deps]],                                                                                                     dev = true },
  { name = [[mini.diff]],                        [[mini.diff]],                                                                                                     dev = true },
  { name = [[mini.doc]],                         [[mini.doc]],                                                                                                      dev = true },
  { name = [[mini.extra]],                       [[mini.extra]],                                                                                                    dev = true },
  { name = [[mini.files]],                       [[mini.files]],                                                                                                    dev = true },
  { name = [[mini.fuzzy]],                       [[mini.fuzzy]],                                                                                                    dev = true },
  { name = [[mini.hipatterns]],                  [[mini.hipatterns]],                                                                                               dev = true },
  { name = [[mini.hues]],                        [[mini.hues]],                                                                                                     dev = true },
  { name = [[mini.icons]],                       [[mini.icons]],                                                                                                    dev = true },
  { name = [[mini.indentscope]],                 [[mini.indentscope]],                                                                                              dev = true },
  { name = [[mini.jump2d]],                      [[mini.jump2d]],                                                                                                   dev = true },
  { name = [[mini.jump]],                        [[mini.jump]],                                                                                                     dev = true },
  { name = [[mini.map]],                         [[mini.map]],                                                                                                      dev = true },
  { name = [[mini.misc]],                        [[mini.misc]],                                                                                                     dev = true },
  { name = [[mini.move]],                        [[mini.move]],                                                                                                     dev = true },
  { name = [[mini.notify]],                      [[mini.notify]],                                                                                                   dev = true },
  { name = [[mini.operators]],                   [[mini.operators]],                                                                                                dev = true },
  { name = [[mini.pairs]],                       [[mini.pairs]],                                                                                                    dev = true },
  { name = [[mini.pick]],                        [[mini.pick]],                                                                                                     dev = true },
  { name = [[mini.sessions]],                    [[mini.sessions]],                                                                                                 dev = true },
  { name = [[mini.splitjoin]],                   [[mini.splitjoin]],                                                                                                dev = true },
  { name = [[mini.starter]],                     [[mini.starter]],                                                                                                  dev = true },
  { name = [[mini.statusline]],                  [[mini.statusline]],                                                                                               dev = true },
  { name = [[mini.surround]],                    [[mini.surround]],                                                                                                 dev = true },
  { name = [[mini.tabline]],                     [[mini.tabline]],                                                                                                  dev = true },
  { name = [[mini.test]],                        [[mini.test]],                                                                                                     dev = true },
  { name = [[mini.trailspace]],                  [[mini.trailspace]],                                                                                               dev = true },
  { name = [[mini.visits]],                      [[mini.visits]],                                                                                                   dev = true },
  { name = [[mini]],                             [[echasnovski/mini.nvim]],                                                                                       lazy = false },

  { import = [[spec.mini]] }
}
