# https://starship.rs/config/

format = '$container\[$username@$hostname$directory$git_branch$git_commit\]$character'
add_newline = false

[container]
format = '[$symbol](purple)'
symbol = '⬢'

[username]
format = '$user'
show_always = true

[hostname]
format = '$hostname'
ssh_only = false

[directory]
format = ' $path'
truncation_length = 1

[git_branch]
format = ''' \($branch\)'''
only_attached = true

[git_commit]
format = ''' \($hash\)'''
only_detached = true

[character]
error_symbol = '\$'
success_symbol = '\$'
