on:
  workflow_dispatch:

jobs:
  chezmoi:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sh -c "$(curl -fsLS get.chezmoi.io)" -- init --one-shot wroyca
