name: Fedora Workstation

on:
  workflow_dispatch:
    branches:
      - ergodox

jobs:
  chezmoi:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sh -c "$(curl -fsLS get.chezmoi.io)" -- init --one-shot wroyca --branch ergodox
      - run: |
          sudo dnf install -y zsh
      - run: |
          curl -L https://raw.githubusercontent.com/molovo/revolver/master/revolver > /usr/bin/revolver && chmod +x /usr/bin/revolver
          curl -L https://github.com/zunit-zsh/zunit/releases/download/v0.8.2/zunit > /usr/bin/zunit && chmod +x /usr/bin/zunit
          zunit --output-text
        shell: zsh {0}

      - name: Summarising TAP (Test Anything Protocol) test results
        uses: pcolby/tap-summary@v1
        if: ${{ always() }}
        with:
          path: tests/_output/output.txt
